// packages/angular/projects/admin/src/app/pages/menu-categories/menu-categories-page.ts
import { type CdkDragDrop, DragDropModule, moveItemInArray } from '@angular/cdk/drag-drop';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';

import { MenuCategoriesService, type ProductTypeConfig } from './menu-categories.service';

/**
 * Menu categories editor — drag-to-reorder via `@angular/cdk/drag-drop`
 * (admin's CLAUDE.md explicitly permits CDK in this app). Local edit
 * signals diverge from the server snapshot so the user can dirty-check
 * the list and reset before saving. Save sends the full ordered array;
 * backend persists `sortOrder` sequentially.
 *
 * Toggle (eye/eye-off) flips `isEnabled` per row.
 */
@Component({
  selector: 'cs-menu-categories-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DragDropModule],
  template: `
    <section class="max-w-2xl space-y-6">
      <header>
        <h1 class="text-2xl font-bold text-(--color-text)">Menu categories</h1>
        <p class="mt-1 text-sm text-(--color-text-muted)">
          Choose which product types appear on your storefront menu and set their display order.
          Drag to reorder, toggle to show or hide.
        </p>
      </header>

      @if (isLoading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading menu categories…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load menu categories</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else {
        <div class="flex items-center gap-4 text-sm">
          <span class="text-(--color-text-secondary)">
            <strong class="text-(--color-text)">{{ enabledCount() }}</strong>
            of {{ items().length }} categories visible
          </span>
          @if (dirty()) {
            <span class="font-medium text-amber-500">Unsaved changes</span>
          }
          @if (savedTick()) {
            <span class="font-medium text-emerald-500" role="status">Saved!</span>
          }
        </div>

        <ul
          cdkDropList
          (cdkDropListDropped)="onDrop($event)"
          class="overflow-hidden rounded-xl border border-(--color-border) bg-(--color-surface)"
          aria-label="Menu categories"
        >
          @for (item of items(); track item.productTypeId; let i = $index) {
            <li
              cdkDrag
              class="flex items-center gap-3 border-b border-(--color-border) px-4 py-3 transition-colors last:border-b-0"
              [class.opacity-50]="!item.isEnabled"
            >
              <span
                cdkDragHandle
                class="cursor-grab p-1 text-(--color-text-muted) hover:text-(--color-text) active:cursor-grabbing"
                [attr.aria-label]="'Drag to reorder ' + item.name"
                aria-hidden="false"
              >
                ⠿
              </span>

              <span class="w-6 text-center font-mono text-xs text-(--color-text-muted)">
                {{ i + 1 }}
              </span>

              <span
                class="flex-1 text-sm font-medium"
                [class]="
                  item.isEnabled ? 'text-(--color-text)' : 'text-(--color-text-muted) line-through'
                "
              >
                {{ item.name }}
              </span>

              <span
                class="rounded bg-(--color-bg) px-2 py-0.5 font-mono text-[10px] text-(--color-text-muted)"
              >
                {{ item.code }}
              </span>

              <button
                type="button"
                (click)="onToggle(i)"
                [attr.aria-label]="(item.isEnabled ? 'Hide ' : 'Show ') + item.name"
                class="rounded-lg p-2 transition-colors"
                [class]="
                  item.isEnabled
                    ? 'text-emerald-500 hover:bg-emerald-500/10'
                    : 'text-(--color-text-muted) hover:bg-(--color-surface-hover)'
                "
              >
                {{ item.isEnabled ? '👁' : '🚫' }}
              </button>
            </li>
          }
        </ul>

        <div class="flex items-center gap-3">
          <button
            type="button"
            (click)="onSave()"
            [disabled]="!dirty() || saving()"
            class="rounded-lg bg-(--color-primary) px-6 py-2.5 text-sm font-semibold text-white hover:bg-(--color-primary-hover) disabled:cursor-not-allowed disabled:opacity-50"
          >
            @if (saving()) {
              Saving…
            } @else {
              Save order
            }
          </button>
          @if (dirty()) {
            <button
              type="button"
              (click)="onReset()"
              class="px-4 py-2.5 text-sm text-(--color-text-muted) hover:text-(--color-text)"
              aria-label="Reset to saved order"
            >
              ↺ Reset
            </button>
          }
        </div>

        <div class="space-y-1 text-xs text-(--color-text-muted)">
          <p>
            Customers see only enabled categories on the storefront menu, in the order shown above.
          </p>
          <p>
            Disabling a category hides it from the menu but does not affect existing products or
            inventory.
          </p>
        </div>
      }
    </section>
  `,
})
export class MenuCategoriesPage {
  private readonly svc = inject(MenuCategoriesService);

  protected readonly isLoading = this.svc.isLoading;
  protected readonly error = this.svc.error;
  protected readonly saving = this.svc.saving;

  /** Local edit state — diverges from server until Save or Reset. */
  protected readonly items = signal<readonly ProductTypeConfig[]>([]);
  protected readonly savedTick = signal<boolean>(false);

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load menu categories.';
  });

  protected readonly enabledCount = computed(() => this.items().filter((t) => t.isEnabled).length);

  protected readonly dirty = computed(() => {
    const server = this.svc.types();
    const local = this.items();
    if (server.length !== local.length) return true;
    for (let i = 0; i < server.length; i++) {
      if (
        server[i].productTypeId !== local[i].productTypeId ||
        server[i].isEnabled !== local[i].isEnabled
      ) {
        return true;
      }
    }
    return false;
  });

  constructor() {
    // Re-seed local edit state whenever the server snapshot changes.
    effect(() => {
      const server = this.svc.types();
      this.items.set([...server]);
    });
  }

  protected onDrop(event: CdkDragDrop<readonly ProductTypeConfig[]>): void {
    if (event.previousIndex === event.currentIndex) return;
    this.items.update((prev) => {
      const next = [...prev];
      moveItemInArray(next, event.previousIndex, event.currentIndex);
      return next;
    });
  }

  protected onToggle(index: number): void {
    this.items.update((prev) =>
      prev.map((item, i) => (i === index ? { ...item, isEnabled: !item.isEnabled } : item)),
    );
  }

  protected async onSave(): Promise<void> {
    const payload = this.items().map((t, i) => ({
      productTypeId: t.productTypeId,
      isEnabled: t.isEnabled,
      sortOrder: i,
    }));
    await this.svc.save(payload);
    this.savedTick.set(true);
    setTimeout(() => this.savedTick.set(false), 3000);
  }

  protected onReset(): void {
    this.items.set([...this.svc.types()]);
  }
}

// apps/admin/src/pages/MenuCategoriesPage.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { GripVertical, Eye, EyeOff, Save, RotateCcw, Loader2 } from 'lucide-react';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';

// ── GraphQL ──────────────────────────────────────────────────

const GET_TYPES = `query($dispensaryId: ID!) {
  dispensaryProductTypes(dispensaryId: $dispensaryId) {
    productTypeId code name isEnabled sortOrder
  }
}`;

const SAVE_TYPES = `mutation($dispensaryId: ID!, $types: [DispensaryProductTypeInput!]!) {
  saveDispensaryProductTypes(dispensaryId: $dispensaryId, types: $types) {
    productTypeId code name isEnabled sortOrder
  }
}`;

// ── Types ────────────────────────────────────────────────────

interface ProductTypeConfig {
  productTypeId: number;
  code: string;
  name: string;
  isEnabled: boolean;
  sortOrder: number;
}

// ── Component ────────────────────────────────────────────────

export function MenuCategoriesPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const queryClient = useQueryClient();

  const [items, setItems] = useState<ProductTypeConfig[]>([]);
  const [dirty, setDirty] = useState(false);
  const [saved, setSaved] = useState(false);

  // Drag state
  const dragIdx = useRef<number | null>(null);
  const [dragOverIdx, setDragOverIdx] = useState<number | null>(null);

  // ── Fetch ──────────────────────────────────────────────────

  const { data, isLoading } = useQuery({
    queryKey: ['dispensaryProductTypes', dispensaryId],
    queryFn: () =>
      gqlRequest<{ dispensaryProductTypes: ProductTypeConfig[] }>(GET_TYPES, { dispensaryId }),
    select: (d) => d.dispensaryProductTypes,
    enabled: !!dispensaryId,
  });

  useEffect(() => {
    if (data) {
      setItems([...data].sort((a, b) => a.sortOrder - b.sortOrder));
      setDirty(false);
    }
  }, [data]);

  // ── Save ───────────────────────────────────────────────────

  const mutation = useMutation({
    mutationFn: () =>
      gqlRequest(SAVE_TYPES, {
        dispensaryId,
        types: items.map((t, i) => ({
          productTypeId: t.productTypeId,
          isEnabled: t.isEnabled,
          sortOrder: i,
        })),
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['dispensaryProductTypes'] });
      setDirty(false);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    },
  });

  // ── Toggle ─────────────────────────────────────────────────

  const toggle = useCallback((idx: number) => {
    setItems((prev) =>
      prev.map((item, i) =>
        i === idx ? { ...item, isEnabled: !item.isEnabled } : item,
      ),
    );
    setDirty(true);
  }, []);

  // ── Drag handlers ──────────────────────────────────────────

  const handleDragStart = (idx: number) => {
    dragIdx.current = idx;
  };

  const handleDragOver = (e: React.DragEvent, idx: number) => {
    e.preventDefault();
    setDragOverIdx(idx);
  };

  const handleDrop = (idx: number) => {
    const from = dragIdx.current;
    if (from === null || from === idx) {
      dragIdx.current = null;
      setDragOverIdx(null);
      return;
    }

    setItems((prev) => {
      const copy = [...prev];
      const [moved] = copy.splice(from, 1);
      copy.splice(idx, 0, moved);
      return copy;
    });
    setDirty(true);
    dragIdx.current = null;
    setDragOverIdx(null);
  };

  const handleDragEnd = () => {
    dragIdx.current = null;
    setDragOverIdx(null);
  };

  // ── Reset ──────────────────────────────────────────────────

  const reset = () => {
    if (data) {
      setItems([...data].sort((a, b) => a.sortOrder - b.sortOrder));
      setDirty(false);
    }
  };

  // ── Render ─────────────────────────────────────────────────

  if (isLoading) {
    return (
      <div className="flex items-center gap-2 text-txt-muted py-12">
        <Loader2 size={18} className="animate-spin" /> Loading menu categories...
      </div>
    );
  }

  const enabledCount = items.filter((t) => t.isEnabled).length;

  return (
    <div className="max-w-2xl">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-txt">Menu Categories</h1>
        <p className="text-sm text-txt-muted mt-1">
          Choose which product types appear on your storefront menu and set their display order.
          Drag to reorder, toggle to show or hide.
        </p>
      </div>

      {/* Stats bar */}
      <div className="flex items-center gap-4 mb-4 text-sm">
        <span className="text-txt-secondary">
          <strong className="text-txt">{enabledCount}</strong> of {items.length} categories visible
        </span>
        {dirty && (
          <span className="text-warning font-medium">Unsaved changes</span>
        )}
        {saved && (
          <span className="text-success font-medium">Saved!</span>
        )}
      </div>

      {/* Sortable list */}
      <div className="bg-surface rounded-xl border border-bdr overflow-hidden">
        {items.map((item, idx) => (
          <div
            key={item.productTypeId}
            draggable
            onDragStart={() => handleDragStart(idx)}
            onDragOver={(e) => handleDragOver(e, idx)}
            onDrop={() => handleDrop(idx)}
            onDragEnd={handleDragEnd}
            className={[
              'flex items-center gap-3 px-4 py-3 transition-all',
              'border-b border-bdr last:border-b-0',
              dragOverIdx === idx ? 'bg-brand-50 border-brand-300' : '',
              !item.isEnabled ? 'opacity-50' : '',
            ].join(' ')}
          >
            {/* Drag handle */}
            <div
              className="cursor-grab active:cursor-grabbing text-txt-faint hover:text-txt-muted p-1"
              aria-label={`Drag to reorder ${item.name}`}
            >
              <GripVertical size={16} />
            </div>

            {/* Sort number */}
            <span className="w-6 text-center text-xs font-mono text-txt-faint">
              {idx + 1}
            </span>

            {/* Name */}
            <span className={`flex-1 text-sm font-medium ${item.isEnabled ? 'text-txt' : 'text-txt-muted line-through'}`}>
              {item.name}
            </span>

            {/* Code badge */}
            <span className="text-[10px] font-mono text-txt-faint bg-bg-alt px-2 py-0.5 rounded">
              {item.code}
            </span>

            {/* Toggle */}
            <button
              onClick={() => toggle(idx)}
              aria-label={`${item.isEnabled ? 'Hide' : 'Show'} ${item.name}`}
              className={[
                'p-2 rounded-lg transition-colors',
                item.isEnabled
                  ? 'text-success hover:bg-success-bg'
                  : 'text-txt-faint hover:bg-bg-alt',
              ].join(' ')}
            >
              {item.isEnabled ? <Eye size={18} /> : <EyeOff size={18} />}
            </button>
          </div>
        ))}
      </div>

      {/* Action buttons */}
      <div className="flex items-center gap-3 mt-6">
        <button
          onClick={() => mutation.mutate()}
          disabled={!dirty || mutation.isPending}
          className="flex items-center gap-2 bg-brand-600 text-txt-inverse font-semibold px-6 py-2.5 rounded-lg hover:bg-brand-500 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {mutation.isPending ? (
            <><Loader2 size={16} className="animate-spin" /> Saving...</>
          ) : (
            <><Save size={16} /> Save Order</>
          )}
        </button>

        {dirty && (
          <button
            onClick={reset}
            className="flex items-center gap-2 text-sm text-txt-muted hover:text-txt transition-colors px-4 py-2.5"
          >
            <RotateCcw size={14} /> Reset
          </button>
        )}
      </div>

      {/* Help text */}
      <div className="mt-8 text-xs text-txt-faint space-y-1">
        <p>Customers will see only enabled categories on the storefront menu, in the order shown above.</p>
        <p>Disabling a category hides it from the menu but does not affect existing products or inventory.</p>
      </div>
    </div>
  );
}

export default MenuCategoriesPage;
