// packages/angular/projects/admin/src/app/pages/orders/orders-page.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';

import { DashboardService } from '../dashboard/dashboard.service';
import { OrdersService, type OrderListItem, type OrderStatusFilter } from './orders.service';

const STATUS_FILTERS: ReadonlyArray<{ key: OrderStatusFilter; label: string }> = [
  { key: 'all', label: 'All' },
  { key: 'pending', label: 'Pending' },
  { key: 'confirmed', label: 'Confirmed' },
  { key: 'preparing', label: 'Preparing' },
  { key: 'ready_for_pickup', label: 'Ready for pickup' },
  { key: 'completed', label: 'Completed' },
  { key: 'cancelled', label: 'Cancelled' },
];

const TERMINAL_STATUSES = new Set<string>(['completed', 'cancelled', 'picked_up', 'delivered']);

/**
 * Admin orders list + detail. Mirrors the React `OrdersPage`:
 * KPI cards (reused `DashboardService`), status filter pills, row
 * table, side detail panel, cancel-order flow with reason capture.
 *
 * Per-order state transitions (confirm / start preparing / mark ready
 * / complete) are intentionally **out of scope** for sc-631 — those
 * `*GQL` ops already exist but the React admin doesn't surface them
 * either (transitions happen via staff POS flows). File a follow-up
 * story if admin needs to drive transitions manually.
 */
@Component({
  selector: 'cs-orders-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="space-y-6">
      <h1 class="text-2xl font-bold text-(--color-text)">Orders</h1>

      <!-- KPI cards -->
      <div class="grid grid-cols-1 gap-4 md:grid-cols-4">
        <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-5">
          <p class="mb-2 text-sm text-(--color-text-secondary)">Total</p>
          <p class="text-2xl font-bold text-(--color-text) tabular-nums">
            {{ sales()?.totalOrders ?? 0 }}
          </p>
        </article>
        <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-5">
          <p class="mb-2 text-sm text-emerald-500">Completed</p>
          <p class="text-2xl font-bold text-emerald-500 tabular-nums">
            {{ sales()?.completedOrders ?? 0 }}
          </p>
        </article>
        <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-5">
          <p class="mb-2 text-sm text-amber-500">Pending</p>
          <p class="text-2xl font-bold text-amber-500 tabular-nums">
            {{ sales()?.pendingOrders ?? 0 }}
          </p>
        </article>
        <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-5">
          <p class="mb-2 text-sm text-rose-500">Cancelled</p>
          <p class="text-2xl font-bold text-rose-500 tabular-nums">
            {{ sales()?.cancelledOrders ?? 0 }}
          </p>
        </article>
      </div>

      <!-- Filter pills -->
      <div class="flex items-center gap-3">
        <div
          class="flex flex-wrap gap-1 rounded-lg border border-(--color-border) bg-(--color-surface) p-1"
          role="tablist"
          aria-label="Status filter"
        >
          @for (f of statusFilters; track f.key) {
            <button
              type="button"
              role="tab"
              [attr.aria-selected]="statusFilter() === f.key"
              (click)="setStatusFilter(f.key)"
              class="rounded-md px-3 py-1.5 text-xs font-medium transition-colors"
              [class]="
                statusFilter() === f.key
                  ? 'bg-(--color-primary) text-white'
                  : 'text-(--color-text-secondary) hover:bg-(--color-surface-hover)'
              "
            >
              {{ f.label }}
            </button>
          }
        </div>
        <span class="text-xs text-(--color-text-muted)">
          {{ filteredOrders().length }} orders
        </span>
      </div>

      <!-- Body: table + optional detail -->
      <div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div
          class="overflow-hidden rounded-xl border border-(--color-border) bg-(--color-surface)"
          [class.lg:col-span-2]="selectedId() !== null"
          [class.lg:col-span-3]="selectedId() === null"
        >
          @if (isLoading()) {
            <p class="p-12 text-center text-sm text-(--color-text-muted)">Loading orders…</p>
          } @else if (error(); as err) {
            <div class="p-6 text-rose-300" role="alert">
              <h2 class="font-semibold">Failed to load orders</h2>
              <p class="mt-1 text-sm">{{ ordersErrorMessage() }}</p>
            </div>
          } @else if (filteredOrders().length === 0) {
            <p class="p-12 text-center text-sm text-(--color-text-muted)">
              No orders found for this filter.
            </p>
          } @else {
            <table class="w-full text-sm">
              <thead class="border-b border-(--color-border) bg-(--color-bg)">
                <tr>
                  <th class="px-4 py-3 text-left font-medium text-(--color-text-secondary)">
                    Order ID
                  </th>
                  <th class="px-4 py-3 text-left font-medium text-(--color-text-secondary)">
                    Customer
                  </th>
                  <th class="px-4 py-3 text-left font-medium text-(--color-text-secondary)">
                    Type
                  </th>
                  <th class="px-4 py-3 text-center font-medium text-(--color-text-secondary)">
                    Status
                  </th>
                  <th class="px-4 py-3 text-right font-medium text-(--color-text-secondary)">
                    Total
                  </th>
                  <th class="px-4 py-3 text-right font-medium text-(--color-text-secondary)">
                    Date
                  </th>
                </tr>
              </thead>
              <tbody class="divide-y divide-(--color-border)">
                @for (order of filteredOrders(); track order.orderId) {
                  <tr
                    class="cursor-pointer transition-colors"
                    [class]="
                      selectedId() === order.orderId
                        ? 'bg-(--color-primary)/10'
                        : 'hover:bg-(--color-surface-hover)'
                    "
                    (click)="onSelect(order.orderId)"
                    [attr.aria-label]="'Order ' + truncateId(order.orderId)"
                  >
                    <td class="px-4 py-3 font-mono text-xs font-medium text-(--color-text)">
                      #{{ truncateId(order.orderId) }}
                    </td>
                    <td class="px-4 py-3 text-xs text-(--color-text-secondary)">
                      {{ formatCustomer(order) }}
                    </td>
                    <td class="px-4 py-3 text-xs capitalize text-(--color-text-secondary)">
                      {{ order.orderType }}
                    </td>
                    <td class="px-4 py-3 text-center">
                      <span
                        class="rounded-full px-2 py-0.5 text-[10px] font-medium capitalize"
                        [class]="statusBadgeClass(order.orderStatus)"
                      >
                        {{ formatStatus(order.orderStatus) }}
                      </span>
                    </td>
                    <td class="px-4 py-3 text-right font-semibold tabular-nums text-(--color-text)">
                      {{ formatMoney(order.total) }}
                    </td>
                    <td class="px-4 py-3 text-right text-xs text-(--color-text-secondary)">
                      {{ formatDate(order.createdAt) }}
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          }
        </div>

        @if (selectedId(); as orderId) {
          <aside
            class="space-y-5 rounded-xl border border-(--color-border) bg-(--color-surface) p-5"
          >
            <header class="flex items-center justify-between">
              <h3 class="font-semibold text-(--color-text)">Order details</h3>
              <button
                type="button"
                (click)="onSelect(null)"
                class="text-(--color-text-muted) hover:text-(--color-text)"
                aria-label="Close detail panel"
              >
                ✕
              </button>
            </header>

            @if (detailLoading()) {
              <p class="py-8 text-center text-sm text-(--color-text-muted)">Loading…</p>
            } @else if (selectedOrder(); as detail) {
              <dl class="space-y-3">
                <div class="flex justify-between text-sm">
                  <dt class="text-(--color-text-secondary)">Order ID</dt>
                  <dd class="font-mono text-xs font-medium text-(--color-text)">
                    {{ truncateId(detail.orderId, 12) }}
                  </dd>
                </div>
                <div class="flex justify-between text-sm">
                  <dt class="text-(--color-text-secondary)">Status</dt>
                  <dd>
                    <span
                      class="rounded-full px-2 py-0.5 text-xs font-medium capitalize"
                      [class]="statusBadgeClass(detail.orderStatus)"
                    >
                      {{ formatStatus(detail.orderStatus) }}
                    </span>
                  </dd>
                </div>
                <div class="flex justify-between text-sm">
                  <dt class="text-(--color-text-secondary)">Type</dt>
                  <dd class="capitalize text-(--color-text)">{{ detail.orderType }}</dd>
                </div>
                <div class="flex justify-between text-sm">
                  <dt class="text-(--color-text-secondary)">Payment</dt>
                  <dd class="capitalize text-(--color-text)">
                    {{ detail.paymentMethod ?? 'N/A' }}
                  </dd>
                </div>
                <div class="flex justify-between text-sm">
                  <dt class="text-(--color-text-secondary)">Created</dt>
                  <dd class="text-(--color-text)">{{ formatDateTime(detail.createdAt) }}</dd>
                </div>

                <div class="space-y-2 border-t border-(--color-border) pt-3">
                  <div class="flex justify-between text-sm">
                    <dt class="text-(--color-text-secondary)">Subtotal</dt>
                    <dd class="tabular-nums text-(--color-text)">
                      {{ formatMoney(detail.subtotal) }}
                    </dd>
                  </div>
                  @if (detail.discountTotal > 0) {
                    <div class="flex justify-between text-sm">
                      <dt class="text-(--color-text-secondary)">Discount</dt>
                      <dd class="tabular-nums text-emerald-500">
                        -{{ formatMoney(detail.discountTotal) }}
                      </dd>
                    </div>
                  }
                  <div class="flex justify-between text-sm">
                    <dt class="text-(--color-text-secondary)">Tax</dt>
                    <dd class="tabular-nums text-(--color-text)">
                      {{ formatMoney(detail.taxTotal) }}
                    </dd>
                  </div>
                  <div class="flex justify-between text-sm font-bold">
                    <dt class="text-(--color-text)">Total</dt>
                    <dd class="tabular-nums text-(--color-text)">
                      {{ formatMoney(detail.total) }}
                    </dd>
                  </div>
                </div>

                @if (detail.metrcSyncStatus) {
                  <div class="border-t border-(--color-border) pt-3">
                    <div class="flex justify-between text-sm">
                      <dt class="text-(--color-text-secondary)">Metrc sync</dt>
                      <dd>
                        <span
                          class="rounded-full px-2 py-0.5 text-xs font-medium"
                          [class]="metrcBadgeClass(detail.metrcSyncStatus)"
                        >
                          {{ detail.metrcSyncStatus }}
                        </span>
                      </dd>
                    </div>
                    @if (detail.metrcReceiptId) {
                      <div class="mt-2 flex justify-between text-sm">
                        <dt class="text-(--color-text-secondary)">Receipt ID</dt>
                        <dd class="font-mono text-xs text-(--color-text)">
                          {{ detail.metrcReceiptId }}
                        </dd>
                      </div>
                    }
                  </div>
                }

                @if (detail.notes) {
                  <div class="border-t border-(--color-border) pt-3">
                    <p class="mb-1 text-xs text-(--color-text-secondary)">Notes</p>
                    <p class="text-sm text-(--color-text)">{{ detail.notes }}</p>
                  </div>
                }

                @if (detail.cancellationReason) {
                  <div class="border-t border-(--color-border) pt-3">
                    <p class="mb-1 text-xs text-rose-500">Cancellation reason</p>
                    <p class="text-sm text-rose-400">{{ detail.cancellationReason }}</p>
                  </div>
                }
              </dl>

              @if (canCancel(detail.orderStatus)) {
                <div class="border-t border-(--color-border) pt-3">
                  @if (showCancelDialog()) {
                    <div class="space-y-2">
                      <input
                        type="text"
                        [value]="cancelReason()"
                        (input)="onCancelReasonInput($event)"
                        placeholder="Cancellation reason…"
                        aria-label="Cancellation reason"
                        class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-rose-500 focus:outline-none"
                      />
                      <div class="flex gap-2">
                        <button
                          type="button"
                          (click)="onConfirmCancel(detail.orderId)"
                          [disabled]="!cancelReason().trim() || cancelling()"
                          class="flex-1 rounded-lg bg-rose-600 px-3 py-2 text-xs font-medium text-white hover:bg-rose-500 disabled:opacity-50"
                        >
                          @if (cancelling()) {
                            Cancelling…
                          } @else {
                            Confirm cancel
                          }
                        </button>
                        <button
                          type="button"
                          (click)="closeCancelDialog()"
                          class="rounded-lg border border-(--color-border) px-3 py-2 text-xs text-(--color-text-secondary) hover:text-(--color-text)"
                        >
                          Back
                        </button>
                      </div>
                    </div>
                  } @else {
                    <button
                      type="button"
                      (click)="openCancelDialog()"
                      class="w-full rounded-lg border border-rose-500/30 px-3 py-2 text-xs font-medium text-rose-500 hover:bg-rose-500/10"
                    >
                      Cancel order
                    </button>
                  }
                </div>
              }
            } @else {
              <p class="py-8 text-center text-sm text-(--color-text-muted)">Order not found</p>
            }
          </aside>
        }
      </div>
    </section>
  `,
})
export class OrdersPage {
  private readonly svc = inject(OrdersService);
  private readonly dashboard = inject(DashboardService);

  protected readonly statusFilters = STATUS_FILTERS;
  protected readonly statusFilter = this.svc.statusFilter;
  protected readonly filteredOrders = this.svc.filteredOrders;
  protected readonly isLoading = this.svc.isLoading;
  protected readonly error = this.svc.error;
  protected readonly selectedId = this.svc.selectedId;
  protected readonly selectedOrder = this.svc.selectedOrder;
  protected readonly detailLoading = this.svc.detailLoading;
  protected readonly cancelling = this.svc.cancelling;

  protected readonly sales = computed(() => this.dashboard.data()?.sales ?? null);

  protected readonly showCancelDialog = signal(false);
  protected readonly cancelReason = signal('');

  protected readonly ordersErrorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load orders.';
  });

  protected setStatusFilter(status: OrderStatusFilter): void {
    this.svc.setStatusFilter(status);
  }

  protected onSelect(orderId: string | null): void {
    this.svc.select(orderId);
    this.closeCancelDialog();
  }

  protected openCancelDialog(): void {
    this.showCancelDialog.set(true);
  }

  protected closeCancelDialog(): void {
    this.showCancelDialog.set(false);
    this.cancelReason.set('');
  }

  protected onCancelReasonInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.cancelReason.set(value);
  }

  protected async onConfirmCancel(orderId: string): Promise<void> {
    const reason = this.cancelReason().trim();
    if (!reason) return;
    await this.svc.cancel(orderId, reason);
    this.closeCancelDialog();
  }

  protected canCancel(status: string): boolean {
    return !TERMINAL_STATUSES.has(status);
  }

  protected truncateId(orderId: string, length = 8): string {
    return orderId.slice(0, length).toUpperCase();
  }

  protected formatCustomer(order: OrderListItem): string {
    if (!order.customerUserId) return 'Walk-in';
    return order.customerUserId.slice(0, 8) + '…';
  }

  protected formatStatus(status: string): string {
    return status.replace(/_/g, ' ');
  }

  protected formatMoney(value: number): string {
    return (
      '$' +
      value.toLocaleString('en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })
    );
  }

  protected formatDate(value: string | null | undefined): string {
    if (!value) return '—';
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return '—';
    return d.toLocaleDateString();
  }

  protected formatDateTime(value: string | null | undefined): string {
    if (!value) return '—';
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return '—';
    return d.toLocaleString();
  }

  protected statusBadgeClass(status: string): string {
    switch (status) {
      case 'completed':
      case 'delivered':
      case 'picked_up':
        return 'bg-emerald-500/10 text-emerald-500';
      case 'confirmed':
      case 'preparing':
      case 'ready_for_pickup':
        return 'bg-sky-500/10 text-sky-500';
      case 'pending':
        return 'bg-amber-500/10 text-amber-500';
      case 'cancelled':
        return 'bg-rose-500/10 text-rose-500';
      default:
        return 'bg-(--color-surface-hover) text-(--color-text-secondary)';
    }
  }

  protected metrcBadgeClass(status: string): string {
    if (status === 'synced') return 'bg-emerald-500/10 text-emerald-500';
    if (status === 'failed') return 'bg-rose-500/10 text-rose-500';
    return 'bg-amber-500/10 text-amber-500';
  }
}

// apps/admin/src/pages/OrdersPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { useDashboard } from '../hooks/useDashboard';
import { ShoppingCart, Clock, CheckCircle, XCircle, Search, Eye, X, ChevronLeft, Ban } from 'lucide-react';

const ORDERS_QUERY = `
  query($dispensaryId: ID!, $limit: Int, $offset: Int) {
    orders(dispensaryId: $dispensaryId, limit: $limit, offset: $offset) {
      orderId dispensaryId customerUserId orderType orderStatus
      subtotal taxTotal total paymentMethod createdAt updatedAt
    }
  }
`;

const ORDER_DETAIL_QUERY = `
  query($orderId: ID!, $dispensaryId: ID) {
    order(orderId: $orderId, dispensaryId: $dispensaryId) {
      orderId dispensaryId customerUserId orderType orderStatus
      subtotal discountTotal taxTotal total paymentMethod
      metrcReceiptId metrcSyncStatus notes cancellationReason
      createdAt updatedAt
    }
  }
`;

const CANCEL_ORDER = `
  mutation($orderId: ID!, $reason: String!, $dispensaryId: ID) {
    cancelOrder(orderId: $orderId, reason: $reason, dispensaryId: $dispensaryId)
  }
`;

const STATUS_OPTIONS = ['all', 'pending', 'confirmed', 'preparing', 'ready_for_pickup', 'completed', 'cancelled'] as const;

const statusBadge = (status: string) => {
  switch (status) {
    case 'completed': case 'delivered': case 'picked_up':
      return 'bg-green-50 text-green-700';
    case 'confirmed': case 'preparing': case 'ready_for_pickup':
      return 'bg-blue-50 text-blue-700';
    case 'pending':
      return 'bg-amber-50 text-amber-700';
    case 'cancelled':
      return 'bg-red-50 text-red-700';
    default:
      return 'bg-gray-100 text-gray-600';
  }
};

export function OrdersPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const queryClient = useQueryClient();
  const { data: dashData, isLoading: dashLoading } = useDashboard(30);
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null);
  const [cancelReason, setCancelReason] = useState('');
  const [showCancelDialog, setShowCancelDialog] = useState(false);

  const sales = dashData?.sales;

  const { data: ordersData, isLoading: ordersLoading } = useQuery({
    queryKey: ['ordersList', dispensaryId],
    queryFn: () => gqlRequest<{ orders: any[] }>(ORDERS_QUERY, { dispensaryId, limit: 100, offset: 0 }),
    enabled: !!dispensaryId,
  });

  const { data: orderDetail, isLoading: detailLoading } = useQuery({
    queryKey: ['orderDetail', selectedOrderId],
    queryFn: () => gqlRequest<{ order: any }>(ORDER_DETAIL_QUERY, { orderId: selectedOrderId, dispensaryId }),
    enabled: !!selectedOrderId,
  });

  const cancelMutation = useMutation({
    mutationFn: (vars: { orderId: string; reason: string }) =>
      gqlRequest(CANCEL_ORDER, { ...vars, dispensaryId }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ordersList'] });
      queryClient.invalidateQueries({ queryKey: ['orderDetail'] });
      queryClient.invalidateQueries({ queryKey: ['dashboard'] });
      setShowCancelDialog(false);
      setCancelReason('');
    },
  });

  const allOrders = ordersData?.orders ?? [];
  const filtered = statusFilter === 'all'
    ? allOrders
    : allOrders.filter((o: any) => o.orderStatus === statusFilter);

  const detail = orderDetail?.order;

  if (dashLoading) return <div className="text-txt-muted">Loading...</div>;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-txt">Orders</h1>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-surface rounded-xl border border-border p-5">
          <div className="flex items-center gap-2 text-txt-secondary text-sm mb-2"><ShoppingCart size={16} /> Total</div>
          <p className="text-2xl font-bold">{sales?.totalOrders ?? 0}</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-5">
          <div className="flex items-center gap-2 text-green-600 text-sm mb-2"><CheckCircle size={16} /> Completed</div>
          <p className="text-2xl font-bold text-green-600">{sales?.completedOrders ?? 0}</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-5">
          <div className="flex items-center gap-2 text-amber-600 text-sm mb-2"><Clock size={16} /> Pending</div>
          <p className="text-2xl font-bold text-amber-600">{sales?.pendingOrders ?? 0}</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-5">
          <div className="flex items-center gap-2 text-red-600 text-sm mb-2"><XCircle size={16} /> Cancelled</div>
          <p className="text-2xl font-bold text-red-600">{sales?.cancelledOrders ?? 0}</p>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="flex items-center gap-3">
        <div className="flex gap-1 bg-surface border border-border rounded-lg p-1">
          {STATUS_OPTIONS.map((s) => (
            <button
              key={s}
              onClick={() => setStatusFilter(s)}
              className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors capitalize ${
                statusFilter === s
                  ? 'bg-brand-600 text-white'
                  : 'text-txt-secondary hover:bg-bg-alt'
              }`}
            >
              {s === 'all' ? 'All' : s.replace(/_/g, ' ')}
            </button>
          ))}
        </div>
        <span className="text-xs text-txt-muted">{filtered.length} orders</span>
      </div>

      {/* Two-panel layout: Table + Detail */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Orders Table */}
        <div className={`${selectedOrderId ? 'lg:col-span-2' : 'lg:col-span-3'} bg-surface rounded-xl border border-border overflow-hidden`}>
          {ordersLoading ? (
            <div className="p-12 text-center text-txt-muted">Loading orders...</div>
          ) : filtered.length === 0 ? (
            <div className="p-12 text-center text-txt-muted">No orders found for this filter.</div>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-bg-alt border-b border-border">
                <tr>
                  <th className="text-left px-4 py-3 font-medium text-txt-secondary">Order ID</th>
                  <th className="text-left px-4 py-3 font-medium text-txt-secondary">Customer</th>
                  <th className="text-left px-4 py-3 font-medium text-txt-secondary">Type</th>
                  <th className="text-center px-4 py-3 font-medium text-txt-secondary">Status</th>
                  <th className="text-right px-4 py-3 font-medium text-txt-secondary">Total</th>
                  <th className="text-right px-4 py-3 font-medium text-txt-secondary">Date</th>
                  <th className="text-center px-4 py-3 font-medium text-txt-secondary">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {filtered.map((order: any) => (
                  <tr
                    key={order.orderId}
                    className={`transition-colors cursor-pointer ${
                      selectedOrderId === order.orderId
                        ? 'bg-brand-50'
                        : 'hover:bg-bg-alt'
                    }`}
                    onClick={() => setSelectedOrderId(order.orderId)}
                  >
                    <td className="px-4 py-3 font-mono text-xs font-medium text-txt">
                      #{order.orderId.slice(0, 8).toUpperCase()}
                    </td>
                    <td className="px-4 py-3 text-txt-secondary text-xs">
                      {order.customerUserId ? order.customerUserId.slice(0, 8) + '...' : 'Walk-in'}
                    </td>
                    <td className="px-4 py-3 text-txt-secondary capitalize text-xs">
                      {order.orderType}
                    </td>
                    <td className="px-4 py-3 text-center">
                      <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium capitalize ${statusBadge(order.orderStatus)}`}>
                        {order.orderStatus.replace(/_/g, ' ')}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right tabular-nums font-semibold text-txt">
                      ${parseFloat(order.total).toFixed(2)}
                    </td>
                    <td className="px-4 py-3 text-right text-xs text-txt-secondary">
                      {new Date(order.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-4 py-3 text-center">
                      <button
                        onClick={(e) => { e.stopPropagation(); setSelectedOrderId(order.orderId); }}
                        className="text-brand-600 hover:text-brand-700"
                      >
                        <Eye size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {/* Order Detail Panel */}
        {selectedOrderId && (
          <div className="bg-surface rounded-xl border border-border p-5 space-y-5">
            <div className="flex items-center justify-between">
              <h3 className="font-semibold text-txt">Order Details</h3>
              <button onClick={() => setSelectedOrderId(null)} className="text-txt-muted hover:text-txt">
                <X size={18} />
              </button>
            </div>

            {detailLoading ? (
              <div className="text-sm text-txt-muted py-8 text-center">Loading...</div>
            ) : detail ? (
              <>
                <div className="space-y-3">
                  <div className="flex justify-between text-sm">
                    <span className="text-txt-secondary">Order ID</span>
                    <span className="font-mono text-xs font-medium">{detail.orderId.slice(0, 12).toUpperCase()}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-txt-secondary">Status</span>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium capitalize ${statusBadge(detail.orderStatus)}`}>
                      {detail.orderStatus.replace(/_/g, ' ')}
                    </span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-txt-secondary">Type</span>
                    <span className="capitalize">{detail.orderType}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-txt-secondary">Payment</span>
                    <span className="capitalize">{detail.paymentMethod ?? 'N/A'}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-txt-secondary">Created</span>
                    <span>{new Date(detail.createdAt).toLocaleString()}</span>
                  </div>

                  <div className="border-t border-border pt-3 space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-txt-secondary">Subtotal</span>
                      <span className="tabular-nums">${parseFloat(detail.subtotal).toFixed(2)}</span>
                    </div>
                    {parseFloat(detail.discountTotal) > 0 && (
                      <div className="flex justify-between text-sm">
                        <span className="text-txt-secondary">Discount</span>
                        <span className="tabular-nums text-green-600">-${parseFloat(detail.discountTotal).toFixed(2)}</span>
                      </div>
                    )}
                    <div className="flex justify-between text-sm">
                      <span className="text-txt-secondary">Tax</span>
                      <span className="tabular-nums">${parseFloat(detail.taxTotal).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between text-sm font-bold">
                      <span>Total</span>
                      <span className="tabular-nums">${parseFloat(detail.total).toFixed(2)}</span>
                    </div>
                  </div>

                  {detail.metrcSyncStatus && (
                    <div className="border-t border-border pt-3">
                      <div className="flex justify-between text-sm">
                        <span className="text-txt-secondary">Metrc Sync</span>
                        <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                          detail.metrcSyncStatus === 'synced' ? 'bg-green-50 text-green-700' :
                          detail.metrcSyncStatus === 'failed' ? 'bg-red-50 text-red-700' :
                          'bg-amber-50 text-amber-700'
                        }`}>{detail.metrcSyncStatus}</span>
                      </div>
                      {detail.metrcReceiptId && (
                        <div className="flex justify-between text-sm mt-2">
                          <span className="text-txt-secondary">Receipt ID</span>
                          <span className="font-mono text-xs">{detail.metrcReceiptId}</span>
                        </div>
                      )}
                    </div>
                  )}

                  {detail.notes && (
                    <div className="border-t border-border pt-3">
                      <p className="text-xs text-txt-secondary mb-1">Notes</p>
                      <p className="text-sm text-txt">{detail.notes}</p>
                    </div>
                  )}

                  {detail.cancellationReason && (
                    <div className="border-t border-border pt-3">
                      <p className="text-xs text-red-600 mb-1">Cancellation Reason</p>
                      <p className="text-sm text-red-700">{detail.cancellationReason}</p>
                    </div>
                  )}
                </div>

                {/* Cancel button for non-terminal orders */}
                {!['completed', 'cancelled', 'picked_up', 'delivered'].includes(detail.orderStatus) && (
                  <div className="pt-3 border-t border-border">
                    {showCancelDialog ? (
                      <div className="space-y-2">
                        <input
                          type="text"
                          value={cancelReason}
                          onChange={(e) => setCancelReason(e.target.value)}
                          placeholder="Cancellation reason..."
                          className="w-full px-3 py-2 border border-border rounded-lg text-sm focus:border-red-400 focus:ring-1 focus:ring-red-400 outline-none"
                        />
                        <div className="flex gap-2">
                          <button
                            onClick={() => cancelMutation.mutate({ orderId: detail.orderId, reason: cancelReason })}
                            disabled={!cancelReason.trim() || cancelMutation.isPending}
                            className="flex-1 flex items-center justify-center gap-1.5 bg-red-600 text-white px-3 py-2 rounded-lg text-xs font-medium hover:bg-red-700 disabled:opacity-50"
                          >
                            <Ban size={14} /> Confirm Cancel
                          </button>
                          <button
                            onClick={() => { setShowCancelDialog(false); setCancelReason(''); }}
                            className="px-3 py-2 text-xs text-txt-secondary hover:text-txt border border-border rounded-lg"
                          >
                            Back
                          </button>
                        </div>
                      </div>
                    ) : (
                      <button
                        onClick={() => setShowCancelDialog(true)}
                        className="w-full flex items-center justify-center gap-1.5 text-red-600 border border-red-200 hover:bg-red-50 px-3 py-2 rounded-lg text-xs font-medium transition-colors"
                      >
                        <XCircle size={14} /> Cancel Order
                      </button>
                    )}
                  </div>
                )}
              </>
            ) : (
              <div className="text-sm text-txt-muted py-8 text-center">Order not found</div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
