// packages/angular/projects/admin/src/app/pages/staffing/staffing-page.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';

import { StaffingService, type Employee } from './staffing.service';

const HOURS_PER_WEEK = 40;

/**
 * Read-only staff roster + compliance KPIs. Mirrors React parity:
 * 5 KPI cards (active staff, active certs, expiring soon, expired,
 * estimated weekly payroll) + a roster table.
 *
 * Filed scope listed add-employee modal, inline role changes, and
 * activate/deactivate toggles — none of which exist in the React
 * admin. File a follow-up if/when invite/role mutations become an
 * admin workflow need.
 */
@Component({
  selector: 'cs-staffing-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="space-y-6">
      <h1 class="text-2xl font-bold text-(--color-text)">Staffing</h1>

      @if (loading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading staff…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load staffing</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else {
        <!-- KPIs -->
        <div class="grid grid-cols-2 gap-3 md:grid-cols-5">
          <article
            class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
          >
            <p class="text-2xl font-bold text-(--color-text) tabular-nums">
              {{ compliance()?.activeEmployees ?? 0 }}
            </p>
            <p class="text-xs text-(--color-text-secondary)">Active staff</p>
          </article>
          <article
            class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
          >
            <p class="text-2xl font-bold text-emerald-500 tabular-nums">
              {{ compliance()?.activeCerts ?? 0 }}
            </p>
            <p class="text-xs text-(--color-text-secondary)">Active certs</p>
          </article>
          <article
            class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
          >
            <p class="text-2xl font-bold text-amber-500 tabular-nums">
              {{ compliance()?.expiringSoon ?? 0 }}
            </p>
            <p class="text-xs text-(--color-text-secondary)">Expiring soon</p>
          </article>
          <article
            class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
          >
            <p class="text-2xl font-bold text-rose-500 tabular-nums">
              {{ compliance()?.expiredCerts ?? 0 }}
            </p>
            <p class="text-xs text-(--color-text-secondary)">Expired</p>
          </article>
          <article
            class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
          >
            <p class="text-2xl font-bold text-(--color-text) tabular-nums">
              {{ estimatedWeeklyPayrollLabel() }}
            </p>
            <p class="text-xs text-(--color-text-secondary)">Est. weekly payroll</p>
          </article>
        </div>

        <!-- Roster -->
        <div class="overflow-hidden rounded-xl border border-(--color-border) bg-(--color-surface)">
          <header class="border-b border-(--color-border) px-6 py-4">
            <h2 class="text-lg font-semibold text-(--color-text)">Employee roster</h2>
          </header>
          @if (employees().length === 0) {
            <p class="p-12 text-center text-sm text-(--color-text-muted)">No employees found.</p>
          } @else {
            <table class="w-full text-sm">
              <thead class="border-b border-(--color-border) bg-(--color-bg)">
                <tr>
                  <th class="px-4 py-2 text-left font-medium text-(--color-text-secondary)">
                    Employee
                  </th>
                  <th class="px-4 py-2 text-left font-medium text-(--color-text-secondary)">
                    Position
                  </th>
                  <th class="px-4 py-2 text-left font-medium text-(--color-text-secondary)">
                    Type
                  </th>
                  <th class="px-4 py-2 text-right font-medium text-(--color-text-secondary)">
                    Rate
                  </th>
                  <th class="px-4 py-2 text-center font-medium text-(--color-text-secondary)">
                    Certs
                  </th>
                  <th class="px-4 py-2 text-center font-medium text-(--color-text-secondary)">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody class="divide-y divide-(--color-border)">
                @for (e of employees(); track e.profileId) {
                  <tr class="hover:bg-(--color-surface-hover)">
                    <td class="px-4 py-3">
                      <p class="font-medium text-(--color-text)">
                        {{ formatName(e) }}
                      </p>
                      <p class="text-xs text-(--color-text-muted)">
                        @if (e.employeeNumber) {
                          {{ e.employeeNumber }} ·
                        }
                        {{ e.email }}
                      </p>
                    </td>
                    <td class="px-4 py-3 text-(--color-text-secondary)">
                      {{ e.positionName ?? '—' }}
                    </td>
                    <td class="px-4 py-3">
                      <span
                        class="rounded-full px-2 py-0.5 text-xs"
                        [class]="employmentTypeClass(e.employmentType)"
                      >
                        {{ employmentTypeLabel(e.employmentType) }}
                      </span>
                    </td>
                    <td class="px-4 py-3 text-right font-medium tabular-nums text-(--color-text)">
                      {{ formatRate(e.hourlyRate) }}
                    </td>
                    <td class="px-4 py-3 text-center">
                      <span class="font-medium text-emerald-500 tabular-nums">
                        {{ e.activeCerts }}
                      </span>
                      @if (e.expiringCerts > 0) {
                        <span class="ml-1 text-amber-500">({{ e.expiringCerts }}⚠)</span>
                      }
                    </td>
                    <td class="px-4 py-3 text-center">
                      <span
                        class="rounded-full px-2 py-0.5 text-xs"
                        [class]="statusBadgeClass(e.employmentStatus)"
                      >
                        {{ e.employmentStatus }}
                      </span>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          }
        </div>
      }
    </section>
  `,
})
export class StaffingPage {
  private readonly svc = inject(StaffingService);

  protected readonly employees = this.svc.employees;
  protected readonly compliance = this.svc.compliance;
  protected readonly loading = this.svc.isLoading;
  protected readonly error = this.svc.error;

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load staffing.';
  });

  protected readonly estimatedWeeklyPayrollLabel = computed(() => {
    const total = this.employees()
      .filter((e) => e.employmentStatus === 'active')
      .reduce((sum, e) => sum + (e.hourlyRate ?? 0) * HOURS_PER_WEEK, 0);
    return (
      '$' +
      total.toLocaleString('en-US', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      })
    );
  });

  protected formatName(e: Employee): string {
    const first = e.firstName ?? '';
    const last = e.lastName ?? '';
    const name = (first + ' ' + last).trim();
    return name || e.email;
  }

  protected formatRate(rate: number | null | undefined): string {
    if (rate == null) return '—';
    return '$' + rate.toFixed(2) + '/hr';
  }

  protected employmentTypeLabel(type: string): string {
    if (type === 'full_time') return 'Full-time';
    if (type === 'part_time') return 'Part-time';
    return type.replace(/_/g, ' ');
  }

  protected employmentTypeClass(type: string): string {
    return type === 'full_time'
      ? 'bg-sky-500/10 text-sky-500'
      : 'bg-(--color-surface-hover) text-(--color-text-secondary)';
  }

  protected statusBadgeClass(status: string): string {
    return status === 'active'
      ? 'bg-emerald-500/10 text-emerald-500'
      : 'bg-rose-500/10 text-rose-500';
  }
}

// apps/admin/src/pages/StaffingPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { Users, Award, AlertTriangle, ChevronDown, ChevronUp, Shield } from 'lucide-react';

const EMPLOYEES_QUERY = `query($id: ID!) { employees(dispensaryId: $id) {
  profileId firstName lastName email positionName department employeeNumber hourlyRate
  employmentType employmentStatus payType activeCerts expiringCerts
}}`;

const COMPLIANCE_QUERY = `query($id: ID!) { staffComplianceOverview(dispensaryId: $id) {
  totalEmployees activeEmployees totalCerts activeCerts expiredCerts expiringSoon pendingCerts
}}`;

const EXPIRING_QUERY = `query($id: ID!, $days: Int!) { expiringCertifications(dispensaryId: $id, daysAhead: $days) {
  certificationId status expirationDate
}}`;

export function StaffingPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const { data: employees, isLoading } = useQuery({
    queryKey: ['employees', dispensaryId],
    queryFn: () => gqlRequest<any>(EMPLOYEES_QUERY, { id: dispensaryId }),
    select: (d) => d.employees,
    enabled: !!dispensaryId,
  });

  const { data: compliance } = useQuery({
    queryKey: ['staffCompliance', dispensaryId],
    queryFn: () => gqlRequest<any>(COMPLIANCE_QUERY, { id: dispensaryId }),
    select: (d) => d.staffComplianceOverview,
    enabled: !!dispensaryId,
  });

  if (isLoading) return <div className="text-txt-muted p-8">Loading staff...</div>;

  const active = employees?.filter((e: any) => e.employmentStatus === 'active') ?? [];
  const totalPayroll = active.reduce((s: number, e: any) => s + (e.hourlyRate ?? 0) * 40, 0);

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-txt">Staffing</h1>

      {/* KPIs */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div className="bg-surface rounded-xl border border-border p-4 text-center">
          <Users size={18} className="mx-auto text-brand-600 mb-1" />
          <p className="text-2xl font-bold">{compliance?.activeEmployees ?? 0}</p>
          <p className="text-xs text-txt-secondary">Active Staff</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-4 text-center">
          <Award size={18} className="mx-auto text-green-600 mb-1" />
          <p className="text-2xl font-bold">{compliance?.activeCerts ?? 0}</p>
          <p className="text-xs text-txt-secondary">Active Certs</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-4 text-center">
          <AlertTriangle size={18} className="mx-auto text-amber-500 mb-1" />
          <p className="text-2xl font-bold text-amber-600">{compliance?.expiringSoon ?? 0}</p>
          <p className="text-xs text-txt-secondary">Expiring Soon</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-4 text-center">
          <Shield size={18} className="mx-auto text-red-500 mb-1" />
          <p className="text-2xl font-bold text-red-600">{compliance?.expiredCerts ?? 0}</p>
          <p className="text-xs text-txt-secondary">Expired</p>
        </div>
        <div className="bg-surface rounded-xl border border-border p-4 text-center">
          <p className="text-2xl font-bold">${totalPayroll.toLocaleString()}</p>
          <p className="text-xs text-txt-secondary">Est. Weekly Payroll</p>
        </div>
      </div>

      {/* Employee Roster */}
      <div className="bg-surface rounded-xl border border-border overflow-hidden">
        <div className="px-6 py-4 border-b border-border">
          <h2 className="text-lg font-semibold text-txt">Employee Roster</h2>
        </div>
        <table className="w-full text-sm">
          <thead className="bg-bg-alt border-b border-border">
            <tr>
              <th className="text-left px-4 py-2 font-medium text-txt-secondary">Employee</th>
              <th className="text-left px-4 py-2 font-medium text-txt-secondary">Position</th>
              <th className="text-left px-4 py-2 font-medium text-txt-secondary">Type</th>
              <th className="text-right px-4 py-2 font-medium text-txt-secondary">Rate</th>
              <th className="text-center px-4 py-2 font-medium text-txt-secondary">Certs</th>
              <th className="text-center px-4 py-2 font-medium text-txt-secondary">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {(employees ?? []).map((emp: any) => (
              <tr key={emp.profileId}
                className="hover:bg-bg-alt cursor-pointer transition-colors"
                onClick={() => setExpandedId(expandedId === emp.profileId ? null : emp.profileId)}
              >
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    {expandedId === emp.profileId ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                    <div>
                      <p className="font-medium text-txt">{emp.firstName} {emp.lastName}</p>
                      <p className="text-xs text-txt-muted">{emp.employeeNumber} · {emp.email}</p>
                    </div>
                  </div>
                </td>
                <td className="px-4 py-3 text-gray-600">{emp.positionName}</td>
                <td className="px-4 py-3">
                  <span className={`text-xs px-2 py-0.5 rounded-full ${emp.employmentType === 'full_time' ? 'bg-blue-50 text-blue-700' : 'bg-gray-100 text-gray-600'}`}>
                    {emp.employmentType === 'full_time' ? 'Full-time' : 'Part-time'}
                  </span>
                </td>
                <td className="px-4 py-3 text-right tabular-nums font-medium">${emp.hourlyRate?.toFixed(2) ?? '-'}/hr</td>
                <td className="px-4 py-3 text-center">
                  <span className="text-green-600 font-medium">{emp.activeCerts}</span>
                  {emp.expiringCerts > 0 && <span className="text-amber-500 ml-1">({emp.expiringCerts}⚠)</span>}
                </td>
                <td className="px-4 py-3 text-center">
                  <span className={`text-xs px-2 py-0.5 rounded-full ${emp.employmentStatus === 'active' ? 'bg-green-50 text-green-700' : 'bg-danger-bg text-danger'}`}>
                    {emp.employmentStatus}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
