// packages/angular/projects/admin/src/app/pages/tax-management/tax-management-page.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { TaxRulesService, type TaxRule } from './tax-rules.service';

const TAX_BASIS_OPTIONS = [
  { value: 'retail_price', label: 'Retail price (%)' },
  { value: 'per_mg_thc', label: 'Per mg THC ($)' },
  { value: 'wholesale_price', label: 'Wholesale price (%)' },
];

interface AddFormControls {
  readonly state: FormControl<string>;
  readonly code: FormControl<string>;
  readonly name: FormControl<string>;
  readonly rate: FormControl<string>;
  readonly taxBasis: FormControl<string>;
  readonly statutoryReference: FormControl<string>;
}

interface EditFormControls {
  readonly name: FormControl<string>;
  readonly rate: FormControl<string>;
}

interface RuleGroup {
  readonly state: string;
  readonly rules: readonly TaxRule[];
  readonly combinedPercentLabel: string;
}

/**
 * Super_admin-only Tax Management. Lists all platform tax rules
 * grouped by state, allows adding a new rule (state / code / name /
 * rate / basis / optional statutory reference), inline-edit of name
 * + rate, and toggling `is_active`. Route is gated by
 * `roleGuard('super_admin')` (sc-622 factory) — the sidebar already
 * filters the Tax Rules item to super_admin (sc-623), so this is
 * defense-in-depth.
 */
@Component({
  selector: 'cs-tax-management-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule],
  template: `
    <section class="space-y-6">
      @if (toast(); as msg) {
        <div
          class="fixed right-6 top-6 z-50 rounded-lg bg-(--color-primary) px-4 py-2 text-sm text-white shadow-lg"
          role="status"
        >
          {{ msg }}
        </div>
      }

      <header class="flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-bold text-(--color-text)">Tax management</h1>
          <p class="mt-1 text-sm text-(--color-text-muted)">
            {{ rules().length }} rules across {{ states().length }} states
          </p>
        </div>
        <button
          type="button"
          (click)="toggleAddForm()"
          class="rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover)"
        >
          {{ showAddForm() ? 'Cancel' : '+ Add tax rule' }}
        </button>
      </header>

      @if (showAddForm()) {
        <form
          [formGroup]="addForm"
          (ngSubmit)="onSubmitAdd()"
          class="space-y-4 rounded-xl border border-(--color-border) bg-(--color-surface) p-6"
          aria-label="Add tax rule"
        >
          <h2 class="text-lg font-semibold text-(--color-text)">New tax rule</h2>

          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                State code
              </span>
              <input
                type="text"
                formControlName="state"
                maxlength="2"
                placeholder="e.g. NY"
                class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm uppercase text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
            </label>
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                Code
              </span>
              <input
                type="text"
                formControlName="code"
                placeholder="e.g. NY_RETAIL_EXCISE"
                class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm uppercase text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
            </label>
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                Tax basis
              </span>
              <select
                formControlName="taxBasis"
                class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              >
                @for (o of taxBasisOptions; track o.value) {
                  <option [value]="o.value">{{ o.label }}</option>
                }
              </select>
            </label>

            <label class="block md:col-span-2">
              <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                Display name
              </span>
              <input
                type="text"
                formControlName="name"
                placeholder="e.g. NY Retail Cannabis Excise (9%)"
                class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
            </label>
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                Rate
                @if (addForm.controls.taxBasis.value === 'per_mg_thc') {
                  ($/mg)
                } @else {
                  (decimal, e.g. 0.09 = 9%)
                }
              </span>
              <input
                type="number"
                step="any"
                formControlName="rate"
                [attr.placeholder]="
                  addForm.controls.taxBasis.value === 'per_mg_thc' ? '0.005' : '0.09'
                "
                class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
            </label>

            <label class="block md:col-span-3">
              <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                Statutory reference (optional)
              </span>
              <input
                type="text"
                formControlName="statutoryReference"
                placeholder="e.g. NY Cannabis Law § 130(2)"
                class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
            </label>
          </div>

          <div class="flex justify-end">
            <button
              type="submit"
              [disabled]="addForm.invalid || saving()"
              class="rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover) disabled:opacity-50"
            >
              @if (saving()) {
                Saving…
              } @else {
                Save rule
              }
            </button>
          </div>
        </form>
      }

      <div class="flex items-center gap-3">
        <select
          [value]="stateFilter()"
          (change)="onStateFilterChange($event)"
          aria-label="Filter by state"
          class="cursor-pointer rounded-lg border border-(--color-border) bg-(--color-surface) px-3 py-2 text-sm text-(--color-text) focus:outline-none"
        >
          <option value="">All states ({{ rules().length }})</option>
          @for (s of states(); track s) {
            <option [value]="s">{{ s }} ({{ ruleCountForState(s) }})</option>
          }
        </select>
        @if (stateFilter()) {
          <button
            type="button"
            (click)="clearStateFilter()"
            class="rounded-full border border-(--color-border) px-3 py-1.5 text-xs text-(--color-text-muted) hover:text-(--color-text)"
          >
            Clear filter
          </button>
        }
      </div>

      @if (isLoading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading tax rules…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load tax rules</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else if (grouped().length === 0) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-12 text-center text-sm text-(--color-text-muted)"
        >
          No tax rules found{{ stateFilter() ? ' for ' + stateFilter() : '' }}.
        </p>
      } @else {
        @for (group of grouped(); track group.state) {
          <div
            class="overflow-hidden rounded-xl border border-(--color-border) bg-(--color-surface)"
          >
            <header
              class="flex items-center justify-between border-b border-(--color-border) bg-(--color-bg) px-6 py-4"
            >
              <div>
                <h2 class="text-lg font-semibold text-(--color-text)">{{ group.state }}</h2>
                <p class="text-xs text-(--color-text-muted)">
                  {{ group.rules.length }} tax {{ group.rules.length === 1 ? 'rule' : 'rules' }}
                </p>
              </div>
              <span class="font-mono text-xs text-(--color-text-muted)">
                {{ group.combinedPercentLabel }}
              </span>
            </header>
            <ul class="divide-y divide-(--color-border)">
              @for (rule of group.rules; track rule.tax_category_id) {
                <li
                  class="flex items-center justify-between gap-4 px-6 py-4"
                  [class.opacity-50]="!rule.is_active"
                >
                  <div class="min-w-0 flex-1">
                    @if (editingId() === rule.tax_category_id) {
                      <input
                        type="text"
                        [formControl]="editForm.controls.name"
                        class="w-full rounded border border-(--color-border) bg-(--color-bg) px-2 py-1 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                        [attr.aria-label]="'Edit name for ' + rule.code"
                      />
                    } @else {
                      <div class="text-sm font-medium text-(--color-text)">{{ rule.name }}</div>
                    }
                    <div class="mt-1 flex items-center gap-3 text-xs text-(--color-text-muted)">
                      <span class="font-mono">{{ rule.code }}</span>
                      <span aria-hidden="true">·</span>
                      <span>{{ basisLabel(rule.tax_basis) }}</span>
                      @if (rule.statutory_reference) {
                        <span aria-hidden="true">·</span>
                        <span class="italic">{{ rule.statutory_reference }}</span>
                      }
                    </div>
                  </div>

                  <div class="flex items-center gap-3">
                    @if (editingId() === rule.tax_category_id) {
                      <input
                        type="number"
                        step="any"
                        [formControl]="editForm.controls.rate"
                        class="w-24 rounded border border-(--color-border) bg-(--color-bg) px-2 py-1 text-right text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                        [attr.aria-label]="'Edit rate for ' + rule.code"
                      />
                      <button
                        type="button"
                        (click)="onSaveEdit(rule)"
                        [disabled]="saving()"
                        class="rounded p-1.5 text-emerald-500 hover:bg-emerald-500/10 disabled:opacity-50"
                        [attr.aria-label]="'Save edits for ' + rule.code"
                      >
                        ✓
                      </button>
                      <button
                        type="button"
                        (click)="cancelEdit()"
                        class="rounded p-1.5 text-(--color-text-muted) hover:bg-(--color-surface-hover)"
                        aria-label="Cancel edit"
                      >
                        ✕
                      </button>
                    } @else {
                      <span
                        class="w-20 text-right text-sm font-semibold tabular-nums text-(--color-text)"
                      >
                        {{ formatRate(rule) }}
                      </span>
                      <button
                        type="button"
                        (click)="startEdit(rule)"
                        class="rounded p-1.5 text-(--color-text-muted) hover:bg-(--color-surface-hover) hover:text-(--color-text)"
                        [attr.aria-label]="'Edit ' + rule.code"
                      >
                        ✎
                      </button>
                      <button
                        type="button"
                        (click)="onToggleActive(rule)"
                        [disabled]="saving()"
                        class="rounded p-1.5 disabled:opacity-50"
                        [class]="
                          rule.is_active
                            ? 'text-emerald-500 hover:bg-emerald-500/10'
                            : 'text-(--color-text-muted) hover:bg-(--color-surface-hover)'
                        "
                        [attr.aria-label]="
                          (rule.is_active ? 'Deactivate ' : 'Activate ') + rule.code
                        "
                        [attr.title]="rule.is_active ? 'Deactivate' : 'Activate'"
                      >
                        {{ rule.is_active ? '●' : '○' }}
                      </button>
                    }
                  </div>
                </li>
              }
            </ul>
          </div>
        }
      }
    </section>
  `,
})
export class TaxManagementPage {
  private readonly svc = inject(TaxRulesService);

  protected readonly taxBasisOptions = TAX_BASIS_OPTIONS;
  protected readonly rules = this.svc.rules;
  protected readonly isLoading = this.svc.isLoading;
  protected readonly error = this.svc.error;
  protected readonly saving = this.svc.saving;

  protected readonly stateFilter = signal<string>('');
  protected readonly showAddForm = signal<boolean>(false);
  protected readonly editingId = signal<number | null>(null);
  protected readonly toast = signal<string | null>(null);

  protected readonly states = computed<readonly string[]>(() => {
    return [...new Set(this.rules().map((r) => r.state))].sort();
  });

  protected readonly grouped = computed<readonly RuleGroup[]>(() => {
    const filter = this.stateFilter();
    const filtered = filter ? this.rules().filter((r) => r.state === filter) : this.rules();
    const byState = new Map<string, TaxRule[]>();
    for (const r of filtered) {
      const list = byState.get(r.state) ?? [];
      list.push(r);
      byState.set(r.state, list);
    }
    return Array.from(byState.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([state, rules]) => ({
        state,
        rules,
        combinedPercentLabel: combinedLabel(rules),
      }));
  });

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load tax rules.';
  });

  /* eslint-disable @typescript-eslint/unbound-method --
   * Angular's reactive-forms API expects raw `Validators.*` references; the
   * `unbound-method` rule's `this:void` warning is a false positive for
   * these pure-function validator references.
   */
  protected readonly addForm = new FormGroup<AddFormControls>({
    state: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(2), Validators.maxLength(2)],
    }),
    code: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    name: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    rate: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    taxBasis: new FormControl('retail_price', {
      nonNullable: true,
      validators: [Validators.required],
    }),
    statutoryReference: new FormControl('', { nonNullable: true }),
  });

  protected readonly editForm = new FormGroup<EditFormControls>({
    name: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    rate: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
  });
  /* eslint-enable @typescript-eslint/unbound-method */

  protected toggleAddForm(): void {
    this.showAddForm.update((v) => !v);
  }

  protected onStateFilterChange(event: Event): void {
    this.stateFilter.set((event.target as HTMLSelectElement).value);
  }

  protected clearStateFilter(): void {
    this.stateFilter.set('');
  }

  protected ruleCountForState(state: string): number {
    return this.rules().filter((r) => r.state === state).length;
  }

  protected startEdit(rule: TaxRule): void {
    this.editingId.set(rule.tax_category_id);
    this.editForm.reset({ name: rule.name, rate: String(rule.rate) });
  }

  protected cancelEdit(): void {
    this.editingId.set(null);
  }

  protected async onSaveEdit(rule: TaxRule): Promise<void> {
    if (this.editForm.invalid) return;
    const v = this.editForm.getRawValue();
    const rate = parseFloat(v.rate);
    if (Number.isNaN(rate) || rate < 0) return;
    const namePatch = v.name !== rule.name ? v.name : undefined;
    const ratePatch = rate !== rule.rate ? rate : undefined;
    if (namePatch === undefined && ratePatch === undefined) {
      this.cancelEdit();
      return;
    }
    await this.svc.update({
      taxCategoryId: rule.tax_category_id,
      name: namePatch,
      rate: ratePatch,
    });
    this.editingId.set(null);
    this.flashToast('Tax rule updated');
  }

  protected async onToggleActive(rule: TaxRule): Promise<void> {
    await this.svc.update({
      taxCategoryId: rule.tax_category_id,
      isActive: !rule.is_active,
    });
    this.flashToast(rule.is_active ? 'Tax rule deactivated' : 'Tax rule activated');
  }

  protected async onSubmitAdd(): Promise<void> {
    if (this.addForm.invalid) return;
    const v = this.addForm.getRawValue();
    const rate = parseFloat(v.rate);
    if (Number.isNaN(rate)) return;
    await this.svc.add({
      state: v.state.toUpperCase(),
      code: v.code.toUpperCase(),
      name: v.name,
      rate,
      taxBasis: v.taxBasis,
      statutoryReference: v.statutoryReference.trim() || null,
    });
    this.addForm.reset({
      state: '',
      code: '',
      name: '',
      rate: '',
      taxBasis: 'retail_price',
      statutoryReference: '',
    });
    this.showAddForm.set(false);
    this.flashToast('Tax rule added');
  }

  protected formatRate(rule: TaxRule): string {
    if (rule.tax_basis === 'per_mg_thc') return '$' + rule.rate + '/mg';
    const pct = rule.rate * 100;
    return pct.toFixed(pct % 1 === 0 ? 0 : 3) + '%';
  }

  protected basisLabel(basis: string): string {
    return TAX_BASIS_OPTIONS.find((o) => o.value === basis)?.label ?? basis;
  }

  private flashToast(message: string): void {
    this.toast.set(message);
    setTimeout(() => this.toast.set(null), 3000);
  }
}

function combinedLabel(rules: readonly TaxRule[]): string {
  const sum = rules
    .filter((r) => r.is_active && r.tax_basis !== 'per_mg_thc')
    .reduce((acc, r) => acc + r.rate * 100, 0);
  return 'Combined: ' + sum.toFixed(2) + '% + THC excise';
}

// apps/admin/src/pages/TaxManagementPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { Plus, Pencil, X, Check, CircleDot, CircleOff, Search } from 'lucide-react';

// ── GraphQL ────────────────────────────────────────────────────────────

const GET_TAX_RULES = `query { platformTaxRules { tax_category_id state code name rate tax_basis statutory_reference is_active } }`;

const ADD_TAX_RULE = `mutation($state: String!, $code: String!, $name: String!, $rate: Float!, $taxBasis: String!, $statutoryReference: String) {
  addTaxRule(state: $state, code: $code, name: $name, rate: $rate, taxBasis: $taxBasis, statutoryReference: $statutoryReference) {
    tax_category_id state code name rate tax_basis statutory_reference is_active
  }
}`;

const UPDATE_TAX_RULE = `mutation($taxCategoryId: Int!, $rate: Float, $isActive: Boolean, $name: String) {
  updateTaxRule(taxCategoryId: $taxCategoryId, rate: $rate, isActive: $isActive, name: $name) {
    tax_category_id state code name rate tax_basis statutory_reference is_active
  }
}`;

// ── Types ──────────────────────────────────────────────────────────────

interface TaxRule {
  tax_category_id: number;
  state: string;
  code: string;
  name: string;
  rate: number;
  tax_basis: string;
  statutory_reference: string | null;
  is_active: boolean;
}

interface NewRuleForm {
  state: string;
  code: string;
  name: string;
  rate: string;
  taxBasis: string;
  statutoryReference: string;
}

const EMPTY_FORM: NewRuleForm = { state: '', code: '', name: '', rate: '', taxBasis: 'retail_price', statutoryReference: '' };

const TAX_BASIS_OPTIONS = [
  { value: 'retail_price', label: 'Retail Price (%)' },
  { value: 'per_mg_thc', label: 'Per mg THC ($)' },
  { value: 'wholesale_price', label: 'Wholesale Price (%)' },
];

function formatRate(rule: TaxRule): string {
  if (rule.tax_basis === 'per_mg_thc') return `$${rule.rate}/mg`;
  return `${(rule.rate * 100).toFixed(rule.rate * 100 % 1 === 0 ? 0 : 3)}%`;
}

function basisLabel(basis: string): string {
  return TAX_BASIS_OPTIONS.find(o => o.value === basis)?.label ?? basis;
}

// ── Component ──────────────────────────────────────────────────────────

export function TaxManagementPage() {
  const queryClient = useQueryClient();
  const [stateFilter, setStateFilter] = useState('');
  const [showAddForm, setShowAddForm] = useState(false);
  const [newRule, setNewRule] = useState<NewRuleForm>(EMPTY_FORM);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editForm, setEditForm] = useState<{ name: string; rate: string }>({ name: '', rate: '' });
  const [toast, setToast] = useState<string | null>(null);

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(null), 3000); };

  const { data, isLoading } = useQuery({
    queryKey: ['taxRules'],
    queryFn: () => gqlRequest<{ platformTaxRules: TaxRule[] }>(GET_TAX_RULES),
    select: (d) => d.platformTaxRules,
  });

  const addMutation = useMutation({
    mutationFn: (input: NewRuleForm) =>
      gqlRequest(ADD_TAX_RULE, {
        state: input.state.toUpperCase(),
        code: input.code.toUpperCase(),
        name: input.name,
        rate: parseFloat(input.rate),
        taxBasis: input.taxBasis,
        statutoryReference: input.statutoryReference || null,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['taxRules'] });
      setNewRule(EMPTY_FORM);
      setShowAddForm(false);
      showToast('Tax rule added');
    },
  });

  const updateMutation = useMutation({
    mutationFn: (input: { taxCategoryId: number; rate?: number; isActive?: boolean; name?: string }) =>
      gqlRequest(UPDATE_TAX_RULE, input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['taxRules'] });
      setEditingId(null);
      showToast('Tax rule updated');
    },
  });

  const rules = data ?? [];
  const filtered = stateFilter ? rules.filter(r => r.state === stateFilter) : rules;
  const states = [...new Set(rules.map(r => r.state))].sort();

  // Group by state
  const grouped = filtered.reduce<Record<string, TaxRule[]>>((acc, rule) => {
    (acc[rule.state] ??= []).push(rule);
    return acc;
  }, {});

  const startEdit = (rule: TaxRule) => {
    setEditingId(rule.tax_category_id);
    setEditForm({ name: rule.name, rate: String(rule.rate) });
  };

  const saveEdit = (rule: TaxRule) => {
    const rate = parseFloat(editForm.rate);
    if (isNaN(rate) || rate < 0) return;
    updateMutation.mutate({
      taxCategoryId: rule.tax_category_id,
      rate: rate !== rule.rate ? rate : undefined,
      name: editForm.name !== rule.name ? editForm.name : undefined,
    });
  };

  const toggleActive = (rule: TaxRule) => {
    updateMutation.mutate({ taxCategoryId: rule.tax_category_id, isActive: !rule.is_active });
  };

  if (isLoading) return <div className="text-txt-muted">Loading tax rules...</div>;

  return (
    <div className="space-y-6">
      {/* Toast */}
      {toast && (
        <div className="fixed top-6 right-6 bg-brand-500 text-white px-4 py-2 rounded-lg shadow-lg text-sm z-50 animate-fade-in">
          {toast}
        </div>
      )}

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-txt">Tax Management</h1>
          <p className="text-sm text-txt-muted mt-1">
            {rules.length} rules across {states.length} states
          </p>
        </div>
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="flex items-center gap-2 px-4 py-2 bg-brand-500 text-white rounded-lg text-sm font-medium hover:bg-brand-600 transition-colors"
        >
          {showAddForm ? <X size={16} /> : <Plus size={16} />}
          {showAddForm ? 'Cancel' : 'Add Tax Rule'}
        </button>
      </div>

      {/* Add Form */}
      {showAddForm && (
        <div className="bg-surface rounded-xl border border-bdr p-6 space-y-4">
          <h2 className="text-lg font-semibold text-txt">New Tax Rule</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-medium text-txt-muted mb-1">State Code</label>
              <input
                value={newRule.state}
                onChange={e => setNewRule({ ...newRule, state: e.target.value })}
                placeholder="e.g. NY, CA, IL"
                maxLength={2}
                className="w-full px-3 py-2 bg-surface-alt border border-bdr rounded-lg text-sm text-txt uppercase"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-txt-muted mb-1">Code</label>
              <input
                value={newRule.code}
                onChange={e => setNewRule({ ...newRule, code: e.target.value })}
                placeholder="e.g. NY_RETAIL_EXCISE"
                className="w-full px-3 py-2 bg-surface-alt border border-bdr rounded-lg text-sm text-txt uppercase"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-txt-muted mb-1">Tax Basis</label>
              <select
                value={newRule.taxBasis}
                onChange={e => setNewRule({ ...newRule, taxBasis: e.target.value })}
                className="w-full px-3 py-2 bg-surface-alt border border-bdr rounded-lg text-sm text-txt"
              >
                {TAX_BASIS_OPTIONS.map(o => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </div>
            <div className="md:col-span-2">
              <label className="block text-xs font-medium text-txt-muted mb-1">Display Name</label>
              <input
                value={newRule.name}
                onChange={e => setNewRule({ ...newRule, name: e.target.value })}
                placeholder="e.g. NY Retail Cannabis Excise (9%)"
                className="w-full px-3 py-2 bg-surface-alt border border-bdr rounded-lg text-sm text-txt"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-txt-muted mb-1">
                Rate {newRule.taxBasis === 'per_mg_thc' ? '($/mg)' : '(decimal, e.g. 0.09 = 9%)'}
              </label>
              <input
                type="number"
                step="any"
                value={newRule.rate}
                onChange={e => setNewRule({ ...newRule, rate: e.target.value })}
                placeholder={newRule.taxBasis === 'per_mg_thc' ? '0.005' : '0.09'}
                className="w-full px-3 py-2 bg-surface-alt border border-bdr rounded-lg text-sm text-txt"
              />
            </div>
            <div className="md:col-span-3">
              <label className="block text-xs font-medium text-txt-muted mb-1">Statutory Reference (optional)</label>
              <input
                value={newRule.statutoryReference}
                onChange={e => setNewRule({ ...newRule, statutoryReference: e.target.value })}
                placeholder="e.g. NY Cannabis Law § 130(2)"
                className="w-full px-3 py-2 bg-surface-alt border border-bdr rounded-lg text-sm text-txt"
              />
            </div>
          </div>
          <div className="flex justify-end">
            <button
              onClick={() => addMutation.mutate(newRule)}
              disabled={!newRule.state || !newRule.code || !newRule.name || !newRule.rate || addMutation.isPending}
              className="flex items-center gap-2 px-4 py-2 bg-brand-500 text-white rounded-lg text-sm font-medium hover:bg-brand-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {addMutation.isPending ? 'Saving...' : 'Save Rule'}
            </button>
          </div>
          {addMutation.isError && (
            <p className="text-sm text-red-500">Error: {(addMutation.error as Error).message}</p>
          )}
        </div>
      )}

      {/* Filter */}
      <div className="flex items-center gap-3">
        <div className="relative">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-txt-muted" />
          <select
            value={stateFilter}
            onChange={e => setStateFilter(e.target.value)}
            className="pl-9 pr-4 py-2 bg-surface border border-bdr rounded-lg text-sm text-txt appearance-none cursor-pointer"
          >
            <option value="">All States ({rules.length})</option>
            {states.map(s => (
              <option key={s} value={s}>{s} ({rules.filter(r => r.state === s).length})</option>
            ))}
          </select>
        </div>
        <div className="flex gap-2">
          {stateFilter && (
            <button
              onClick={() => setStateFilter('')}
              className="px-3 py-1.5 text-xs bg-surface-alt border border-bdr rounded-full text-txt-muted hover:text-txt transition-colors"
            >
              Clear filter
            </button>
          )}
        </div>
      </div>

      {/* Rules by State */}
      {Object.entries(grouped).sort(([a], [b]) => a.localeCompare(b)).map(([state, stateRules]) => (
        <div key={state} className="bg-surface rounded-xl border border-bdr overflow-hidden">
          <div className="px-6 py-4 border-b border-bdr bg-surface-alt flex items-center justify-between">
            <div>
              <h2 className="text-lg font-semibold text-txt">{state}</h2>
              <p className="text-xs text-txt-muted">{stateRules.length} tax {stateRules.length === 1 ? 'rule' : 'rules'}</p>
            </div>
            <span className="text-xs text-txt-muted font-mono">
              Combined: {stateRules.filter(r => r.is_active && r.tax_basis !== 'per_mg_thc')
                .reduce((sum, r) => sum + r.rate * 100, 0).toFixed(2)}% + THC excise
            </span>
          </div>
          <div className="divide-y divide-bdr">
            {stateRules.map(rule => (
              <div
                key={rule.tax_category_id}
                className={`px-6 py-4 flex items-center justify-between gap-4 ${!rule.is_active ? 'opacity-50' : ''}`}
              >
                <div className="flex-1 min-w-0">
                  {editingId === rule.tax_category_id ? (
                    <input
                      value={editForm.name}
                      onChange={e => setEditForm({ ...editForm, name: e.target.value })}
                      className="w-full px-2 py-1 bg-surface-alt border border-bdr rounded text-sm text-txt"
                    />
                  ) : (
                    <div className="text-sm font-medium text-txt">{rule.name}</div>
                  )}
                  <div className="flex items-center gap-3 mt-1">
                    <span className="text-xs font-mono text-txt-muted">{rule.code}</span>
                    <span className="text-xs text-txt-muted">·</span>
                    <span className="text-xs text-txt-muted">{basisLabel(rule.tax_basis)}</span>
                    {rule.statutory_reference && (
                      <>
                        <span className="text-xs text-txt-muted">·</span>
                        <span className="text-xs text-txt-muted italic">{rule.statutory_reference}</span>
                      </>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  {editingId === rule.tax_category_id ? (
                    <>
                      <input
                        type="number"
                        step="any"
                        value={editForm.rate}
                        onChange={e => setEditForm({ ...editForm, rate: e.target.value })}
                        className="w-24 px-2 py-1 bg-surface-alt border border-bdr rounded text-sm text-txt text-right"
                      />
                      <button onClick={() => saveEdit(rule)} className="p-1.5 text-brand-500 hover:bg-brand-50 rounded transition-colors">
                        <Check size={16} />
                      </button>
                      <button onClick={() => setEditingId(null)} className="p-1.5 text-txt-muted hover:bg-surface-alt rounded transition-colors">
                        <X size={16} />
                      </button>
                    </>
                  ) : (
                    <>
                      <span className="text-sm font-semibold text-txt tabular-nums w-20 text-right">
                        {formatRate(rule)}
                      </span>
                      <button onClick={() => startEdit(rule)} className="p-1.5 text-txt-muted hover:text-txt hover:bg-surface-alt rounded transition-colors">
                        <Pencil size={14} />
                      </button>
                      <button
                        onClick={() => toggleActive(rule)}
                        className={`p-1.5 rounded transition-colors ${rule.is_active ? 'text-brand-500 hover:bg-brand-50' : 'text-txt-muted hover:bg-surface-alt'}`}
                        title={rule.is_active ? 'Deactivate' : 'Activate'}
                      >
                        {rule.is_active ? <CircleDot size={14} /> : <CircleOff size={14} />}
                      </button>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}

      {filtered.length === 0 && (
        <div className="text-center py-12 text-txt-muted">
          No tax rules found{stateFilter ? ` for ${stateFilter}` : ''}.
        </div>
      )}
    </div>
  );
}
