// apps/admin/src/pages/CompliancePage.tsx
import { useDashboard } from '../hooks/useDashboard';
import { ShieldCheck, RefreshCw, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';

export function CompliancePage() {
  const { data, isLoading } = useDashboard(30);

  if (isLoading) return <div className="text-txt-muted">Loading...</div>;

  const compliance = data?.compliance;
  const metrc = data?.metrcSync;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-txt">Compliance & Metrc</h1>

      {/* Compliance Score */}
      <div className="bg-surface rounded-xl border border-border p-6">
        <div className="flex items-center gap-4 mb-6">
          <div className={`w-16 h-16 rounded-full flex items-center justify-center text-2xl font-bold ${
            compliance?.compliancePercent === 100 ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'
          }`}>
            {compliance?.compliancePercent ?? 0}%
          </div>
          <div>
            <h2 className="text-lg font-semibold text-txt">Product Compliance</h2>
            <p className="text-sm text-txt-secondary">
              {compliance?.compliantProducts}/{compliance?.totalProducts} products fully compliant
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="flex items-center gap-2">
            {compliance?.missingUid === 0
              ? <CheckCircle size={16} className="text-green-500" />
              : <XCircle size={16} className="text-red-500" />}
            <div>
              <p className="text-sm font-medium">Metrc UIDs</p>
              <p className="text-xs text-txt-secondary">{compliance?.missingUid ?? 0} missing</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {compliance?.missingCategory === 0
              ? <CheckCircle size={16} className="text-green-500" />
              : <XCircle size={16} className="text-red-500" />}
            <div>
              <p className="text-sm font-medium">Item Categories</p>
              <p className="text-xs text-txt-secondary">{compliance?.missingCategory ?? 0} missing</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {compliance?.missingPackageLabel === 0
              ? <CheckCircle size={16} className="text-green-500" />
              : <XCircle size={16} className="text-red-500" />}
            <div>
              <p className="text-sm font-medium">Package Labels</p>
              <p className="text-xs text-txt-secondary">{compliance?.missingPackageLabel ?? 0} missing</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <CheckCircle size={16} className="text-green-500" />
            <div>
              <p className="text-sm font-medium">Approved</p>
              <p className="text-xs text-txt-secondary">{compliance?.compliantProducts ?? 0} approved</p>
            </div>
          </div>
        </div>
      </div>

      {/* Metrc Sync */}
      <div className="bg-surface rounded-xl border border-border p-6">
        <h2 className="text-lg font-semibold text-txt mb-4 flex items-center gap-2">
          <RefreshCw size={18} /> Metrc Sync Status
        </h2>

        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <div>
            <p className="text-sm text-txt-secondary">Total Syncs</p>
            <p className="text-2xl font-bold">{metrc?.totalSyncs ?? 0}</p>
          </div>
          <div>
            <p className="text-sm text-txt-secondary">Success</p>
            <p className="text-2xl font-bold text-green-600">{metrc?.successCount ?? 0}</p>
          </div>
          <div>
            <p className="text-sm text-txt-secondary">Failed</p>
            <p className={`text-2xl font-bold ${(metrc?.failedCount ?? 0) > 0 ? 'text-red-600' : ''}`}>
              {metrc?.failedCount ?? 0}
            </p>
          </div>
          <div>
            <p className="text-sm text-txt-secondary">Success Rate</p>
            <p className={`text-2xl font-bold ${
              (metrc?.successRate ?? 100) >= 90 ? 'text-green-600' :
              (metrc?.successRate ?? 100) >= 50 ? 'text-amber-600' : 'text-red-600'
            }`}>{metrc?.successRate ?? 0}%</p>
          </div>
          <div>
            <p className="text-sm text-txt-secondary">Awaiting Sync</p>
            <p className={`text-2xl font-bold ${(metrc?.ordersAwaitingSync ?? 0) > 0 ? 'text-amber-600' : ''}`}>
              {metrc?.ordersAwaitingSync ?? 0}
            </p>
          </div>
        </div>

        {metrc?.lastSyncAt && (
          <p className="text-xs text-txt-muted mt-4">
            Last successful sync: {new Date(metrc.lastSyncAt).toLocaleString()}
          </p>
        )}
      </div>
    </div>
  );
}

// packages/angular/projects/admin/src/app/pages/compliance/compliance-page.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';

import { DashboardService } from '../dashboard/dashboard.service';

/**
 * Admin Compliance & Metrc summary — sourced entirely from the
 * existing `dashboard` query (sc-624). Mirrors React parity:
 * compliance score donut + per-attribute checklist + Metrc sync
 * counters. The failed-sync retry table from the filed scope isn't
 * in the React admin — file a follow-up once we have a
 * `failedMetrcSyncs` + retry-queue UI need.
 */
@Component({
  selector: 'cs-compliance-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="space-y-6">
      <h1 class="text-2xl font-bold text-(--color-text)">Compliance &amp; Metrc</h1>

      @if (loading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading compliance…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load compliance</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else if (data(); as d) {
        <!-- Compliance Score -->
        <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
          <div class="mb-6 flex items-center gap-4">
            <div
              class="flex h-16 w-16 items-center justify-center rounded-full text-2xl font-bold"
              [class]="
                d.compliance.compliancePercent === 100
                  ? 'bg-emerald-500/15 text-emerald-500'
                  : 'bg-amber-500/15 text-amber-500'
              "
              aria-label="Overall compliance score"
            >
              {{ d.compliance.compliancePercent }}%
            </div>
            <div>
              <h2 class="text-lg font-semibold text-(--color-text)">Product compliance</h2>
              <p class="text-sm text-(--color-text-secondary)">
                {{ d.compliance.compliantProducts }}/{{ d.compliance.totalProducts }} products fully
                compliant
              </p>
            </div>
          </div>

          <ul class="grid grid-cols-2 gap-4 md:grid-cols-4">
            <li class="flex items-center gap-2">
              <span
                class="text-lg"
                [class]="d.compliance.missingUid === 0 ? 'text-emerald-500' : 'text-rose-500'"
                aria-hidden="true"
              >
                {{ d.compliance.missingUid === 0 ? '✓' : '✗' }}
              </span>
              <div>
                <p class="text-sm font-medium text-(--color-text)">Metrc UIDs</p>
                <p class="text-xs text-(--color-text-secondary)">
                  {{ d.compliance.missingUid }} missing
                </p>
              </div>
            </li>
            <li class="flex items-center gap-2">
              <span
                class="text-lg"
                [class]="d.compliance.missingCategory === 0 ? 'text-emerald-500' : 'text-rose-500'"
                aria-hidden="true"
              >
                {{ d.compliance.missingCategory === 0 ? '✓' : '✗' }}
              </span>
              <div>
                <p class="text-sm font-medium text-(--color-text)">Item categories</p>
                <p class="text-xs text-(--color-text-secondary)">
                  {{ d.compliance.missingCategory }} missing
                </p>
              </div>
            </li>
            <li class="flex items-center gap-2">
              <span
                class="text-lg"
                [class]="
                  d.compliance.missingPackageLabel === 0 ? 'text-emerald-500' : 'text-rose-500'
                "
                aria-hidden="true"
              >
                {{ d.compliance.missingPackageLabel === 0 ? '✓' : '✗' }}
              </span>
              <div>
                <p class="text-sm font-medium text-(--color-text)">Package labels</p>
                <p class="text-xs text-(--color-text-secondary)">
                  {{ d.compliance.missingPackageLabel }} missing
                </p>
              </div>
            </li>
            <li class="flex items-center gap-2">
              <span class="text-lg text-emerald-500" aria-hidden="true">✓</span>
              <div>
                <p class="text-sm font-medium text-(--color-text)">Approved</p>
                <p class="text-xs text-(--color-text-secondary)">
                  {{ d.compliance.compliantProducts }} approved
                </p>
              </div>
            </li>
          </ul>
        </div>

        <!-- Metrc Sync -->
        <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
          <h2 class="mb-4 flex items-center gap-2 text-lg font-semibold text-(--color-text)">
            <span aria-hidden="true">↻</span> Metrc sync status
          </h2>

          <div class="grid grid-cols-2 gap-4 md:grid-cols-5">
            <div>
              <p class="text-sm text-(--color-text-secondary)">Total syncs</p>
              <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                {{ d.metrcSync.totalSyncs }}
              </p>
            </div>
            <div>
              <p class="text-sm text-(--color-text-secondary)">Success</p>
              <p class="text-2xl font-bold text-emerald-500 tabular-nums">
                {{ d.metrcSync.successCount }}
              </p>
            </div>
            <div>
              <p class="text-sm text-(--color-text-secondary)">Failed</p>
              <p
                class="text-2xl font-bold tabular-nums"
                [class]="d.metrcSync.failedCount > 0 ? 'text-rose-500' : 'text-(--color-text)'"
              >
                {{ d.metrcSync.failedCount }}
              </p>
            </div>
            <div>
              <p class="text-sm text-(--color-text-secondary)">Success rate</p>
              <p
                class="text-2xl font-bold tabular-nums"
                [class]="successRateClass(d.metrcSync.successRate)"
              >
                {{ d.metrcSync.successRate }}%
              </p>
            </div>
            <div>
              <p class="text-sm text-(--color-text-secondary)">Awaiting sync</p>
              <p
                class="text-2xl font-bold tabular-nums"
                [class]="
                  d.metrcSync.ordersAwaitingSync > 0 ? 'text-amber-500' : 'text-(--color-text)'
                "
              >
                {{ d.metrcSync.ordersAwaitingSync }}
              </p>
            </div>
          </div>

          @if (d.metrcSync.lastSyncAt) {
            <p class="mt-4 text-xs text-(--color-text-muted)">
              Last successful sync: {{ formatDateTime(d.metrcSync.lastSyncAt) }}
            </p>
          }
        </div>
      }
    </section>
  `,
})
export class CompliancePage {
  private readonly dashboard = inject(DashboardService);

  protected readonly data = this.dashboard.data;
  protected readonly loading = this.dashboard.isLoading;
  protected readonly error = this.dashboard.error;

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load compliance.';
  });

  protected successRateClass(rate: number): string {
    if (rate >= 90) return 'text-emerald-500';
    if (rate >= 50) return 'text-amber-500';
    return 'text-rose-500';
  }

  protected formatDateTime(value: string | null | undefined): string {
    if (!value) return '—';
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return '—';
    return d.toLocaleString();
  }
}
