// packages/angular/projects/storefront/src/app/layout/footer.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

interface CategoryLink {
  readonly label: string;
  readonly slug: string;
}

interface AccountLink {
  readonly label: string;
  readonly path: string;
}

const SHOP_CATEGORIES: readonly CategoryLink[] = [
  { label: 'Flower', slug: 'flower' },
  { label: 'Edibles', slug: 'edibles' },
  { label: 'Vapes', slug: 'vapes' },
  { label: 'Pre-Rolls', slug: 'pre-rolls' },
  { label: 'Concentrates', slug: 'concentrates' },
];

const ACCOUNT_LINKS: readonly AccountLink[] = [
  { label: 'My Account', path: '/account' },
  { label: 'Order History', path: '/account' },
  { label: 'Rewards', path: '/account' },
  { label: 'Sign In', path: '/login' },
];

@Component({
  selector: 'cs-footer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink],
  template: `
    <footer class="bg-[#0a1a0f] text-white/40">
      <div class="mx-auto max-w-7xl px-6 py-16">
        <div class="mb-12 grid grid-cols-1 gap-10 md:grid-cols-4">
          <div class="md:col-span-1">
            <div class="mb-4 flex items-center gap-2.5">
              <div
                class="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-600 text-sm font-black tracking-tighter text-white"
              >
                GL
              </div>
              <span
                class="text-lg font-semibold text-white"
                style="font-family: 'Playfair Display', Georgia, serif"
                >GreenLeaf</span
              >
            </div>
            <p class="text-sm leading-relaxed">
              Curated cannabis. Tested for quality. Delivered with care.
            </p>
          </div>

          <div>
            <h4 class="mb-4 text-xs font-semibold uppercase tracking-wider text-white/60">Shop</h4>
            <ul class="space-y-2.5">
              @for (cat of shopCategories; track cat.slug) {
                <li>
                  <a
                    class="text-sm transition-colors hover:text-white"
                    [routerLink]="['/products']"
                    [queryParams]="{ category: cat.slug }"
                    >{{ cat.label }}</a
                  >
                </li>
              }
            </ul>
          </div>

          <div>
            <h4 class="mb-4 text-xs font-semibold uppercase tracking-wider text-white/60">
              Account
            </h4>
            <ul class="space-y-2.5">
              @for (link of accountLinks; track link.label) {
                <li>
                  <a
                    class="text-sm transition-colors hover:text-white"
                    [routerLink]="[link.path]"
                    >{{ link.label }}</a
                  >
                </li>
              }
            </ul>
          </div>

          <div>
            <h4 class="mb-4 text-xs font-semibold uppercase tracking-wider text-white/60">Hours</h4>
            <ul class="space-y-2.5 text-sm">
              <li>Mon–Sat: 10am – 9pm</li>
              <li>Sunday: 11am – 7pm</li>
              <li class="pt-2 text-white/60">21+ only. Valid ID required.</li>
            </ul>
          </div>
        </div>

        <div
          class="flex flex-col items-center justify-between gap-4 border-t border-white/5 pt-8 sm:flex-row"
        >
          <p class="text-xs text-white/20">© {{ year }} GreenLeaf Dispensary</p>
          <p class="text-xs text-white/20">
            Powered by <span class="text-emerald-500/40">CannaSaas</span>
          </p>
        </div>
      </div>
    </footer>
  `,
})
export class Footer {
  protected readonly shopCategories = SHOP_CATEGORIES;
  protected readonly accountLinks = ACCOUNT_LINKS;
  protected readonly year = new Date().getFullYear();
}

// apps/storefront/src/components/layout/Footer.tsx
import Link from 'next/link';

export function Footer() {
  return (
    <footer className="bg-[#0a1a0f] text-white/40">
      <div className="max-w-7xl mx-auto px-6 py-16">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10 mb-12">
          <div className="md:col-span-1">
            <div className="flex items-center gap-2.5 mb-4">
              <div className="w-8 h-8 rounded-lg bg-emerald-600 flex items-center justify-center text-sm font-black tracking-tighter text-white">GL</div>
              <span className="text-lg font-semibold text-white" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>GreenLeaf</span>
            </div>
            <p className="text-sm leading-relaxed">Curated cannabis. Tested for quality. Delivered with care.</p>
          </div>
          <div>
            <h4 className="text-xs font-semibold text-white/60 tracking-wider uppercase mb-4">Shop</h4>
            <ul className="space-y-2.5">
              {['Flower', 'Edibles', 'Vapes', 'Pre-Rolls', 'Concentrates'].map((item) => (
                <li key={item}><Link href={`/products?category=${item.toLowerCase()}`} className="text-sm hover:text-white transition-colors">{item}</Link></li>
              ))}
            </ul>
          </div>
          <div>
            <h4 className="text-xs font-semibold text-white/60 tracking-wider uppercase mb-4">Account</h4>
            <ul className="space-y-2.5">
              {[{ label: 'My Account', href: '/account' }, { label: 'Order History', href: '/account' }, { label: 'Rewards', href: '/account' }, { label: 'Sign In', href: '/login' }].map((item) => (
                <li key={item.label}><Link href={item.href} className="text-sm hover:text-white transition-colors">{item.label}</Link></li>
              ))}
            </ul>
          </div>
          <div>
            <h4 className="text-xs font-semibold text-white/60 tracking-wider uppercase mb-4">Hours</h4>
            <ul className="space-y-2.5 text-sm">
              <li>Mon–Sat: 10am – 9pm</li>
              <li>Sunday: 11am – 7pm</li>
              <li className="pt-2 text-white/60">21+ only. Valid ID required.</li>
            </ul>
          </div>
        </div>
        <div className="border-t border-white/5 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-white/20">© {new Date().getFullYear()} GreenLeaf Dispensary</p>
          <p className="text-xs text-white/20">Powered by <span className="text-emerald-500/40">CannaSaas</span></p>
        </div>
      </div>
    </footer>
  );
}
