// apps/admin/src/pages/ProductsPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { Package, Search, Plus, Pencil, Trash2, X, Save, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';

const PRODUCTS_QUERY = `
  query($dispensaryId: ID!, $limit: Int) {
    products(dispensaryId: $dispensaryId, limit: $limit) {
      id name description strainType strainName thcPercent cbdPercent isActive isApproved
      variants { variantId name sku quantityPerUnit retailPrice stockQuantity stockStatus }
    }
  }
`;

const CREATE_PRODUCT = `mutation($input: CreateProductInput!) { createProduct(input: $input) { id name } }`;
const UPDATE_PRODUCT = `mutation($input: UpdateProductInput!) { updateProduct(input: $input) { id name } }`;
const UPDATE_PRICE = `mutation($input: UpdateVariantPriceInput!) { updateVariantPrice(input: $input) }`;
const DELETE_PRODUCT = `mutation($productId: ID!, $dispensaryId: ID!) { deleteProduct(productId: $productId, dispensaryId: $dispensaryId) }`;

const STRAIN_BADGE: Record<string, string> = {
  sativa: 'bg-orange-50 text-orange-700',
  indica: 'bg-purple-50 text-purple-700',
  hybrid: 'bg-green-50 text-green-700',
};

const STOCK_BADGE: Record<string, { label: string; cls: string }> = {
  in_stock: { label: 'In Stock', cls: 'bg-green-50 text-green-700' },
  low_stock: { label: 'Low Stock', cls: 'bg-amber-50 text-amber-700' },
  out_of_stock: { label: 'Sold Out', cls: 'bg-red-50 text-red-700' },
};

interface ProductForm {
  name: string;
  description: string;
  strainType: string;
  strainName: string;
  thcPercent: string;
  cbdPercent: string;
  isActive: boolean;
  variantName: string;
  variantQuantityG: string;
  retailPrice: string;
}

const emptyForm: ProductForm = {
  name: '', description: '', strainType: 'hybrid', strainName: '',
  thcPercent: '', cbdPercent: '', isActive: true,
  variantName: '3.5g Jar', variantQuantityG: '3.5', retailPrice: '',
};

export function ProductsPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId) || 'c0000000-0000-0000-0000-000000000001';
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<any>(null);
  const [editing, setEditing] = useState(false);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState<ProductForm>(emptyForm);
  const [priceEdit, setPriceEdit] = useState<string>('');
  const [confirmDelete, setConfirmDelete] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['adminProducts', dispensaryId],
    queryFn: () => gqlRequest<{ products: any[] }>(PRODUCTS_QUERY, { dispensaryId, limit: 100 }),
    enabled: !!dispensaryId,
  });

  const products = data?.products ?? [];
  const filtered = search
    ? products.filter((p: any) => p.name.toLowerCase().includes(search.toLowerCase()))
    : products;

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['adminProducts'] });
    queryClient.invalidateQueries({ queryKey: ['dashboard'] });
  };

  const createMut = useMutation({
    mutationFn: (input: any) => gqlRequest(CREATE_PRODUCT, { input }),
    onSuccess: () => { invalidate(); setCreating(false); setForm(emptyForm); },
  });

  const updateMut = useMutation({
    mutationFn: (input: any) => gqlRequest(UPDATE_PRODUCT, { input }),
    onSuccess: () => { invalidate(); setEditing(false); setSelected(null); },
  });

  const priceMut = useMutation({
    mutationFn: (input: any) => gqlRequest(UPDATE_PRICE, { input }),
    onSuccess: () => { invalidate(); setPriceEdit(''); },
  });

  const deleteMut = useMutation({
    mutationFn: (vars: any) => gqlRequest(DELETE_PRODUCT, vars),
    onSuccess: () => { invalidate(); setSelected(null); setConfirmDelete(false); },
  });

  const openEdit = (p: any) => {
    setSelected(p);
    setEditing(true);
    setCreating(false);
    setConfirmDelete(false);
    const v = p.variants?.[0];
    setForm({
      name: p.name || '',
      description: p.description || '',
      strainType: p.strainType || 'hybrid',
      strainName: p.strainName || '',
      thcPercent: p.thcPercent?.toString() || '',
      cbdPercent: p.cbdPercent?.toString() || '',
      isActive: p.isActive ?? true,
      variantName: v?.name || '',
      variantQuantityG: v?.quantityPerUnit?.toString() || '',
      retailPrice: v?.retailPrice?.toString() || '',
    });
    setPriceEdit(v?.retailPrice?.toString() || '');
  };

  const openCreate = () => {
    setSelected(null);
    setEditing(false);
    setCreating(true);
    setConfirmDelete(false);
    setForm(emptyForm);
  };

  const openDetail = (p: any) => {
    if (editing || creating) return;
    setSelected(p);
    setEditing(false);
    setCreating(false);
    setConfirmDelete(false);
    setPriceEdit(p.variants?.[0]?.retailPrice?.toString() || '');
  };

  const handleSaveNew = () => {
    createMut.mutate({
      dispensaryId,
      name: form.name,
      description: form.description || undefined,
      strainType: form.strainType || undefined,
      strainName: form.strainName || undefined,
      thcPercent: form.thcPercent ? parseFloat(form.thcPercent) : undefined,
      cbdPercent: form.cbdPercent ? parseFloat(form.cbdPercent) : undefined,
      isActive: form.isActive,
      variantName: form.variantName || undefined,
      variantQuantityG: form.variantQuantityG ? parseFloat(form.variantQuantityG) : undefined,
      retailPrice: form.retailPrice ? parseFloat(form.retailPrice) : undefined,
    });
  };

  const handleSaveEdit = () => {
    updateMut.mutate({
      productId: selected.id,
      dispensaryId,
      name: form.name,
      description: form.description,
      strainType: form.strainType,
      strainName: form.strainName,
      thcPercent: form.thcPercent ? parseFloat(form.thcPercent) : undefined,
      cbdPercent: form.cbdPercent ? parseFloat(form.cbdPercent) : undefined,
      isActive: form.isActive,
    });
  };

  const handlePriceSave = () => {
    const v = selected?.variants?.[0];
    if (!v || !priceEdit) return;
    priceMut.mutate({ variantId: v.variantId, dispensaryId, price: parseFloat(priceEdit) });
  };

  const closePanel = () => {
    setSelected(null);
    setEditing(false);
    setCreating(false);
    setConfirmDelete(false);
  };

  const showPanel = selected || creating;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-txt">Products ({filtered.length})</h1>
        <button onClick={openCreate}
          className="flex items-center gap-2 bg-brand-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-brand-700 transition-colors">
          <Plus size={16} /> Add Product
        </button>
      </div>

      <div className="relative max-w-md">
        <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-txt-muted" />
        <input type="text" placeholder="Search products..." value={search} onChange={(e) => setSearch(e.target.value)}
          className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-border text-sm focus:border-brand-500 focus:ring-1 focus:ring-brand-500 outline-none" />
      </div>

      <div className={`grid ${showPanel ? 'grid-cols-1 md:grid-cols-3' : 'grid-cols-1'} gap-6`}>
        {/* Table */}
        <div className={`${showPanel ? 'md:col-span-2' : ''} bg-surface rounded-xl border border-border overflow-hidden`}>
          {isLoading ? (
            <div className="p-12 text-center text-txt-muted">Loading...</div>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-bg-alt border-b border-border">
                <tr>
                  <th className="text-left px-5 py-3 font-medium text-txt-secondary">Product</th>
                  <th className="text-left px-5 py-3 font-medium text-txt-secondary">Strain</th>
                  <th className="text-right px-5 py-3 font-medium text-txt-secondary">Price</th>
                  <th className="text-center px-5 py-3 font-medium text-txt-secondary">Stock</th>
                  <th className="text-center px-5 py-3 font-medium text-txt-secondary">Status</th>
                  <th className="text-center px-5 py-3 font-medium text-txt-secondary">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {filtered.map((p: any) => {
                  const v = p.variants?.[0];
                  const stock = STOCK_BADGE[v?.stockStatus] ?? STOCK_BADGE.in_stock;
                  return (
                    <tr key={p.id}
                      onClick={() => openDetail(p)}
                      className={`transition-colors cursor-pointer ${selected?.id === p.id ? 'bg-brand-50' : 'hover:bg-bg-alt'}`}>
                      <td className="px-5 py-4">
                        <div className="flex items-center gap-3">
                          <div className="p-2 bg-brand-50 rounded-lg"><Package size={16} className="text-brand-600" /></div>
                          <div>
                            <p className="font-medium text-txt">{p.name}</p>
                            <p className="text-xs text-txt-muted">{v?.name} · {v?.sku}</p>
                          </div>
                        </div>
                      </td>
                      <td className="px-5 py-4">
                        {p.strainType && (
                          <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${STRAIN_BADGE[p.strainType] ?? STRAIN_BADGE.hybrid}`}>
                            {p.strainType}
                          </span>
                        )}
                        {p.thcPercent && <span className="text-xs text-txt-muted ml-2">THC {p.thcPercent}%</span>}
                      </td>
                      <td className="px-5 py-4 text-right tabular-nums font-semibold text-txt">
                        {v?.retailPrice ? `$${Number(v.retailPrice).toFixed(2)}` : '-'}
                      </td>
                      <td className="px-5 py-4 text-center">
                        <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium ${stock.cls}`}>{stock.label}</span>
                      </td>
                      <td className="px-5 py-4 text-center">
                        {p.isActive ? (
                          <span className="text-[10px] px-2 py-0.5 rounded-full font-medium bg-green-50 text-green-700">Active</span>
                        ) : (
                          <span className="text-[10px] px-2 py-0.5 rounded-full font-medium bg-gray-100 text-gray-500">Inactive</span>
                        )}
                      </td>
                      <td className="px-5 py-4 text-center">
                        <button onClick={(e) => { e.stopPropagation(); openEdit(p); }}
                          className="text-brand-600 hover:text-brand-700 p-1">
                          <Pencil size={15} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>

        {/* Side Panel */}
        {showPanel && (
          <div className="bg-surface rounded-xl border border-border p-5 space-y-5">
            <div className="flex items-center justify-between">
              <h3 className="font-semibold text-txt">
                {creating ? 'New Product' : editing ? 'Edit Product' : 'Product Details'}
              </h3>
              <button onClick={closePanel} className="text-txt-muted hover:text-txt"><X size={18} /></button>
            </div>

            {(creating || editing) ? (
              /* ── Edit / Create Form ── */
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-medium text-txt-secondary mb-1">Name *</label>
                  <input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}
                    className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-txt-secondary mb-1">Description</label>
                  <textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={3}
                    className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500 resize-none" />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-txt-secondary mb-1">Strain Type</label>
                    <select value={form.strainType} onChange={(e) => setForm({ ...form, strainType: e.target.value })}
                      className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500">
                      <option value="hybrid">Hybrid</option>
                      <option value="sativa">Sativa</option>
                      <option value="indica">Indica</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-txt-secondary mb-1">Strain Name</label>
                    <input value={form.strainName} onChange={(e) => setForm({ ...form, strainName: e.target.value })}
                      className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-txt-secondary mb-1">THC %</label>
                    <input type="number" step="0.1" value={form.thcPercent} onChange={(e) => setForm({ ...form, thcPercent: e.target.value })}
                      className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-txt-secondary mb-1">CBD %</label>
                    <input type="number" step="0.1" value={form.cbdPercent} onChange={(e) => setForm({ ...form, cbdPercent: e.target.value })}
                      className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                  </div>
                </div>

                {creating && (
                  <>
                    <div className="border-t border-border pt-4">
                      <p className="text-xs font-semibold text-txt-secondary mb-3">Default Variant</p>
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className="block text-xs font-medium text-txt-secondary mb-1">Variant Name</label>
                          <input value={form.variantName} onChange={(e) => setForm({ ...form, variantName: e.target.value })}
                            className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                        </div>
                        <div>
                          <label className="block text-xs font-medium text-txt-secondary mb-1">Weight (g)</label>
                          <input type="number" step="0.5" value={form.variantQuantityG} onChange={(e) => setForm({ ...form, variantQuantityG: e.target.value })}
                            className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                        </div>
                      </div>
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-txt-secondary mb-1">Retail Price ($)</label>
                      <input type="number" step="0.01" value={form.retailPrice} onChange={(e) => setForm({ ...form, retailPrice: e.target.value })}
                        className="w-full px-3 py-2 border border-border rounded-lg text-sm outline-none focus:border-brand-500" />
                    </div>
                  </>
                )}

                <div className="flex items-center gap-2">
                  <input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })}
                    className="rounded border-border" />
                  <span className="text-sm text-txt-secondary">Active (visible on storefront)</span>
                </div>

                <div className="flex gap-2 pt-2">
                  <button onClick={creating ? handleSaveNew : handleSaveEdit}
                    disabled={!form.name || createMut.isPending || updateMut.isPending}
                    className="flex-1 flex items-center justify-center gap-2 bg-brand-600 text-white py-2 rounded-lg text-sm font-medium hover:bg-brand-700 disabled:opacity-50 transition-colors">
                    {(createMut.isPending || updateMut.isPending) ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />}
                    {creating ? 'Create Product' : 'Save Changes'}
                  </button>
                  <button onClick={closePanel}
                    className="px-4 py-2 border border-border rounded-lg text-sm text-txt-secondary hover:bg-bg-alt">
                    Cancel
                  </button>
                </div>

                {(createMut.isError || updateMut.isError) && (
                  <p className="text-xs text-red-600">{((createMut.error || updateMut.error) as Error)?.message}</p>
                )}
              </div>
            ) : selected ? (
              /* ── Read-only Detail ── */
              <div className="space-y-4">
                <div className="flex items-center gap-3">
                  <div className="p-3 bg-brand-50 rounded-xl"><Package size={24} className="text-brand-600" /></div>
                  <div>
                    <p className="text-lg font-semibold text-txt">{selected.name}</p>
                    {selected.strainType && (
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${STRAIN_BADGE[selected.strainType] ?? ''}`}>
                        {selected.strainType}
                      </span>
                    )}
                  </div>
                </div>

                {selected.description && (
                  <p className="text-sm text-txt-secondary">{selected.description}</p>
                )}

                <div className="grid grid-cols-2 gap-3 text-sm">
                  {selected.thcPercent != null && (
                    <div className="bg-bg-alt rounded-lg p-3">
                      <p className="text-xs text-txt-muted">THC</p>
                      <p className="font-bold text-txt">{selected.thcPercent}%</p>
                    </div>
                  )}
                  {selected.cbdPercent != null && (
                    <div className="bg-bg-alt rounded-lg p-3">
                      <p className="text-xs text-txt-muted">CBD</p>
                      <p className="font-bold text-txt">{selected.cbdPercent}%</p>
                    </div>
                  )}
                </div>

                <div className="flex gap-2 text-sm">
                  {selected.isActive ? (
                    <span className="flex items-center gap-1 text-green-600"><CheckCircle size={14} /> Active</span>
                  ) : (
                    <span className="flex items-center gap-1 text-gray-500"><AlertCircle size={14} /> Inactive</span>
                  )}
                  {selected.isApproved && (
                    <span className="flex items-center gap-1 text-green-600"><CheckCircle size={14} /> Approved</span>
                  )}
                </div>

                {/* Variant & Pricing */}
                {selected.variants?.map((v: any) => (
                  <div key={v.variantId} className="border-t border-border pt-4">
                    <p className="text-xs font-semibold text-txt-secondary mb-2">Variant: {v.name}</p>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between"><span className="text-txt-secondary">SKU</span><span className="font-mono text-xs">{v.sku}</span></div>
                      <div className="flex justify-between"><span className="text-txt-secondary">Weight</span><span>{v.quantityPerUnit}g</span></div>
                      <div className="flex justify-between"><span className="text-txt-secondary">Stock</span>
                        <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${(STOCK_BADGE[v.stockStatus] ?? STOCK_BADGE.in_stock).cls}`}>
                          {v.stockQuantity ?? 0} ({(STOCK_BADGE[v.stockStatus] ?? STOCK_BADGE.in_stock).label})
                        </span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-txt-secondary">Price</span>
                        <div className="flex items-center gap-2">
                          <input type="number" step="0.01" value={priceEdit}
                            onChange={(e) => setPriceEdit(e.target.value)}
                            className="w-24 px-2 py-1 border border-border rounded text-sm text-right tabular-nums outline-none focus:border-brand-500" />
                          {priceEdit !== (v.retailPrice?.toString() ?? '') && (
                            <button onClick={handlePriceSave} disabled={priceMut.isPending}
                              className="text-brand-600 hover:text-brand-700 text-xs font-medium">
                              {priceMut.isPending ? '...' : 'Save'}
                            </button>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}

                {/* Action buttons */}
                <div className="flex gap-2 pt-3 border-t border-border">
                  <button onClick={() => openEdit(selected)}
                    className="flex-1 flex items-center justify-center gap-1.5 bg-brand-600 text-white py-2 rounded-lg text-xs font-medium hover:bg-brand-700">
                    <Pencil size={14} /> Edit
                  </button>
                  {!confirmDelete ? (
                    <button onClick={() => setConfirmDelete(true)}
                      className="flex items-center justify-center gap-1.5 text-red-600 border border-red-200 hover:bg-red-50 px-3 py-2 rounded-lg text-xs font-medium">
                      <Trash2 size={14} /> Delete
                    </button>
                  ) : (
                    <div className="flex gap-1">
                      <button onClick={() => deleteMut.mutate({ productId: selected.id, dispensaryId })}
                        disabled={deleteMut.isPending}
                        className="flex items-center gap-1 bg-red-600 text-white px-3 py-2 rounded-lg text-xs font-medium hover:bg-red-700 disabled:opacity-50">
                        {deleteMut.isPending ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />} Confirm
                      </button>
                      <button onClick={() => setConfirmDelete(false)}
                        className="px-2 py-2 border border-border rounded-lg text-xs text-txt-secondary hover:bg-bg-alt">
                        No
                      </button>
                    </div>
                  )}
                </div>
              </div>
            ) : null}
          </div>
        )}
      </div>
    </div>
  );
}

// packages/angular/projects/admin/src/app/pages/products/products-page.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { AuthService } from '../../core/auth/auth.service';
import { ProductsService, type Product, type ProductVariant } from './products.service';

type PanelMode = 'detail' | 'edit' | 'create' | null;

interface ProductFormControls {
  readonly name: FormControl<string>;
  readonly description: FormControl<string>;
  readonly strainType: FormControl<string>;
  readonly strainName: FormControl<string>;
  readonly thcPercent: FormControl<string>;
  readonly cbdPercent: FormControl<string>;
  readonly isActive: FormControl<boolean>;
  // Create-only — ignored on edit.
  readonly variantName: FormControl<string>;
  readonly variantQuantityG: FormControl<string>;
  readonly retailPrice: FormControl<string>;
}

const STRAIN_OPTIONS = ['hybrid', 'sativa', 'indica'] as const;

/**
 * Admin products list + side-panel CRUD. Mirrors the React
 * `ProductsPage`: list with search, click row → detail panel,
 * Add Product opens create form, Edit opens edit form, inline price
 * edit on the active variant, delete-with-confirm.
 *
 * Bulk operations, per-row variant drawer, and drag-to-reorder
 * are deferred — the React admin doesn't surface those either.
 */
@Component({
  selector: 'cs-products-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule],
  template: `
    <section class="space-y-6">
      <header class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-(--color-text)">
          Products ({{ filteredProducts().length }})
        </h1>
        <button
          type="button"
          (click)="onAdd()"
          class="rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover)"
        >
          + Add product
        </button>
      </header>

      <div class="relative max-w-md">
        <input
          type="text"
          [value]="search()"
          (input)="onSearchInput($event)"
          placeholder="Search products…"
          aria-label="Search products"
          class="w-full rounded-lg border border-(--color-border) bg-(--color-surface) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
        />
      </div>

      <div class="grid grid-cols-1 gap-6" [class.md:grid-cols-3]="showPanel()">
        <div
          class="overflow-hidden rounded-xl border border-(--color-border) bg-(--color-surface)"
          [class.md:col-span-2]="showPanel()"
        >
          @if (isLoading()) {
            <p class="p-12 text-center text-sm text-(--color-text-muted)">Loading…</p>
          } @else if (error(); as err) {
            <div class="p-6 text-rose-300" role="alert">
              <h2 class="font-semibold">Failed to load products</h2>
              <p class="mt-1 text-sm">{{ productsErrorMessage() }}</p>
            </div>
          } @else if (filteredProducts().length === 0) {
            <p class="p-12 text-center text-sm text-(--color-text-muted)">
              No products match this search.
            </p>
          } @else {
            <table class="w-full text-sm">
              <thead class="border-b border-(--color-border) bg-(--color-bg)">
                <tr>
                  <th class="px-5 py-3 text-left font-medium text-(--color-text-secondary)">
                    Product
                  </th>
                  <th class="px-5 py-3 text-left font-medium text-(--color-text-secondary)">
                    Strain
                  </th>
                  <th class="px-5 py-3 text-right font-medium text-(--color-text-secondary)">
                    Price
                  </th>
                  <th class="px-5 py-3 text-center font-medium text-(--color-text-secondary)">
                    Stock
                  </th>
                  <th class="px-5 py-3 text-center font-medium text-(--color-text-secondary)">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody class="divide-y divide-(--color-border)">
                @for (p of filteredProducts(); track p.id) {
                  <tr
                    class="cursor-pointer transition-colors"
                    [class]="
                      selectedId() === p.id
                        ? 'bg-(--color-primary)/10'
                        : 'hover:bg-(--color-surface-hover)'
                    "
                    (click)="onSelect(p)"
                  >
                    <td class="px-5 py-4">
                      <p class="font-medium text-(--color-text)">{{ p.name }}</p>
                      @if (firstVariant(p); as v) {
                        <p class="text-xs text-(--color-text-muted)">{{ v.name }} · {{ v.sku }}</p>
                      }
                    </td>
                    <td class="px-5 py-4">
                      @if (p.strainType) {
                        <span
                          class="rounded-full px-2 py-0.5 text-xs font-medium"
                          [class]="strainBadgeClass(p.strainType)"
                        >
                          {{ p.strainType }}
                        </span>
                      }
                      @if (p.thcPercent != null) {
                        <span class="ml-2 text-xs text-(--color-text-muted)">
                          THC {{ p.thcPercent }}%
                        </span>
                      }
                    </td>
                    <td class="px-5 py-4 text-right font-semibold tabular-nums text-(--color-text)">
                      @if (firstVariant(p); as v) {
                        {{ formatMoney(v.retailPrice) }}
                      } @else {
                        —
                      }
                    </td>
                    <td class="px-5 py-4 text-center">
                      @if (firstVariant(p); as v) {
                        <span
                          class="rounded-full px-2 py-0.5 text-[10px] font-medium"
                          [class]="stockBadgeClass(v.stockStatus)"
                        >
                          {{ stockLabel(v.stockStatus) }}
                        </span>
                      }
                    </td>
                    <td class="px-5 py-4 text-center">
                      @if (p.isActive) {
                        <span
                          class="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-500"
                        >
                          Active
                        </span>
                      } @else {
                        <span
                          class="rounded-full bg-(--color-surface-hover) px-2 py-0.5 text-[10px] font-medium text-(--color-text-muted)"
                        >
                          Inactive
                        </span>
                      }
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          }
        </div>

        @if (showPanel()) {
          <aside
            class="space-y-5 rounded-xl border border-(--color-border) bg-(--color-surface) p-5"
          >
            <header class="flex items-center justify-between">
              <h3 class="font-semibold text-(--color-text)">
                {{ panelTitle() }}
              </h3>
              <button
                type="button"
                (click)="closePanel()"
                class="text-(--color-text-muted) hover:text-(--color-text)"
                aria-label="Close panel"
              >
                ✕
              </button>
            </header>

            @if (panelMode() === 'create' || panelMode() === 'edit') {
              <form
                [formGroup]="form"
                (ngSubmit)="onSubmitForm()"
                class="space-y-4"
                [attr.aria-label]="panelMode() === 'create' ? 'Create product' : 'Edit product'"
              >
                <label class="block">
                  <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                    Name *
                  </span>
                  <input
                    type="text"
                    formControlName="name"
                    class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                  />
                </label>

                <label class="block">
                  <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                    Description
                  </span>
                  <textarea
                    formControlName="description"
                    rows="3"
                    class="w-full resize-none rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                  ></textarea>
                </label>

                <div class="grid grid-cols-2 gap-3">
                  <label class="block">
                    <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                      Strain type
                    </span>
                    <select
                      formControlName="strainType"
                      class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                    >
                      @for (s of strainOptions; track s) {
                        <option [value]="s">{{ s }}</option>
                      }
                    </select>
                  </label>
                  <label class="block">
                    <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                      Strain name
                    </span>
                    <input
                      type="text"
                      formControlName="strainName"
                      class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                    />
                  </label>
                </div>

                <div class="grid grid-cols-2 gap-3">
                  <label class="block">
                    <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                      THC %
                    </span>
                    <input
                      type="number"
                      step="0.1"
                      formControlName="thcPercent"
                      class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                    />
                  </label>
                  <label class="block">
                    <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                      CBD %
                    </span>
                    <input
                      type="number"
                      step="0.1"
                      formControlName="cbdPercent"
                      class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                    />
                  </label>
                </div>

                @if (panelMode() === 'create') {
                  <div class="space-y-3 border-t border-(--color-border) pt-4">
                    <p class="text-xs font-semibold text-(--color-text-secondary)">
                      Default variant
                    </p>
                    <div class="grid grid-cols-2 gap-3">
                      <label class="block">
                        <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                          Variant name
                        </span>
                        <input
                          type="text"
                          formControlName="variantName"
                          class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                        />
                      </label>
                      <label class="block">
                        <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                          Weight (g)
                        </span>
                        <input
                          type="number"
                          step="0.5"
                          formControlName="variantQuantityG"
                          class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                        />
                      </label>
                    </div>
                    <label class="block">
                      <span class="mb-1 block text-xs font-medium text-(--color-text-secondary)">
                        Retail price ($)
                      </span>
                      <input
                        type="number"
                        step="0.01"
                        formControlName="retailPrice"
                        class="w-full rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                      />
                    </label>
                  </div>
                }

                <label class="flex items-center gap-2">
                  <input
                    type="checkbox"
                    formControlName="isActive"
                    class="rounded border-(--color-border)"
                  />
                  <span class="text-sm text-(--color-text-secondary)">
                    Active (visible on storefront)
                  </span>
                </label>

                <div class="flex gap-2 pt-2">
                  <button
                    type="submit"
                    [disabled]="form.invalid || saving()"
                    class="flex-1 rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover) disabled:opacity-50"
                  >
                    @if (saving()) {
                      Saving…
                    } @else if (panelMode() === 'create') {
                      Create product
                    } @else {
                      Save changes
                    }
                  </button>
                  <button
                    type="button"
                    (click)="closePanel()"
                    class="rounded-lg border border-(--color-border) px-4 py-2 text-sm text-(--color-text-secondary) hover:text-(--color-text)"
                  >
                    Cancel
                  </button>
                </div>
              </form>
            } @else if (selected(); as p) {
              <div class="space-y-4">
                <div>
                  <p class="text-lg font-semibold text-(--color-text)">{{ p.name }}</p>
                  @if (p.strainType) {
                    <span
                      class="mt-1 inline-block rounded-full px-2 py-0.5 text-xs font-medium"
                      [class]="strainBadgeClass(p.strainType)"
                    >
                      {{ p.strainType }}
                    </span>
                  }
                </div>

                @if (p.description) {
                  <p class="text-sm text-(--color-text-secondary)">{{ p.description }}</p>
                }

                <div class="grid grid-cols-2 gap-3 text-sm">
                  @if (p.thcPercent != null) {
                    <div class="rounded-lg bg-(--color-bg) p-3">
                      <p class="text-xs text-(--color-text-muted)">THC</p>
                      <p class="font-bold text-(--color-text)">{{ p.thcPercent }}%</p>
                    </div>
                  }
                  @if (p.cbdPercent != null) {
                    <div class="rounded-lg bg-(--color-bg) p-3">
                      <p class="text-xs text-(--color-text-muted)">CBD</p>
                      <p class="font-bold text-(--color-text)">{{ p.cbdPercent }}%</p>
                    </div>
                  }
                </div>

                <div class="flex gap-2 text-sm">
                  @if (p.isActive) {
                    <span class="text-emerald-500">● Active</span>
                  } @else {
                    <span class="text-(--color-text-muted)">○ Inactive</span>
                  }
                  @if (p.isApproved) {
                    <span class="text-emerald-500">● Approved</span>
                  }
                </div>

                @for (v of p.variants; track v.variantId) {
                  <div class="space-y-2 border-t border-(--color-border) pt-4 text-sm">
                    <p class="text-xs font-semibold text-(--color-text-secondary)">
                      Variant: {{ v.name }}
                    </p>
                    <div class="flex justify-between">
                      <span class="text-(--color-text-secondary)">SKU</span>
                      <span class="font-mono text-xs text-(--color-text)">{{ v.sku }}</span>
                    </div>
                    @if (v.quantityPerUnit != null) {
                      <div class="flex justify-between">
                        <span class="text-(--color-text-secondary)">Weight</span>
                        <span class="text-(--color-text)">{{ v.quantityPerUnit }}g</span>
                      </div>
                    }
                    <div class="flex justify-between">
                      <span class="text-(--color-text-secondary)">Stock</span>
                      <span
                        class="rounded-full px-2 py-0.5 text-xs font-medium"
                        [class]="stockBadgeClass(v.stockStatus)"
                      >
                        {{ v.stockQuantity ?? 0 }} ({{ stockLabel(v.stockStatus) }})
                      </span>
                    </div>
                    <div class="flex items-center justify-between">
                      <span class="text-(--color-text-secondary)">Price</span>
                      <div class="flex items-center gap-2">
                        <input
                          type="number"
                          step="0.01"
                          [value]="priceEdit()"
                          (input)="onPriceEditInput($event)"
                          [attr.aria-label]="'Price for ' + v.name"
                          class="w-24 rounded border border-(--color-border) bg-(--color-bg) px-2 py-1 text-right text-sm tabular-nums text-(--color-text) focus:border-(--color-primary) focus:outline-none"
                        />
                        @if (canSavePrice(v)) {
                          <button
                            type="button"
                            (click)="onSavePrice(v)"
                            [disabled]="savingPrice()"
                            class="text-xs font-medium text-(--color-primary) hover:text-(--color-primary-hover) disabled:opacity-50"
                            [attr.aria-label]="'Save price for ' + v.name"
                          >
                            @if (savingPrice()) {
                              …
                            } @else {
                              Save
                            }
                          </button>
                        }
                      </div>
                    </div>
                  </div>
                }

                <div class="flex gap-2 border-t border-(--color-border) pt-3">
                  <button
                    type="button"
                    (click)="onEdit(p)"
                    class="flex-1 rounded-lg bg-(--color-primary) px-3 py-2 text-xs font-medium text-white hover:bg-(--color-primary-hover)"
                  >
                    Edit
                  </button>
                  @if (!confirmDelete()) {
                    <button
                      type="button"
                      (click)="openDeleteConfirm()"
                      class="rounded-lg border border-rose-500/30 px-3 py-2 text-xs font-medium text-rose-500 hover:bg-rose-500/10"
                    >
                      Delete
                    </button>
                  } @else {
                    <button
                      type="button"
                      (click)="onConfirmDelete(p)"
                      [disabled]="deleting()"
                      class="rounded-lg bg-rose-600 px-3 py-2 text-xs font-medium text-white hover:bg-rose-500 disabled:opacity-50"
                      [attr.aria-label]="'Confirm delete ' + p.name"
                    >
                      @if (deleting()) {
                        Deleting…
                      } @else {
                        Confirm delete
                      }
                    </button>
                    <button
                      type="button"
                      (click)="closeDeleteConfirm()"
                      class="rounded-lg border border-(--color-border) px-3 py-2 text-xs text-(--color-text-secondary) hover:text-(--color-text)"
                    >
                      No
                    </button>
                  }
                </div>
              </div>
            }
          </aside>
        }
      </div>
    </section>
  `,
})
export class ProductsPage {
  private readonly svc = inject(ProductsService);
  private readonly auth = inject(AuthService);

  protected readonly strainOptions = STRAIN_OPTIONS;

  protected readonly filteredProducts = this.svc.filteredProducts;
  protected readonly isLoading = this.svc.isLoading;
  protected readonly error = this.svc.error;
  protected readonly saving = this.svc.saving;
  protected readonly savingPrice = this.svc.savingPrice;
  protected readonly deleting = this.svc.deleting;
  protected readonly search = this.svc.search;

  protected readonly selected = signal<Product | null>(null);
  protected readonly panelMode = signal<PanelMode>(null);
  protected readonly priceEdit = signal<string>('');
  protected readonly confirmDelete = signal<boolean>(false);

  protected readonly selectedId = computed(() => this.selected()?.id ?? null);
  protected readonly showPanel = computed(() => this.panelMode() !== null);

  protected readonly panelTitle = computed(() => {
    switch (this.panelMode()) {
      case 'create':
        return 'New product';
      case 'edit':
        return 'Edit product';
      case 'detail':
        return 'Product details';
      default:
        return '';
    }
  });

  protected readonly productsErrorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load products.';
  });

  /* eslint-disable @typescript-eslint/unbound-method --
   * Validators.* are pure functions; the unbound-method rule's
   * `this:void` warning is a false positive for these references.
   */
  protected readonly form = new FormGroup<ProductFormControls>({
    name: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    description: new FormControl('', { nonNullable: true }),
    strainType: new FormControl('hybrid', { nonNullable: true }),
    strainName: new FormControl('', { nonNullable: true }),
    thcPercent: new FormControl('', { nonNullable: true }),
    cbdPercent: new FormControl('', { nonNullable: true }),
    isActive: new FormControl(true, { nonNullable: true }),
    variantName: new FormControl('3.5g Jar', { nonNullable: true }),
    variantQuantityG: new FormControl('3.5', { nonNullable: true }),
    retailPrice: new FormControl('', { nonNullable: true }),
  });
  /* eslint-enable @typescript-eslint/unbound-method */

  protected onSearchInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.svc.setSearch(value);
  }

  protected onSelect(product: Product): void {
    if (this.panelMode() === 'create' || this.panelMode() === 'edit') return;
    this.selected.set(product);
    this.panelMode.set('detail');
    this.confirmDelete.set(false);
    this.priceEdit.set(this.firstVariant(product)?.retailPrice?.toString() ?? '');
  }

  protected onAdd(): void {
    this.selected.set(null);
    this.panelMode.set('create');
    this.confirmDelete.set(false);
    this.form.reset({
      name: '',
      description: '',
      strainType: 'hybrid',
      strainName: '',
      thcPercent: '',
      cbdPercent: '',
      isActive: true,
      variantName: '3.5g Jar',
      variantQuantityG: '3.5',
      retailPrice: '',
    });
  }

  protected onEdit(product: Product): void {
    this.selected.set(product);
    this.panelMode.set('edit');
    this.confirmDelete.set(false);
    const v = this.firstVariant(product);
    this.form.reset({
      name: product.name,
      description: product.description ?? '',
      strainType: product.strainType ?? 'hybrid',
      strainName: product.strainName ?? '',
      thcPercent: product.thcPercent?.toString() ?? '',
      cbdPercent: product.cbdPercent?.toString() ?? '',
      isActive: product.isActive,
      variantName: v?.name ?? '',
      variantQuantityG: v?.quantityPerUnit?.toString() ?? '',
      retailPrice: v?.retailPrice?.toString() ?? '',
    });
    this.priceEdit.set(v?.retailPrice?.toString() ?? '');
  }

  protected closePanel(): void {
    this.selected.set(null);
    this.panelMode.set(null);
    this.confirmDelete.set(false);
  }

  protected openDeleteConfirm(): void {
    this.confirmDelete.set(true);
  }

  protected closeDeleteConfirm(): void {
    this.confirmDelete.set(false);
  }

  protected onPriceEditInput(event: Event): void {
    this.priceEdit.set((event.target as HTMLInputElement).value);
  }

  protected canSavePrice(variant: ProductVariant): boolean {
    const current = variant.retailPrice?.toString() ?? '';
    const edit = this.priceEdit();
    return edit !== '' && edit !== current;
  }

  protected async onSavePrice(variant: ProductVariant): Promise<void> {
    const dispensaryId = this.auth.user()?.dispensaryId;
    const price = parseFloat(this.priceEdit());
    if (!dispensaryId || Number.isNaN(price)) return;
    await this.svc.updateVariantPrice({ variantId: variant.variantId, dispensaryId, price });
  }

  protected async onSubmitForm(): Promise<void> {
    if (this.form.invalid) return;
    const dispensaryId = this.auth.user()?.dispensaryId;
    if (!dispensaryId) return;
    const v = this.form.getRawValue();
    if (this.panelMode() === 'create') {
      await this.svc.create({
        dispensaryId,
        name: v.name,
        description: v.description || undefined,
        strainType: v.strainType || undefined,
        strainName: v.strainName || undefined,
        thcPercent: v.thcPercent ? parseFloat(v.thcPercent) : undefined,
        cbdPercent: v.cbdPercent ? parseFloat(v.cbdPercent) : undefined,
        isActive: v.isActive,
        variantName: v.variantName || undefined,
        variantQuantityG: v.variantQuantityG ? parseFloat(v.variantQuantityG) : undefined,
        retailPrice: v.retailPrice ? parseFloat(v.retailPrice) : undefined,
      });
      this.closePanel();
    } else if (this.panelMode() === 'edit') {
      const productId = this.selected()?.id;
      if (!productId) return;
      await this.svc.update({
        productId,
        dispensaryId,
        name: v.name,
        description: v.description || undefined,
        strainType: v.strainType || undefined,
        strainName: v.strainName || undefined,
        thcPercent: v.thcPercent ? parseFloat(v.thcPercent) : undefined,
        cbdPercent: v.cbdPercent ? parseFloat(v.cbdPercent) : undefined,
        isActive: v.isActive,
      });
      this.closePanel();
    }
  }

  protected async onConfirmDelete(product: Product): Promise<void> {
    const dispensaryId = this.auth.user()?.dispensaryId;
    if (!dispensaryId) return;
    await this.svc.deleteProduct(product.id, dispensaryId);
    this.closePanel();
  }

  protected firstVariant(p: Product): ProductVariant | undefined {
    return p.variants[0];
  }

  protected formatMoney(value: number | null | undefined): string {
    if (value == null) return '—';
    return (
      '$' +
      value.toLocaleString('en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })
    );
  }

  protected stockLabel(status: string | null | undefined): string {
    switch (status) {
      case 'in_stock':
        return 'In Stock';
      case 'low_stock':
        return 'Low Stock';
      case 'out_of_stock':
        return 'Sold Out';
      default:
        return 'Unknown';
    }
  }

  protected stockBadgeClass(status: string | null | undefined): string {
    switch (status) {
      case 'in_stock':
        return 'bg-emerald-500/10 text-emerald-500';
      case 'low_stock':
        return 'bg-amber-500/10 text-amber-500';
      case 'out_of_stock':
        return 'bg-rose-500/10 text-rose-500';
      default:
        return 'bg-(--color-surface-hover) text-(--color-text-secondary)';
    }
  }

  protected strainBadgeClass(strain: string | null | undefined): string {
    switch (strain) {
      case 'sativa':
        return 'bg-orange-500/10 text-orange-500';
      case 'indica':
        return 'bg-purple-500/10 text-purple-500';
      case 'hybrid':
      default:
        return 'bg-emerald-500/10 text-emerald-500';
    }
  }
}
