// apps/staff/src/pages/ProductLookupPage.tsx
import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { Search, Leaf } from 'lucide-react';

const SEARCH_QUERY = `
  query($input: ProductSearchInput!) {
    searchProducts(input: $input) {
      total
      products { id name strainName strainType description thcPercent cbdPercent effects flavors }
    }
  }
`;

const STRAIN_COLORS: Record<string, string> = {
  sativa: 'bg-orange-100 text-orange-700',
  indica: 'bg-purple-100 text-purple-700',
  hybrid: 'bg-green-100 text-green-700',
};

export function ProductLookupPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const [search, setSearch] = useState('');
  const [debounced, setDebounced] = useState('');

  const handleChange = (val: string) => {
    setSearch(val);
    clearTimeout((window as any).__pTimeout);
    (window as any).__pTimeout = setTimeout(() => setDebounced(val), 250);
  };

  const { data, isLoading } = useQuery({
    queryKey: ['productLookup', dispensaryId, debounced],
    queryFn: () => gqlRequest<{ searchProducts: any }>(SEARCH_QUERY, {
      input: { dispensaryId, search: debounced || undefined, limit: 20 },
    }),
    select: (d) => d.searchProducts,
    enabled: !!dispensaryId,
  });

  const products = data?.products ?? [];

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Product Lookup</h1>

      <div className="relative max-w-xl">
        <Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
        <input
          type="text"
          placeholder="Search by name, strain, effects..."
          value={search}
          onChange={(e) => handleChange(e.target.value)}
          autoFocus
          className="w-full pl-11 pr-4 py-3 rounded-xl border border-gray-200 text-sm focus:border-brand-500 focus:ring-1 focus:ring-brand-500 outline-none bg-white"
        />
      </div>

      {isLoading ? (
        <div className="text-gray-400 text-sm">Searching...</div>
      ) : products.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {products.map((p: any) => (
            <div key={p.id} className="bg-white rounded-xl border border-gray-100 p-5 hover:shadow-sm transition-shadow">
              <div className="flex items-start gap-3">
                <div className="p-2 bg-brand-50 rounded-lg shrink-0">
                  <Leaf size={20} className="text-brand-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold text-gray-900">{p.name}</h3>
                    {p.strainType && (
                      <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${STRAIN_COLORS[p.strainType] ?? STRAIN_COLORS.hybrid}`}>
                        {p.strainType}
                      </span>
                    )}
                  </div>

                  {p.strainName && p.strainName !== p.name && (
                    <p className="text-xs text-gray-500 mt-0.5">Strain: {p.strainName}</p>
                  )}

                  <div className="flex gap-4 mt-2 text-xs text-gray-600">
                    {p.thcPercent && <span className="font-medium">THC: {p.thcPercent}%</span>}
                    {p.cbdPercent && <span className="font-medium">CBD: {p.cbdPercent}%</span>}
                  </div>

                  {p.effects?.length > 0 && (
                    <div className="flex flex-wrap gap-1 mt-2">
                      {p.effects.map((e: string) => (
                        <span key={e} className="text-[10px] bg-brand-50 text-brand-700 px-2 py-0.5 rounded-full">{e}</span>
                      ))}
                    </div>
                  )}

                  {p.flavors?.length > 0 && (
                    <div className="flex flex-wrap gap-1 mt-1">
                      {p.flavors.map((f: string) => (
                        <span key={f} className="text-[10px] bg-amber-50 text-amber-700 px-2 py-0.5 rounded-full">{f}</span>
                      ))}
                    </div>
                  )}

                  {p.description && (
                    <p className="text-xs text-gray-400 mt-2 line-clamp-2">{p.description}</p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : debounced ? (
        <div className="text-center py-12 text-gray-400">
          <p>No products found for "{debounced}"</p>
        </div>
      ) : (
        <div className="text-center py-12 text-gray-400">
          <p>Start typing to search products</p>
        </div>
      )}
    </div>
  );
}

// packages/angular/projects/staff/src/app/features/product-lookup/product-lookup-page.ts
import { ChangeDetectionStrategy, Component, effect, inject, signal } from '@angular/core';
import { toObservable, toSignal } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged } from 'rxjs';
import { SearchProductsLookupGQL } from '@cannasaas/ui-ng';
import { AuthService } from '../../core/auth/auth.service';

interface ProductHit {
  readonly productId: string;
  readonly name: string;
  readonly strainType: string | null;
  readonly thcPercent: number | null;
  readonly cbdPercent: number | null;
  readonly effects: readonly string[] | null;
  readonly flavors: readonly string[] | null;
}

@Component({
  selector: 'cs-product-lookup-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
  template: `
    <header class="mb-6">
      <h1 class="text-2xl font-bold">Product Lookup</h1>
    </header>

    <div class="mb-6 max-w-xl">
      <input
        type="text"
        autofocus
        placeholder="Search by name, strain, effects…"
        class="min-h-11 w-full rounded-xl border border-(--color-border) bg-(--color-surface) px-4 py-3 text-sm"
        [ngModel]="search()"
        (ngModelChange)="search.set($event)"
      />
    </div>

    @if (loading()) {
      <p class="text-sm text-(--color-text-muted)">Searching…</p>
    } @else if (results().length > 0) {
      <ul class="grid grid-cols-1 gap-4 md:grid-cols-2">
        @for (p of results(); track p.productId) {
          <li class="rounded-xl border border-(--color-border) bg-(--color-surface) p-5">
            <div class="flex items-center gap-2">
              <h3 class="font-semibold">{{ p.name }}</h3>
              @if (p.strainType) {
                <span
                  class="rounded-full bg-(--color-surface-alt) px-2 py-0.5 text-[10px] font-semibold uppercase"
                >
                  {{ p.strainType }}
                </span>
              }
            </div>
            <div class="mt-2 flex gap-4 text-xs text-(--color-text-muted)">
              @if (p.thcPercent != null) {
                <span class="font-medium">THC: {{ p.thcPercent }}%</span>
              }
              @if (p.cbdPercent != null) {
                <span class="font-medium">CBD: {{ p.cbdPercent }}%</span>
              }
            </div>
            @if ((p.effects?.length ?? 0) > 0) {
              <div class="mt-2 flex flex-wrap gap-1">
                @for (e of p.effects ?? []; track e) {
                  <span
                    class="rounded-full bg-(--color-primary-xlight) px-2 py-0.5 text-[10px] text-(--color-primary)"
                  >
                    {{ e }}
                  </span>
                }
              </div>
            }
            @if ((p.flavors?.length ?? 0) > 0) {
              <div class="mt-1 flex flex-wrap gap-1">
                @for (f of p.flavors ?? []; track f) {
                  <span class="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] text-amber-700">
                    {{ f }}
                  </span>
                }
              </div>
            }
          </li>
        }
      </ul>
    } @else if (debouncedSearch().length > 0) {
      <p class="py-12 text-center text-sm text-(--color-text-muted)">
        No products found for "{{ debouncedSearch() }}"
      </p>
    } @else {
      <p class="py-12 text-center text-sm text-(--color-text-muted)">
        Start typing to search products
      </p>
    }
  `,
})
export class ProductLookupPage {
  private readonly auth = inject(AuthService);
  private readonly searchGQL = inject(SearchProductsLookupGQL);

  protected readonly search = signal('');
  protected readonly results = signal<readonly ProductHit[]>([]);
  protected readonly loading = signal(false);

  protected readonly debouncedSearch = toSignal(
    toObservable(this.search).pipe(debounceTime(250), distinctUntilChanged()),
    { initialValue: '' },
  );

  constructor() {
    effect(() => {
      const id = this.auth.user()?.dispensaryId;
      const q = this.debouncedSearch();
      if (!id || !q) {
        this.results.set([]);
        return;
      }
      void this.runSearch(id, q);
    });
  }

  private async runSearch(dispensaryId: string, query: string): Promise<void> {
    this.loading.set(true);
    try {
      const result = await this.searchGQL
        .fetch({
          variables: { dispensaryId, query, limit: 20 },
          fetchPolicy: 'network-only',
        })
        .toPromise();
      const rows = (result?.data?.searchProducts ?? []) as unknown as ProductHit[];
      this.results.set(rows);
    } catch {
      this.results.set([]);
    } finally {
      this.loading.set(false);
    }
  }
}
