// packages/angular/projects/staff/src/app/features/fulfillment/fulfillment-page.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { AvailableTimeSlotsGQL, DeliveryZonesForFulfillmentGQL } from '@cannasaas/ui-ng';
import { AuthService } from '../../core/auth/auth.service';

interface DeliveryZone {
  readonly zoneId: string;
  readonly name: string;
  readonly radiusMiles: number;
  readonly deliveryFee: number;
  readonly minOrderAmount: number;
  readonly freeDeliveryThreshold: number | null;
}

interface TimeSlot {
  readonly slotId: string;
  readonly startTime: string;
  readonly endTime: string;
  readonly spotsRemaining: number;
}

function tomorrowYmd(): string {
  const t = new Date();
  t.setDate(t.getDate() + 1);
  return t.toISOString().split('T')[0] ?? '';
}

@Component({
  selector: 'cs-fulfillment-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <header class="mb-6">
      <h1 class="text-2xl font-bold">Fulfillment</h1>
    </header>

    <section class="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">
      <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
        <p class="text-lg font-bold">{{ zones().length }}</p>
        <p class="text-xs text-(--color-text-muted)">Delivery Zones</p>
      </div>
      <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
        <p class="text-lg font-bold">{{ maxRadius() }} mi</p>
        <p class="text-xs text-(--color-text-muted)">Max Radius</p>
      </div>
      <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
        <p class="text-lg font-bold">{{ pickupSlots().length }}</p>
        <p class="text-xs text-(--color-text-muted)">Pickup Slots ({{ dateLabel }})</p>
      </div>
      <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
        <p class="text-lg font-bold">{{ deliverySlots().length }}</p>
        <p class="text-xs text-(--color-text-muted)">Delivery Slots ({{ dateLabel }})</p>
      </div>
    </section>

    <section class="mb-6 rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
      <h2 class="mb-4 text-lg font-semibold">Delivery Zones</h2>
      @if (zones().length === 0) {
        <p class="text-sm text-(--color-text-muted)">No delivery zones configured</p>
      } @else {
        <ul class="grid grid-cols-1 gap-3 md:grid-cols-3">
          @for (z of zones(); track z.zoneId) {
            <li class="rounded-lg border border-(--color-border) p-4">
              <h3 class="font-medium">{{ z.name }}</h3>
              <p class="mt-1 space-y-0.5 text-sm text-(--color-text-muted)">
                <span class="block">Radius: {{ z.radiusMiles }} mi</span>
                <span class="block">
                  Fee: {{ z.deliveryFee > 0 ? '$' + z.deliveryFee : 'Free' }}
                </span>
                <span class="block">Min order: \${{ z.minOrderAmount }}</span>
                @if (z.freeDeliveryThreshold) {
                  <span class="block">Free above: \${{ z.freeDeliveryThreshold }}</span>
                }
              </p>
            </li>
          }
        </ul>
      }
    </section>

    <section class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
        <h2 class="mb-3 text-lg font-semibold">Pickup Slots — {{ dateLabel }}</h2>
        @if (pickupSlots().length === 0) {
          <p class="text-sm text-(--color-text-muted)">No pickup slots</p>
        } @else {
          <ul class="space-y-2">
            @for (s of pickupSlots(); track s.slotId) {
              <li
                class="flex items-center justify-between rounded-lg bg-(--color-surface-alt) p-3 text-sm"
              >
                <span class="font-medium">
                  {{ s.startTime.slice(0, 5) }} - {{ s.endTime.slice(0, 5) }}
                </span>
                <span
                  class="text-xs font-semibold"
                  [class.text-rose-600]="s.spotsRemaining <= 2"
                  [class.text-emerald-600]="s.spotsRemaining > 2"
                >
                  {{ s.spotsRemaining }} spots
                </span>
              </li>
            }
          </ul>
        }
      </div>
      <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
        <h2 class="mb-3 text-lg font-semibold">Delivery Slots — {{ dateLabel }}</h2>
        @if (deliverySlots().length === 0) {
          <p class="text-sm text-(--color-text-muted)">No delivery slots</p>
        } @else {
          <ul class="space-y-2">
            @for (s of deliverySlots(); track s.slotId) {
              <li
                class="flex items-center justify-between rounded-lg bg-(--color-surface-alt) p-3 text-sm"
              >
                <span class="font-medium">
                  {{ s.startTime.slice(0, 5) }} - {{ s.endTime.slice(0, 5) }}
                </span>
                <span
                  class="text-xs font-semibold"
                  [class.text-rose-600]="s.spotsRemaining <= 1"
                  [class.text-emerald-600]="s.spotsRemaining > 1"
                >
                  {{ s.spotsRemaining }} spots
                </span>
              </li>
            }
          </ul>
        }
      </div>
    </section>
  `,
})
export class FulfillmentPage {
  private readonly auth = inject(AuthService);
  private readonly zonesGQL = inject(DeliveryZonesForFulfillmentGQL);
  private readonly slotsGQL = inject(AvailableTimeSlotsGQL);

  protected readonly dateLabel = tomorrowYmd();
  protected readonly zones = signal<readonly DeliveryZone[]>([]);
  protected readonly pickupSlots = signal<readonly TimeSlot[]>([]);
  protected readonly deliverySlots = signal<readonly TimeSlot[]>([]);

  protected readonly maxRadius = computed(() =>
    this.zones().length > 0 ? Math.max(...this.zones().map((z) => z.radiusMiles)) : 0,
  );

  constructor() {
    effect(() => {
      const id = this.auth.user()?.dispensaryId;
      if (!id) return;
      void this.loadZones(id);
      void this.loadSlots(id, 'pickup', this.dateLabel).then((s) => this.pickupSlots.set(s));
      void this.loadSlots(id, 'delivery', this.dateLabel).then((s) => this.deliverySlots.set(s));
    });
  }

  private async loadZones(dispensaryId: string): Promise<void> {
    try {
      const result = await this.zonesGQL
        .fetch({
          variables: { dispensaryId },
          fetchPolicy: 'network-only',
        })
        .toPromise();
      this.zones.set((result?.data?.deliveryZones ?? []) as unknown as DeliveryZone[]);
    } catch {
      this.zones.set([]);
    }
  }

  private async loadSlots(
    dispensaryId: string,
    slotType: 'pickup' | 'delivery',
    date: string,
  ): Promise<readonly TimeSlot[]> {
    try {
      const result = await this.slotsGQL
        .fetch({
          variables: { dispensaryId, slotType, date },
          fetchPolicy: 'network-only',
        })
        .toPromise();
      return (result?.data?.availableTimeSlots ?? []) as unknown as TimeSlot[];
    } catch {
      return [];
    }
  }
}

// apps/staff/src/pages/FulfillmentPage.tsx
import { useQuery } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { Truck, Store, Clock, MapPin } from 'lucide-react';

export function FulfillmentPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);

  const { data: zones } = useQuery({
    queryKey: ['deliveryZones', dispensaryId],
    queryFn: () => gqlRequest<{ deliveryZones: any[] }>(`
      query($id: ID!) { deliveryZones(dispensaryId: $id) { zoneId name radiusMiles deliveryFee minOrderAmount freeDeliveryThreshold } }
    `, { id: dispensaryId }),
    select: (d) => d.deliveryZones,
  });

  const { data: dashboard } = useQuery({
    queryKey: ['fulfillmentDashboard'],
    queryFn: () => gqlRequest<{ dashboard: any }>(`
      query { dashboard(days: 1) { sales { completedOrders pendingOrders } } }
    `),
    select: (d) => d.dashboard,
  });

  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  const dateStr = tomorrow.toISOString().split('T')[0];

  const { data: pickupSlots } = useQuery({
    queryKey: ['pickupSlots', dispensaryId, dateStr],
    queryFn: () => gqlRequest<{ availableTimeSlots: any[] }>(`
      query($id: ID!, $type: String!, $date: String!) {
        availableTimeSlots(dispensaryId: $id, slotType: $type, date: $date) { slotId startTime endTime spotsRemaining }
      }
    `, { id: dispensaryId, type: 'pickup', date: dateStr }),
    select: (d) => d.availableTimeSlots,
  });

  const { data: deliverySlots } = useQuery({
    queryKey: ['deliverySlots', dispensaryId, dateStr],
    queryFn: () => gqlRequest<{ availableTimeSlots: any[] }>(`
      query($id: ID!, $type: String!, $date: String!) {
        availableTimeSlots(dispensaryId: $id, slotType: $type, date: $date) { slotId startTime endTime spotsRemaining }
      }
    `, { id: dispensaryId, type: 'delivery', date: dateStr }),
    select: (d) => d.availableTimeSlots,
  });

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Fulfillment</h1>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div className="bg-white rounded-xl border border-gray-100 p-4 flex items-center gap-3">
          <Store size={20} className="text-brand-600" />
          <div>
            <p className="text-lg font-bold">{dashboard?.sales?.completedOrders ?? 0}</p>
            <p className="text-xs text-gray-500">Completed Today</p>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-gray-100 p-4 flex items-center gap-3">
          <Clock size={20} className="text-amber-500" />
          <div>
            <p className="text-lg font-bold">{dashboard?.sales?.pendingOrders ?? 0}</p>
            <p className="text-xs text-gray-500">Pending</p>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-gray-100 p-4 flex items-center gap-3">
          <Truck size={20} className="text-indigo-500" />
          <div>
            <p className="text-lg font-bold">{zones?.length ?? 0}</p>
            <p className="text-xs text-gray-500">Delivery Zones</p>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-gray-100 p-4 flex items-center gap-3">
          <MapPin size={20} className="text-red-500" />
          <div>
            <p className="text-lg font-bold">{zones ? Math.max(...zones.map((z: any) => z.radiusMiles)) : 0} mi</p>
            <p className="text-xs text-gray-500">Max Radius</p>
          </div>
        </div>
      </div>

      {/* Delivery Zones */}
      <div className="bg-white rounded-xl border border-gray-100 p-6">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Delivery Zones</h2>
        {zones && zones.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {zones.map((z: any) => (
              <div key={z.zoneId} className="border border-gray-100 rounded-lg p-4">
                <h3 className="font-medium text-gray-900">{z.name}</h3>
                <div className="text-sm text-gray-500 mt-1 space-y-0.5">
                  <p>Radius: {z.radiusMiles} mi</p>
                  <p>Fee: {z.deliveryFee > 0 ? `$${z.deliveryFee}` : 'Free'}</p>
                  <p>Min order: ${z.minOrderAmount}</p>
                  {z.freeDeliveryThreshold && <p>Free above: ${z.freeDeliveryThreshold}</p>}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-gray-400 text-sm">No delivery zones configured</p>
        )}
      </div>

      {/* Time Slots for Tomorrow */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white rounded-xl border border-gray-100 p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Pickup Slots — {dateStr}</h2>
          {pickupSlots && pickupSlots.length > 0 ? (
            <div className="space-y-2">
              {pickupSlots.map((s: any) => (
                <div key={s.slotId} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg text-sm">
                  <span className="font-medium">{s.startTime.slice(0, 5)} - {s.endTime.slice(0, 5)}</span>
                  <span className={`text-xs font-semibold ${s.spotsRemaining <= 2 ? 'text-red-600' : 'text-green-600'}`}>
                    {s.spotsRemaining} spots
                  </span>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-gray-400 text-sm">No pickup slots</p>
          )}
        </div>

        <div className="bg-white rounded-xl border border-gray-100 p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Delivery Slots — {dateStr}</h2>
          {deliverySlots && deliverySlots.length > 0 ? (
            <div className="space-y-2">
              {deliverySlots.map((s: any) => (
                <div key={s.slotId} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg text-sm">
                  <span className="font-medium">{s.startTime.slice(0, 5)} - {s.endTime.slice(0, 5)}</span>
                  <span className={`text-xs font-semibold ${s.spotsRemaining <= 1 ? 'text-red-600' : 'text-green-600'}`}>
                    {s.spotsRemaining} spots
                  </span>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-gray-400 text-sm">No delivery slots</p>
          )}
        </div>
      </div>
    </div>
  );
}
