// apps/admin/src/pages/ReportsPage.tsx
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { BarChart3, Receipt, Users, Warehouse, Download, Calendar, TrendingUp, DollarSign } from 'lucide-react';

const SALES_REPORT = `query($id: ID!, $s: String!, $e: String!) { salesReport(dispensaryId: $id, startDate: $s, endDate: $e) {
  totalOrders completedOrders cancelledOrders grossSales totalDiscounts totalTax netRevenue avgOrderValue deliveryOrders pickupOrders cashOrders cardOrders totalCashDiscounts
}}`;

const TAX_REPORT = `query($id: ID!, $s: String!, $e: String!) { taxReport(dispensaryId: $id, startDate: $s, endDate: $e) {
  dispensaryName state licenseNumber taxableSales totalDiscounts netTaxable totalTaxCollected transactionCount
  taxBreakdown { taxName taxCode rate taxBasis statutoryReference estimatedTax }
}}`;

const LABOR_REPORT = `query($id: ID!, $s: String!, $e: String!) { laborCostReport(dispensaryId: $id, startDate: $s, endDate: $e) {
  employeeCount totalHours totalLaborCost totalRevenue laborCostPercent
}}`;

const SHRINKAGE_REPORT = `query($id: ID!, $s: String!, $e: String!) { shrinkageReport(dispensaryId: $id, startDate: $s, endDate: $e) {
  totalAdjustments totalUnitsLost estimatedValueLost byReason { reason reasonCode count units estimatedValue }
}}`;

type Tab = 'sales' | 'tax' | 'staff' | 'inventory';

export function ReportsPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const token = useAuthStore((s) => s.token);
  const [tab, setTab] = useState<Tab>('sales');

  const today = new Date();
  const monthAgo = new Date(today); monthAgo.setDate(monthAgo.getDate() - 30);
  const [startDate, setStartDate] = useState(monthAgo.toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(today.toISOString().split('T')[0]);

  const { data: sales } = useQuery({
    queryKey: ['salesReport', dispensaryId, startDate, endDate],
    queryFn: () => gqlRequest<any>(SALES_REPORT, { id: dispensaryId, s: startDate, e: endDate }),
    select: (d) => d.salesReport,
    enabled: !!dispensaryId && tab === 'sales',
  });

  const { data: tax } = useQuery({
    queryKey: ['taxReport', dispensaryId, startDate, endDate],
    queryFn: () => gqlRequest<any>(TAX_REPORT, { id: dispensaryId, s: startDate, e: endDate }),
    select: (d) => d.taxReport,
    enabled: !!dispensaryId && tab === 'tax',
  });

  const { data: labor } = useQuery({
    queryKey: ['laborReport', dispensaryId, startDate, endDate],
    queryFn: () => gqlRequest<any>(LABOR_REPORT, { id: dispensaryId, s: startDate, e: endDate }),
    select: (d) => d.laborCostReport,
    enabled: !!dispensaryId && tab === 'staff',
  });

  const { data: shrinkage } = useQuery({
    queryKey: ['shrinkageReport', dispensaryId, startDate, endDate],
    queryFn: () => gqlRequest<any>(SHRINKAGE_REPORT, { id: dispensaryId, s: startDate, e: endDate }),
    select: (d) => d.shrinkageReport,
    enabled: !!dispensaryId && tab === 'inventory',
  });

  const downloadCsv = (type: string) => {
    const base = type === 'inventory'
      ? `/v1/reports/${type}/csv?dispensaryId=${dispensaryId}`
      : `/v1/reports/${type}/csv?dispensaryId=${dispensaryId}&startDate=${startDate}&endDate=${endDate}`;
    fetch(base, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'x-dispensary-id': dispensaryId ?? '',
        'x-organization-id': useAuthStore.getState().user?.organizationId ?? '',
      },
    }).then(r => r.blob()).then(blob => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${type}-report-${startDate}-to-${endDate}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  const fmt = (v: number) => `$${v.toLocaleString(undefined, { minimumFractionDigits: 2 })}`;

  const TABS: { key: Tab; label: string; icon: any }[] = [
    { key: 'sales', label: 'Sales', icon: BarChart3 },
    { key: 'tax', label: 'Tax', icon: Receipt },
    { key: 'staff', label: 'Staff', icon: Users },
    { key: 'inventory', label: 'Inventory', icon: Warehouse },
  ];

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-txt">Reports</h1>

      {/* Date Range + Tabs */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-1 bg-gray-100 rounded-lg p-1">
          {TABS.map(({ key, label, icon: Icon }) => (
            <button key={key} onClick={() => setTab(key)}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-md text-sm font-medium transition-colors ${tab === key ? 'bg-surface shadow text-txt' : 'text-txt-secondary hover:text-gray-700'}`}>
              <Icon size={15} /> {label}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2 text-sm">
          <Calendar size={14} className="text-txt-muted" />
          <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="border border-border rounded-lg px-2 py-1.5 text-sm" />
          <span className="text-txt-muted">to</span>
          <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="border border-border rounded-lg px-2 py-1.5 text-sm" />
          <button onClick={() => downloadCsv(tab)} className="flex items-center gap-1 bg-brand-600 text-txt-inverse text-sm font-medium px-3 py-1.5 rounded-lg hover:bg-brand-700">
            <Download size={14} /> CSV
          </button>
        </div>
      </div>

      {/* SALES TAB */}
      {tab === 'sales' && sales && (
        <div className="space-y-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{sales.completedOrders}</p><p className="text-xs text-txt-secondary">Orders</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold text-brand-700">{fmt(sales.netRevenue)}</p><p className="text-xs text-txt-secondary">Net Revenue</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{fmt(sales.avgOrderValue)}</p><p className="text-xs text-txt-secondary">Avg Order</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{fmt(sales.totalTax)}</p><p className="text-xs text-txt-secondary">Tax Collected</p></div>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-lg font-bold">{fmt(sales.grossSales)}</p><p className="text-xs text-txt-secondary">Gross Sales</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-lg font-bold text-red-600">-{fmt(sales.totalDiscounts)}</p><p className="text-xs text-txt-secondary">Discounts</p></div>
            <div className="bg-surface rounded-xl border border-border p-4">
              <p className="text-lg font-bold">{sales.pickupOrders} / {sales.deliveryOrders}</p><p className="text-xs text-txt-secondary">Pickup / Delivery</p>
            </div>
            <div className="bg-surface rounded-xl border border-border p-4">
              <p className="text-lg font-bold">{sales.cashOrders} / {sales.cardOrders}</p><p className="text-xs text-txt-secondary">Cash / Card</p>
              {sales.totalCashDiscounts > 0 && <p className="text-xs text-green-600 mt-0.5">Cash discounts: {fmt(sales.totalCashDiscounts)}</p>}
            </div>
          </div>
        </div>
      )}

      {/* TAX TAB */}
      {tab === 'tax' && tax && (
        <div className="space-y-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{fmt(tax.taxableSales)}</p><p className="text-xs text-txt-secondary">Taxable Sales</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{fmt(tax.netTaxable)}</p><p className="text-xs text-txt-secondary">Net Taxable</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold text-brand-700">{fmt(tax.totalTaxCollected)}</p><p className="text-xs text-txt-secondary">Tax Collected</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{tax.transactionCount}</p><p className="text-xs text-txt-secondary">Transactions</p></div>
          </div>
          <div className="bg-surface rounded-xl border border-border p-6">
            <h3 className="font-semibold mb-3">Tax Breakdown — {tax.state}</h3>
            <p className="text-xs text-txt-muted mb-3">License: {tax.licenseNumber}</p>
            <table className="w-full text-sm">
              <thead className="bg-bg-alt"><tr>
                <th className="text-left px-3 py-2 font-medium text-txt-secondary">Tax</th>
                <th className="text-right px-3 py-2 font-medium text-txt-secondary">Rate</th>
                <th className="text-left px-3 py-2 font-medium text-txt-secondary">Basis</th>
                <th className="text-left px-3 py-2 font-medium text-txt-secondary">Reference</th>
                <th className="text-right px-3 py-2 font-medium text-txt-secondary">Amount</th>
              </tr></thead>
              <tbody className="divide-y divide-gray-50">
                {tax.taxBreakdown.map((t: any, i: number) => (
                  <tr key={i}>
                    <td className="px-3 py-2 font-medium">{t.taxName}</td>
                    <td className="px-3 py-2 text-right tabular-nums">{(t.rate * 100).toFixed(2)}%</td>
                    <td className="px-3 py-2 text-txt-secondary">{t.taxBasis}</td>
                    <td className="px-3 py-2 text-xs text-txt-muted">{t.statutoryReference}</td>
                    <td className="px-3 py-2 text-right tabular-nums font-semibold">{fmt(t.estimatedTax)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* STAFF TAB */}
      {tab === 'staff' && labor && (
        <div className="space-y-4">
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{labor.employeeCount}</p><p className="text-xs text-txt-secondary">Employees</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold tabular-nums">{labor.totalHours.toFixed(1)}</p><p className="text-xs text-txt-secondary">Total Hours</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{fmt(labor.totalLaborCost)}</p><p className="text-xs text-txt-secondary">Labor Cost</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{fmt(labor.totalRevenue)}</p><p className="text-xs text-txt-secondary">Revenue</p></div>
            <div className="bg-surface rounded-xl border border-border p-4">
              <p className={`text-2xl font-bold ${labor.laborCostPercent > 30 ? 'text-red-600' : labor.laborCostPercent > 20 ? 'text-amber-600' : 'text-green-600'}`}>
                {labor.laborCostPercent}%
              </p>
              <p className="text-xs text-txt-secondary">Labor %</p>
            </div>
          </div>
        </div>
      )}

      {/* INVENTORY TAB */}
      {tab === 'inventory' && shrinkage && (
        <div className="space-y-4">
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold">{shrinkage.totalAdjustments}</p><p className="text-xs text-txt-secondary">Adjustments</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold text-red-600">{shrinkage.totalUnitsLost}</p><p className="text-xs text-txt-secondary">Units Lost</p></div>
            <div className="bg-surface rounded-xl border border-border p-4"><p className="text-2xl font-bold text-red-600">{fmt(shrinkage.estimatedValueLost)}</p><p className="text-xs text-txt-secondary">Est. Value Lost</p></div>
          </div>
          {shrinkage.byReason.length > 0 && (
            <div className="bg-surface rounded-xl border border-border p-6">
              <h3 className="font-semibold mb-3">Shrinkage by Reason</h3>
              <table className="w-full text-sm">
                <thead className="bg-bg-alt"><tr>
                  <th className="text-left px-3 py-2 font-medium text-txt-secondary">Reason</th>
                  <th className="text-right px-3 py-2 font-medium text-txt-secondary">Adjustments</th>
                  <th className="text-right px-3 py-2 font-medium text-txt-secondary">Units</th>
                  <th className="text-right px-3 py-2 font-medium text-txt-secondary">Est. Value</th>
                </tr></thead>
                <tbody className="divide-y divide-gray-50">
                  {shrinkage.byReason.map((r: any, i: number) => (
                    <tr key={i}>
                      <td className="px-3 py-2 font-medium">{r.reason}</td>
                      <td className="px-3 py-2 text-right tabular-nums">{r.count}</td>
                      <td className="px-3 py-2 text-right tabular-nums">{r.units}</td>
                      <td className="px-3 py-2 text-right tabular-nums font-semibold text-red-600">{fmt(r.estimatedValue)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// packages/angular/projects/admin/src/app/pages/reports/reports-page.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';

import { ReportsService, type ReportTab } from './reports.service';

const TABS: ReadonlyArray<{ key: ReportTab; label: string }> = [
  { key: 'sales', label: 'Sales' },
  { key: 'tax', label: 'Tax' },
  { key: 'staff', label: 'Staff' },
  { key: 'inventory', label: 'Inventory' },
];

/**
 * Reports hub. Four tabs (Sales / Tax / Staff / Inventory), each
 * backed by its own GraphQL query that only fires when the tab is
 * active (lazy `enabled` gate matches React parity).
 *
 * Filed scope mentioned ngx-charts visualizations — the React admin
 * doesn't render any charts here (just KPI tiles + breakdown
 * tables), so the Angular port matches that. The Dashboard (sc-624)
 * already covers the ngx-charts pattern when needed.
 *
 * CSV export deferred — the React UX hits REST endpoints
 * (`/v1/reports/<type>/csv`) with custom Authorization +
 * `x-dispensary-id` headers, which doesn't fit Apollo cleanly. File
 * a follow-up if needed.
 */
@Component({
  selector: 'cs-reports-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="space-y-6">
      <h1 class="text-2xl font-bold text-(--color-text)">Reports</h1>

      <div class="flex flex-wrap items-center justify-between gap-3">
        <div
          class="flex items-center gap-1 rounded-lg border border-(--color-border) bg-(--color-surface) p-1"
          role="tablist"
          aria-label="Report sections"
        >
          @for (t of tabs; track t.key) {
            <button
              type="button"
              role="tab"
              [attr.aria-selected]="tab() === t.key"
              (click)="setTab(t.key)"
              class="rounded-md px-4 py-2 text-sm font-medium transition-colors"
              [class]="
                tab() === t.key
                  ? 'bg-(--color-primary) text-white'
                  : 'text-(--color-text-secondary) hover:text-(--color-text)'
              "
            >
              {{ t.label }}
            </button>
          }
        </div>
        <div class="flex items-center gap-2 text-sm">
          <input
            type="date"
            [value]="startDate()"
            (change)="onStartDate($event)"
            aria-label="Start date"
            class="rounded-lg border border-(--color-border) bg-(--color-bg) px-2 py-1 text-sm text-(--color-text)"
          />
          <span class="text-(--color-text-muted)">to</span>
          <input
            type="date"
            [value]="endDate()"
            (change)="onEndDate($event)"
            aria-label="End date"
            class="rounded-lg border border-(--color-border) bg-(--color-bg) px-2 py-1 text-sm text-(--color-text)"
          />
        </div>
      </div>

      @if (loading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading report…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load report</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else {
        @switch (tab()) {
          @case ('sales') {
            @if (sales(); as s) {
              <div class="grid grid-cols-2 gap-3 md:grid-cols-4">
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ s.completedOrders }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Orders</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-primary) tabular-nums">
                    {{ money(s.netRevenue) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Net revenue</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ money(s.avgOrderValue) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Avg order</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ money(s.totalTax) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Tax collected</p>
                </article>
              </div>

              <div class="grid grid-cols-2 gap-3 md:grid-cols-4">
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-lg font-bold text-(--color-text) tabular-nums">
                    {{ money(s.grossSales) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Gross sales</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-lg font-bold text-rose-500 tabular-nums">
                    -{{ money(s.totalDiscounts) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Discounts</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-lg font-bold text-(--color-text) tabular-nums">
                    {{ s.pickupOrders }} / {{ s.deliveryOrders }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Pickup / Delivery</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-lg font-bold text-(--color-text) tabular-nums">
                    {{ s.cashOrders }} / {{ s.cardOrders }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Cash / Card</p>
                  @if (s.totalCashDiscounts > 0) {
                    <p class="mt-0.5 text-xs text-emerald-500">
                      Cash discounts: {{ money(s.totalCashDiscounts) }}
                    </p>
                  }
                </article>
              </div>
            } @else {
              <p
                class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
              >
                No sales data for this period.
              </p>
            }
          }

          @case ('tax') {
            @if (tax(); as t) {
              <div class="grid grid-cols-2 gap-3 md:grid-cols-4">
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ money(t.taxableSales) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Taxable sales</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ money(t.netTaxable) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Net taxable</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-primary) tabular-nums">
                    {{ money(t.totalTaxCollected) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Tax collected</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ t.transactionCount }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Transactions</p>
                </article>
              </div>

              <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
                <h3 class="mb-3 font-semibold text-(--color-text)">
                  Tax breakdown
                  @if (t.state) {
                    — {{ t.state }}
                  }
                </h3>
                @if (t.licenseNumber) {
                  <p class="mb-3 text-xs text-(--color-text-muted)">
                    License: {{ t.licenseNumber }}
                  </p>
                }
                @if (t.taxBreakdown.length === 0) {
                  <p class="text-sm text-(--color-text-muted)">No tax rules applied.</p>
                } @else {
                  <table class="w-full text-sm">
                    <thead class="bg-(--color-bg)">
                      <tr>
                        <th class="px-3 py-2 text-left font-medium text-(--color-text-secondary)">
                          Tax
                        </th>
                        <th class="px-3 py-2 text-right font-medium text-(--color-text-secondary)">
                          Rate
                        </th>
                        <th class="px-3 py-2 text-left font-medium text-(--color-text-secondary)">
                          Basis
                        </th>
                        <th class="px-3 py-2 text-left font-medium text-(--color-text-secondary)">
                          Reference
                        </th>
                        <th class="px-3 py-2 text-right font-medium text-(--color-text-secondary)">
                          Amount
                        </th>
                      </tr>
                    </thead>
                    <tbody class="divide-y divide-(--color-border)">
                      @for (row of t.taxBreakdown; track row.taxCode) {
                        <tr>
                          <td class="px-3 py-2 font-medium text-(--color-text)">
                            {{ row.taxName }}
                          </td>
                          <td class="px-3 py-2 text-right tabular-nums text-(--color-text)">
                            {{ ratePercent(row.rate) }}
                          </td>
                          <td class="px-3 py-2 text-(--color-text-secondary)">
                            {{ row.taxBasis }}
                          </td>
                          <td class="px-3 py-2 text-xs text-(--color-text-muted)">
                            {{ row.statutoryReference ?? '—' }}
                          </td>
                          <td
                            class="px-3 py-2 text-right font-semibold tabular-nums text-(--color-text)"
                          >
                            {{ money(row.estimatedTax) }}
                          </td>
                        </tr>
                      }
                    </tbody>
                  </table>
                }
              </div>
            } @else {
              <p
                class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
              >
                No tax data for this period.
              </p>
            }
          }

          @case ('staff') {
            @if (labor(); as l) {
              <div class="grid grid-cols-2 gap-3 md:grid-cols-5">
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ l.employeeCount }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Employees</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ l.totalHours.toFixed(1) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Total hours</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ money(l.totalLaborCost) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Labor cost</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ money(l.totalRevenue) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Revenue</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p
                    class="text-2xl font-bold tabular-nums"
                    [class]="laborPercentClass(l.laborCostPercent)"
                  >
                    {{ l.laborCostPercent }}%
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Labor %</p>
                </article>
              </div>
            } @else {
              <p
                class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
              >
                No labor data for this period.
              </p>
            }
          }

          @case ('inventory') {
            @if (shrinkage(); as sh) {
              <div class="grid grid-cols-3 gap-3">
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                    {{ sh.totalAdjustments }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Adjustments</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-rose-500 tabular-nums">
                    {{ sh.totalUnitsLost }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Units lost</p>
                </article>
                <article class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                  <p class="text-2xl font-bold text-rose-500 tabular-nums">
                    {{ money(sh.estimatedValueLost) }}
                  </p>
                  <p class="text-xs text-(--color-text-secondary)">Est. value lost</p>
                </article>
              </div>

              @if (sh.byReason.length > 0) {
                <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
                  <h3 class="mb-3 font-semibold text-(--color-text)">Shrinkage by reason</h3>
                  <table class="w-full text-sm">
                    <thead class="bg-(--color-bg)">
                      <tr>
                        <th class="px-3 py-2 text-left font-medium text-(--color-text-secondary)">
                          Reason
                        </th>
                        <th class="px-3 py-2 text-right font-medium text-(--color-text-secondary)">
                          Adjustments
                        </th>
                        <th class="px-3 py-2 text-right font-medium text-(--color-text-secondary)">
                          Units
                        </th>
                        <th class="px-3 py-2 text-right font-medium text-(--color-text-secondary)">
                          Est. value
                        </th>
                      </tr>
                    </thead>
                    <tbody class="divide-y divide-(--color-border)">
                      @for (r of sh.byReason; track r.reasonCode) {
                        <tr>
                          <td class="px-3 py-2 font-medium text-(--color-text)">
                            {{ r.reason }}
                          </td>
                          <td class="px-3 py-2 text-right tabular-nums text-(--color-text)">
                            {{ r.count }}
                          </td>
                          <td class="px-3 py-2 text-right tabular-nums text-(--color-text)">
                            {{ r.units }}
                          </td>
                          <td class="px-3 py-2 text-right font-semibold tabular-nums text-rose-500">
                            {{ money(r.estimatedValue) }}
                          </td>
                        </tr>
                      }
                    </tbody>
                  </table>
                </div>
              }
            } @else {
              <p
                class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
              >
                No inventory shrinkage data for this period.
              </p>
            }
          }
        }
      }
    </section>
  `,
})
export class ReportsPage {
  private readonly svc = inject(ReportsService);

  protected readonly tabs = TABS;
  protected readonly tab = this.svc.tab;
  protected readonly startDate = this.svc.startDate;
  protected readonly endDate = this.svc.endDate;
  protected readonly sales = this.svc.sales;
  protected readonly tax = this.svc.tax;
  protected readonly labor = this.svc.labor;
  protected readonly shrinkage = this.svc.shrinkage;
  protected readonly loading = this.svc.isLoading;
  protected readonly error = this.svc.error;

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load report.';
  });

  protected setTab(tab: ReportTab): void {
    this.svc.setTab(tab);
  }

  protected onStartDate(event: Event): void {
    this.svc.setStartDate((event.target as HTMLInputElement).value);
  }

  protected onEndDate(event: Event): void {
    this.svc.setEndDate((event.target as HTMLInputElement).value);
  }

  protected money(value: number): string {
    return (
      '$' +
      value.toLocaleString('en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })
    );
  }

  protected ratePercent(rate: number): string {
    return (rate * 100).toFixed(2) + '%';
  }

  protected laborPercentClass(percent: number): string {
    if (percent > 30) return 'text-rose-500';
    if (percent > 20) return 'text-amber-500';
    return 'text-emerald-500';
  }
}
