// apps/storefront/src/components/layout/Header.tsx
'use client';

import Link from 'next/link';
import { ShoppingBag, Search, User, Zap, Menu, X } from 'lucide-react';
import { useCartStore } from '@/stores/cart.store';
import { useAuthStore } from '@/stores/auth.store';
import { useState, useEffect } from 'react';

export function Header() {
  const itemCount = useCartStore((s) => s.itemCount());
  const { user, isAuthenticated } = useAuthStore();
  const [mounted, setMounted] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    setMounted(true);
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const isLoggedIn = mounted && isAuthenticated();

  return (
    <header className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 ${
      scrolled
        ? 'bg-white/90 backdrop-blur-xl border-b border-gray-100 shadow-sm'
        : 'bg-transparent'
    }`}>
      <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2.5">
          <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-sm font-black tracking-tighter transition-colors duration-300 ${
            scrolled ? 'bg-emerald-600 text-white' : 'bg-white/10 text-white backdrop-blur-sm border border-white/20'
          }`}>GL</div>
          <span className={`text-lg font-semibold tracking-tight transition-colors duration-300 ${
            scrolled ? 'text-gray-900' : 'text-white'
          }`} style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>GreenLeaf</span>
        </Link>

        {/* Desktop nav */}
        <nav className="hidden md:flex items-center gap-8">
          {[
            { href: '/products', label: 'Menu' },
            { href: '/products?category=flower', label: 'Flower' },
            { href: '/products?category=edibles', label: 'Edibles' },
            { href: '/products?category=vapes', label: 'Vapes' },
          ].map((link) => (
            <Link key={link.href} href={link.href}
              className={`text-sm font-medium transition-colors duration-300 ${
                scrolled ? 'text-gray-500 hover:text-gray-900' : 'text-white/60 hover:text-white'
              }`}>{link.label}</Link>
          ))}
          <Link href="/express-checkout"
            className={`flex items-center gap-1.5 text-sm font-medium transition-colors duration-300 ${
              scrolled ? 'text-emerald-600 hover:text-emerald-700' : 'text-emerald-300 hover:text-emerald-200'
            }`}><Zap size={13} /> Express</Link>
        </nav>

        {/* Right actions */}
        <div className="flex items-center gap-2">
          <Link href="/products" aria-label="Search"
            className={`p-2.5 rounded-full transition-all duration-300 ${
              scrolled ? 'text-gray-400 hover:text-gray-900 hover:bg-gray-100' : 'text-white/50 hover:text-white hover:bg-white/10'
            }`}><Search size={18} /></Link>

          <Link href="/cart" aria-label="Cart"
            className={`relative p-2.5 rounded-full transition-all duration-300 ${
              scrolled ? 'text-gray-400 hover:text-gray-900 hover:bg-gray-100' : 'text-white/50 hover:text-white hover:bg-white/10'
            }`}>
            <ShoppingBag size={18} />
            {itemCount > 0 && (
              <span className="absolute -top-0.5 -right-0.5 bg-emerald-500 text-white text-[9px] font-bold rounded-full min-w-[18px] min-h-[18px] flex items-center justify-center shadow-sm">
                {itemCount}
              </span>
            )}
          </Link>

          {isLoggedIn ? (
            <Link href="/account"
              className={`hidden sm:flex items-center gap-2 pl-2 pr-3 py-1.5 rounded-full transition-all duration-300 ${
                scrolled ? 'hover:bg-gray-100' : 'hover:bg-white/10'
              }`}>
              <div className="w-7 h-7 bg-emerald-100 rounded-full flex items-center justify-center">
                <span className="text-xs font-bold text-emerald-700">
                  {(user?.firstName?.[0] || user?.email?.[0] || 'U').toUpperCase()}
                </span>
              </div>
              <span className={`text-sm font-medium transition-colors duration-300 ${scrolled ? 'text-gray-700' : 'text-white/80'}`}>
                {user?.firstName || user?.email?.split('@')[0]}
              </span>
            </Link>
          ) : (
            <Link href="/login"
              className={`hidden sm:flex items-center text-sm font-medium px-4 py-2 rounded-full transition-all duration-300 ${
                scrolled
                  ? 'text-emerald-700 bg-emerald-50 hover:bg-emerald-100'
                  : 'text-white bg-white/10 hover:bg-white/20 border border-white/10 backdrop-blur-sm'
              }`}>Sign In</Link>
          )}

          {/* Mobile menu */}
          <button onClick={() => setMobileOpen(!mobileOpen)}
            className={`md:hidden p-2.5 rounded-full transition-colors ${
              scrolled ? 'text-gray-600 hover:bg-gray-100' : 'text-white/70 hover:bg-white/10'
            }`} aria-label="Toggle menu">
            {mobileOpen ? <X size={18} /> : <Menu size={18} />}
          </button>
        </div>
      </div>

      {mobileOpen && (
        <div className="md:hidden bg-white border-t border-gray-100 shadow-lg">
          <nav className="max-w-7xl mx-auto px-6 py-4 flex flex-col gap-1">
            {['Menu', 'Flower', 'Edibles', 'Vapes', 'Pre-Rolls'].map((item) => (
              <Link key={item} href={item === 'Menu' ? '/products' : `/products?category=${item.toLowerCase()}`}
                className="text-sm font-medium text-gray-600 hover:text-emerald-700 py-2.5 border-b border-gray-50 last:border-0"
                onClick={() => setMobileOpen(false)}>{item}</Link>
            ))}
          </nav>
        </div>
      )}
    </header>
  );
}

// packages/angular/projects/storefront/src/app/layout/header.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  inject,
  signal,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { filter, map } from 'rxjs';
import { AuthService } from '../core/auth/auth.service';
import { CartService } from '../core/cart/cart.service';

interface NavLink {
  readonly label: string;
  readonly path: string;
  readonly category?: string;
}

const NAV_LINKS: readonly NavLink[] = [
  { label: 'Menu', path: '/products' },
  { label: 'Flower', path: '/products', category: 'flower' },
  { label: 'Edibles', path: '/products', category: 'edibles' },
  { label: 'Vapes', path: '/products', category: 'vapes' },
];

const MOBILE_NAV_LABELS = ['Menu', 'Flower', 'Edibles', 'Vapes', 'Pre-Rolls'] as const;

const SCROLL_THRESHOLD_PX = 20;

@Component({
  selector: 'cs-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink],
  template: `
    <header
      class="fixed left-0 right-0 top-0 z-50 transition-all duration-500"
      [class]="
        solid()
          ? 'bg-white/90 backdrop-blur-xl border-b border-stone-100 shadow-sm'
          : 'bg-transparent'
      "
    >
      <div class="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
        <a class="flex items-center gap-2.5" [routerLink]="['/']">
          <div
            class="flex h-8 w-8 items-center justify-center rounded-lg text-sm font-black tracking-tighter transition-colors duration-300"
            [class]="
              solid()
                ? 'bg-emerald-600 text-white'
                : 'bg-white/10 text-white border border-white/20 backdrop-blur-sm'
            "
          >
            GL
          </div>
          <span
            class="text-lg font-semibold tracking-tight transition-colors duration-300"
            [class]="solid() ? 'text-stone-900' : 'text-white'"
            style="font-family: 'Playfair Display', Georgia, serif"
            >GreenLeaf</span
          >
        </a>

        <nav class="hidden items-center gap-8 md:flex">
          @for (link of navLinks; track link.label) {
            <a
              class="text-sm font-medium transition-colors duration-300"
              [class]="
                solid() ? 'text-stone-500 hover:text-stone-900' : 'text-white/60 hover:text-white'
              "
              [routerLink]="[link.path]"
              [queryParams]="link.category ? { category: link.category } : null"
              >{{ link.label }}</a
            >
          }
          <a
            class="flex items-center gap-1.5 text-sm font-medium transition-colors duration-300"
            [class]="
              solid()
                ? 'text-emerald-600 hover:text-emerald-700'
                : 'text-emerald-300 hover:text-emerald-200'
            "
            [routerLink]="['/express-checkout']"
          >
            <svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
              <path d="M13 2L3 14h7l-1 8 10-12h-7l1-8z" />
            </svg>
            Express
          </a>
        </nav>

        <div class="flex items-center gap-2">
          <a
            class="rounded-full p-2.5 transition-all duration-300"
            [class]="
              solid()
                ? 'text-stone-400 hover:bg-stone-100 hover:text-stone-900'
                : 'text-white/50 hover:bg-white/10 hover:text-white'
            "
            [routerLink]="['/products']"
            aria-label="Search"
          >
            <svg
              class="h-4 w-4"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              aria-hidden="true"
            >
              <circle cx="11" cy="11" r="7" />
              <path d="M21 21l-4.35-4.35" />
            </svg>
          </a>

          <a
            class="relative rounded-full p-2.5 transition-all duration-300"
            [class]="
              solid()
                ? 'text-stone-400 hover:bg-stone-100 hover:text-stone-900'
                : 'text-white/50 hover:bg-white/10 hover:text-white'
            "
            [routerLink]="['/cart']"
            aria-label="Cart"
          >
            <svg
              class="h-4 w-4"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              aria-hidden="true"
            >
              <path d="M16 11V7a4 4 0 00-8 0v4M5 9h14l-1 12H6L5 9z" />
            </svg>
            @if (itemCount() > 0) {
              <span
                class="absolute -right-0.5 -top-0.5 flex min-h-[18px] min-w-[18px] items-center justify-center rounded-full bg-emerald-500 text-[9px] font-bold text-white shadow-sm"
              >
                {{ itemCount() }}
              </span>
            }
          </a>

          @if (isLoggedIn()) {
            <a
              class="hidden items-center gap-2 rounded-full py-1.5 pl-2 pr-3 transition-all duration-300 sm:flex"
              [class]="solid() ? 'hover:bg-stone-100' : 'hover:bg-white/10'"
              [routerLink]="['/account']"
            >
              <div class="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-100">
                <span class="text-xs font-bold text-emerald-700">{{ initial() }}</span>
              </div>
              <span
                class="text-sm font-medium transition-colors duration-300"
                [class]="solid() ? 'text-stone-700' : 'text-white/80'"
                >{{ shortName() }}</span
              >
            </a>
          } @else {
            <a
              class="hidden items-center rounded-full px-4 py-2 text-sm font-medium transition-all duration-300 sm:flex"
              [class]="
                solid()
                  ? 'text-emerald-700 bg-emerald-50 hover:bg-emerald-100'
                  : 'text-white bg-white/10 hover:bg-white/20 border border-white/10 backdrop-blur-sm'
              "
              [routerLink]="['/login']"
              >Sign In</a
            >
          }

          <button
            type="button"
            class="rounded-full p-2.5 transition-colors md:hidden"
            [class]="
              solid() ? 'text-stone-600 hover:bg-stone-100' : 'text-white/70 hover:bg-white/10'
            "
            aria-label="Toggle menu"
            [attr.aria-expanded]="mobileOpen()"
            (click)="toggleMobile()"
          >
            @if (mobileOpen()) {
              <svg
                class="h-4 w-4"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                aria-hidden="true"
              >
                <path d="M6 6l12 12M6 18L18 6" />
              </svg>
            } @else {
              <svg
                class="h-4 w-4"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                aria-hidden="true"
              >
                <path d="M3 6h18M3 12h18M3 18h18" />
              </svg>
            }
          </button>
        </div>
      </div>

      @if (mobileOpen()) {
        <div class="border-t border-stone-100 bg-white shadow-lg md:hidden">
          <nav class="mx-auto flex max-w-7xl flex-col gap-1 px-6 py-4">
            @for (label of mobileNavLabels; track label) {
              <a
                class="border-b border-stone-50 py-2.5 text-sm font-medium text-stone-600 last:border-0 hover:text-emerald-700"
                [routerLink]="['/products']"
                [queryParams]="label === 'Menu' ? null : { category: label.toLowerCase() }"
                (click)="closeMobile()"
                >{{ label }}</a
              >
            }
          </nav>
        </div>
      }
    </header>
  `,
})
export class Header {
  private readonly auth = inject(AuthService);
  private readonly cart = inject(CartService);
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly navLinks = NAV_LINKS;
  protected readonly mobileNavLabels = MOBILE_NAV_LABELS;

  protected readonly itemCount = this.cart.itemCount;
  protected readonly isLoggedIn = this.auth.isAuthenticated;
  private readonly user = this.auth.user;

  protected readonly initial = computed(() => {
    const u = this.user();
    if (!u) return 'U';
    return (u.firstName?.[0] ?? u.email[0] ?? 'U').toUpperCase();
  });
  protected readonly shortName = computed(() => {
    const u = this.user();
    if (!u) return '';
    return u.firstName ?? u.email.split('@')[0];
  });

  private readonly currentUrl = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map((e) => e.urlAfterRedirects),
    ),
    { initialValue: this.router.url },
  );
  private readonly isHomepage = computed(() => {
    const url = this.currentUrl();
    return url === '/' || url === '';
  });

  private readonly scrolled = signal(false);
  protected readonly solid = computed(() => !this.isHomepage() || this.scrolled());

  protected readonly mobileOpen = signal(false);

  constructor() {
    if (typeof window === 'undefined') return;
    const onScroll = (): void => this.scrolled.set(window.scrollY > SCROLL_THRESHOLD_PX);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    this.destroyRef.onDestroy(() => window.removeEventListener('scroll', onScroll));
  }

  protected toggleMobile(): void {
    this.mobileOpen.update((v) => !v);
  }

  protected closeMobile(): void {
    this.mobileOpen.set(false);
  }
}
