// packages/angular/projects/storefront/src/app/features/products/product-card.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ProductsQuery } from '@cannasaas/ui-ng';
import { CartService } from '../../core/cart/cart.service';

export type ProductListItem = ProductsQuery['products'][number];

const STRAIN_BADGE_CLASS: Record<string, string> = {
  sativa: 'bg-orange-50 text-orange-700 border-orange-200',
  indica: 'bg-purple-50 text-purple-700 border-purple-200',
  hybrid: 'bg-green-50 text-green-700 border-green-200',
};

const STOCK_LABEL: Record<string, string> = {
  in_stock: 'In Stock',
  low_stock: 'Low Stock',
  out_of_stock: 'Sold Out',
};

const STOCK_CLASS: Record<string, string> = {
  in_stock: 'bg-emerald-50 text-emerald-700',
  low_stock: 'bg-amber-50 text-amber-700',
  out_of_stock: 'bg-rose-50 text-rose-700',
};

@Component({
  selector: 'cs-product-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink],
  template: `
    <a
      [routerLink]="['/products', product().id]"
      class="group block overflow-hidden rounded-xl border border-stone-200 bg-white transition-shadow hover:shadow-md"
      [class.opacity-70]="isOutOfStock()"
    >
      <div
        class="relative flex aspect-square items-center justify-center bg-gradient-to-br from-emerald-50 to-emerald-100"
      >
        <svg
          class="h-12 w-12 text-emerald-300"
          viewBox="0 0 24 24"
          fill="currentColor"
          aria-hidden="true"
        >
          <path
            d="M17 8C8 10 5.9 16.17 3.82 21.34l1.89.66.95-2.3c.48.17.98.3 1.34.3C19 20 22 3 22 3c-1 2-8 2.25-13 3.25S2 11.5 2 13.5s1.75 3.75 1.75 3.75C7 8 17 8 17 8z"
          />
        </svg>
        @if (product().strainType; as strain) {
          <span
            class="absolute left-3 top-3 rounded-full border px-2 py-0.5 text-[10px] font-semibold"
            [class]="strainBadge()"
            >{{ strain }}</span
          >
        }
        @if (stockStatus() !== 'in_stock') {
          <span
            class="absolute right-3 top-3 rounded-full px-2 py-0.5 text-[10px] font-semibold"
            [class]="stockClass()"
          >
            {{ stockLabel() }}
          </span>
        }
        @if (!isOutOfStock()) {
          <button
            type="button"
            class="absolute bottom-3 right-3 rounded-full p-2 transition-opacity"
            [class]="addButtonClass()"
            [disabled]="atMax()"
            [attr.aria-label]="addAriaLabel()"
            (click)="onAdd($event)"
          >
            <svg
              class="h-4 w-4"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
              stroke-linecap="round"
              aria-hidden="true"
            >
              <path d="M12 5v14M5 12h14" />
            </svg>
          </button>
        }
      </div>

      <div class="p-4">
        <h3 class="font-semibold text-stone-900 transition-colors group-hover:text-emerald-700">
          {{ product().name }}
        </h3>
        <div class="mt-2 flex items-center gap-3 text-xs text-stone-500">
          @if (product().thcPercent != null) {
            <span>THC {{ product().thcPercent }}%</span>
          }
          @if (product().cbdPercent != null) {
            <span>CBD {{ product().cbdPercent }}%</span>
          }
        </div>
        <div class="mt-2 flex items-center justify-between">
          @if (price() > 0) {
            <p class="text-lg font-bold text-emerald-700">\${{ priceLabel() }}</p>
          }
          @if (stockStatus() === 'in_stock') {
            <span class="text-[10px] font-medium text-emerald-700">In Stock</span>
          }
        </div>
      </div>
    </a>
  `,
})
export class ProductCard {
  readonly product = input.required<ProductListItem>();

  private readonly cart = inject(CartService);

  private readonly firstVariant = computed(() => this.product().variants[0] ?? null);

  readonly price = computed(() => Number(this.firstVariant()?.retailPrice ?? 0));
  readonly priceLabel = computed(() => this.price().toFixed(2));
  readonly stockStatus = computed(() => this.firstVariant()?.stockStatus ?? 'in_stock');
  readonly isOutOfStock = computed(() => this.stockStatus() === 'out_of_stock');
  readonly stockLabel = computed(() => STOCK_LABEL[this.stockStatus()] ?? STOCK_LABEL['in_stock']);
  readonly stockClass = computed(() => STOCK_CLASS[this.stockStatus()] ?? STOCK_CLASS['in_stock']);
  readonly strainBadge = computed(() => {
    const strain = this.product().strainType?.toLowerCase() ?? 'hybrid';
    return STRAIN_BADGE_CLASS[strain] ?? STRAIN_BADGE_CLASS['hybrid'];
  });

  readonly atMax = computed(() => {
    const variant = this.firstVariant();
    if (!variant?.stockQuantity) return false;
    const variantId = variant.variantId;
    const inCart = this.cart.items().find((i) => i.variantId === variantId);
    return inCart != null && inCart.quantity >= variant.stockQuantity;
  });

  readonly addButtonClass = computed(() =>
    this.atMax()
      ? 'bg-stone-400 text-white opacity-100 cursor-not-allowed'
      : 'bg-emerald-700 text-white opacity-0 group-hover:opacity-100 hover:bg-emerald-600',
  );

  readonly addAriaLabel = computed(() =>
    this.atMax()
      ? `${this.product().name} — maximum quantity in cart`
      : `Add ${this.product().name} to cart`,
  );

  onAdd(event: Event): void {
    event.preventDefault();
    if (this.isOutOfStock() || this.atMax()) return;
    const variant = this.firstVariant();
    const product = this.product();
    this.cart.addItem({
      productId: product.id,
      variantId: variant?.variantId ?? product.id,
      name: product.name,
      variantName: variant?.name ?? 'Standard',
      price: this.price(),
      maxQuantity: variant?.stockQuantity ?? undefined,
      strainType: product.strainType ?? undefined,
    });
  }
}

// apps/storefront/src/components/product/ProductCard.tsx
'use client';

import Link from 'next/link';
import { Leaf, Plus } from 'lucide-react';
import { useCartStore } from '@/stores/cart.store';

interface ProductCardProps {
  product: {
    id: string;
    name: string;
    strainType?: string;
    thcPercent?: number;
    cbdPercent?: number;
    description?: string;
    variants?: {
      variantId: string;
      name: string;
      retailPrice?: number;
      stockQuantity?: number;
      stockStatus?: string;
    }[];
  };
}

const STRAIN_COLORS: Record<string, string> = {
  sativa: 'bg-orange-50 text-orange-700 border-orange-200',
  indica: 'bg-purple-50 text-purple-700 border-purple-200',
  hybrid: 'bg-green-50 text-green-700 border-green-200',
};

const STOCK_BADGE: Record<string, { label: string; className: string }> = {
  in_stock: { label: 'In Stock', className: 'bg-success-bg text-success' },
  low_stock: { label: 'Low Stock', className: 'bg-warning-bg text-warning' },
  out_of_stock: { label: 'Sold Out', className: 'bg-danger-bg text-danger' },
};

export function ProductCard({ product }: ProductCardProps) {
  const addItem = useCartStore((s) => s.addItem);
  const cartItems = useCartStore((s) => s.items);

  const firstVariant = product.variants?.[0];
  const price = firstVariant?.retailPrice
    ? Number(firstVariant.retailPrice)
    : 0;
  const stockStatus = firstVariant?.stockStatus ?? 'in_stock';
  const stockQuantity = firstVariant?.stockQuantity ?? undefined;
  const isOutOfStock = stockStatus === 'out_of_stock';
  const badge = STOCK_BADGE[stockStatus] ?? STOCK_BADGE.in_stock;

  // Check if already at max in cart
  const inCart = cartItems.find(
    (i) =>
      i.productId === product.id &&
      i.variantId === (firstVariant?.variantId ?? product.id),
  );
  const atMax =
    stockQuantity != null && inCart != null && inCart.quantity >= stockQuantity;

  const handleAddToCart = (e: React.MouseEvent) => {
    e.preventDefault();
    if (isOutOfStock || atMax) return;
    addItem({
      productId: product.id,
      variantId: firstVariant?.variantId ?? product.id,
      name: product.name,
      variantName: firstVariant?.name ?? 'Standard',
      price,
      maxQuantity: stockQuantity,
      strainType: product.strainType,
    });
  };

  return (
    <Link
      href={`/products/${product.id}`}
      className={`group bg-surface rounded-xl border border-bdr overflow-hidden hover:shadow-md transition-shadow ${isOutOfStock ? 'opacity-70' : ''}`}
    >
      {/* Image placeholder */}
      <div className="aspect-square bg-gradient-to-br from-brand-50 to-brand-100 flex items-center justify-center relative">
        <Leaf size={48} className="text-brand-400 opacity-30" />
        {product.strainType && (
          <span
            className={`absolute top-3 left-3 text-[10px] font-semibold px-2 py-0.5 rounded-full border ${STRAIN_COLORS[product.strainType] ?? STRAIN_COLORS.hybrid}`}
          >
            {product.strainType}
          </span>
        )}
        {/* Stock badge */}
        {stockStatus !== 'in_stock' && (
          <span
            className={`absolute top-3 right-3 text-[10px] font-semibold px-2 py-0.5 rounded-full ${badge.className}`}
          >
            {badge.label}
          </span>
        )}
        {!isOutOfStock && (
          <button
            onClick={handleAddToCart}
            disabled={atMax}
            className={`absolute bottom-3 right-3 p-2 rounded-full transition-opacity ${
              atMax
                ? 'bg-gray-400 text-white cursor-not-allowed opacity-100'
                : 'bg-brand-600 text-txt-inverse opacity-0 group-hover:opacity-100 hover:bg-brand-500'
            }`}
            aria-label={
              atMax
                ? `${product.name} — maximum quantity in cart`
                : `Add ${product.name} to cart`
            }
          >
            <Plus size={16} />
          </button>
        )}
      </div>

      {/* Details */}
      <div className="p-4">
        <h3 className="font-semibold text-txt group-hover:text-brand-600 transition-colors">
          {product.name}
        </h3>

        <div className="flex items-center gap-3 mt-2 text-xs text-txt-muted">
          {product.thcPercent != null && <span>THC {product.thcPercent}%</span>}
          {product.cbdPercent != null && <span>CBD {product.cbdPercent}%</span>}
        </div>

        <div className="flex items-center justify-between mt-2">
          {price > 0 && (
            <p className="text-lg font-bold text-brand-600">
              ${price.toFixed(2)}
            </p>
          )}
          {stockStatus === 'in_stock' && (
            <span className="text-[10px] text-success font-medium">
              In Stock
            </span>
          )}
        </div>
      </div>
    </Link>
  );
}
