// apps/kiosk/src/pages/MenuPage.tsx
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { gql, DISPENSARY_ID } from '../lib/graphql';
import { useCartStore } from '../stores/cart.store';
import { Plus, Check, ShoppingBag, Sparkles } from 'lucide-react';

const PRODUCTS_QUERY = `query($id: ID!) { products(dispensaryId: $id) {
  id name strainType strainName thcPercent cbdPercent description effects flavors
  variants { variantId name sku retailPrice }
}}`;

const FILTERS = ['All', 'Flower', 'Edible', 'Vape', 'Pre-Roll', 'Concentrate'];

const STRAIN_STYLE: Record<string, { bg: string; badge: string }> = {
  sativa:  { bg: 'from-amber-100 via-orange-50 to-yellow-50', badge: 'bg-amber-500 text-white' },
  indica:  { bg: 'from-violet-100 via-purple-50 to-indigo-50', badge: 'bg-violet-500 text-white' },
  hybrid:  { bg: 'from-emerald-100 via-green-50 to-teal-50', badge: 'bg-emerald-500 text-white' },
};

function hashCode(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) hash = ((hash << 5) - hash) + str.charCodeAt(i) | 0;
  return Math.abs(hash);
}

export function MenuPage() {
  const navigate = useNavigate();
  const addItem = useCartStore((s) => s.addItem);
  const [filter, setFilter] = useState('All');
  const [addedId, setAddedId] = useState<string | null>(null);

  const { data: products, isLoading } = useQuery({
    queryKey: ['kioskProducts'],
    queryFn: () => gql<any>(PRODUCTS_QUERY, { id: DISPENSARY_ID }),
    select: (d) => d.products,
  });

  const getPrice = (p: any) => p.variants?.[0]?.retailPrice ? Number(p.variants[0].retailPrice) : 0;

  const handleAdd = (e: React.MouseEvent, product: any) => {
    e.stopPropagation();
    const v = product.variants?.[0];
    if (!v) return;
    addItem({ productId: product.id, variantId: v.variantId, name: product.name, variantName: v.name, price: getPrice(product), strainType: product.strainType });
    setAddedId(product.id);
    setTimeout(() => setAddedId(null), 1500);
  };

  const filtered = (products ?? []).filter((p: any) =>
    filter === 'All' || p.name?.toLowerCase().includes(filter.toLowerCase())
  );

  return (
    <div className="p-6 lg:p-8">
      {/* Hero banner */}
      <div className="mb-8 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-emerald-50 border border-emerald-200 rounded-full text-emerald-700 text-xs font-medium tracking-wider uppercase mb-3">
          <Sparkles size={12} /> Welcome
        </div>
        <h1 className="text-3xl lg:text-4xl font-light text-gray-900" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
          Browse Our <span className="italic text-emerald-700">Menu</span>
        </h1>
        <p className="text-sm text-gray-400 mt-2">Tap a product to learn more, or add directly to your cart</p>
      </div>

      {/* Filters */}
      <div className="flex gap-2 mb-8 overflow-x-auto pb-2 justify-center">
        {FILTERS.map((f) => (
          <button key={f} onClick={() => setFilter(f)}
            className={`px-6 py-3 rounded-full text-sm font-semibold whitespace-nowrap transition-all active:scale-95 ${
              filter === f
                ? 'bg-emerald-600 text-white shadow-md shadow-emerald-500/20'
                : 'bg-white text-gray-500 border border-gray-200 hover:border-emerald-200 hover:text-emerald-700'
            }`}>
            {f}
          </button>
        ))}
      </div>

      {/* Loading */}
      {isLoading && (
        <div className="text-center py-20 text-gray-400">
          <div className="w-8 h-8 border-2 border-emerald-300 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          Loading menu...
        </div>
      )}

      {/* Products Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
        {filtered.map((p: any) => {
          const price = getPrice(p);
          const isAdded = addedId === p.id;
          const strain = STRAIN_STYLE[p.strainType || 'hybrid'] || STRAIN_STYLE.hybrid;
          const hash = hashCode(p.name);

          return (
            <button key={p.id} onClick={() => navigate('/product/' + p.id)}
              className="bg-white rounded-2xl border border-gray-100 overflow-hidden hover:border-emerald-200 hover:shadow-xl hover:shadow-emerald-500/5 transition-all duration-300 text-left active:scale-[0.98]">

              {/* Product visual */}
              <div className={`aspect-[4/3] bg-gradient-to-br ${strain.bg} relative overflow-hidden`}>
                <div className="absolute rounded-full opacity-20 blur-xl"
                  style={{
                    width: `${60 + (hash % 40)}%`, height: `${60 + (hash % 40)}%`,
                    top: `${10 + (hash % 30)}%`, left: `${10 + ((hash >> 4) % 30)}%`,
                    background: p.strainType === 'sativa' ? '#f59e0b' : p.strainType === 'indica' ? '#8b5cf6' : '#10b981',
                  }} />
                {p.strainType && (
                  <span className={`absolute top-3 left-3 text-[11px] font-bold tracking-wider uppercase px-3 py-1 rounded-full ${strain.badge} shadow-sm`}>
                    {p.strainType}
                  </span>
                )}
                <div className="absolute bottom-3 left-3 flex gap-1.5">
                  {p.thcPercent != null && p.thcPercent > 0 && (
                    <span className="text-[11px] font-bold bg-white/80 backdrop-blur-sm text-gray-700 px-2.5 py-1 rounded-full">
                      THC {p.thcPercent}%
                    </span>
                  )}
                </div>
              </div>

              {/* Info */}
              <div className="p-5">
                <h3 className="font-semibold text-gray-900 text-lg leading-tight">{p.name}</h3>
                {p.strainName && p.strainName !== p.name && (
                  <p className="text-xs text-gray-400 mt-0.5 italic">{p.strainName}</p>
                )}

                {p.effects && p.effects.length > 0 && (
                  <div className="flex flex-wrap gap-1 mt-3">
                    {p.effects.slice(0, 3).map((effect: string) => (
                      <span key={effect} className="text-[10px] font-medium bg-gray-50 text-gray-500 px-2 py-0.5 rounded-full border border-gray-100">
                        {effect}
                      </span>
                    ))}
                  </div>
                )}

                <div className="flex items-center justify-between mt-4">
                  <span className="text-2xl font-bold text-gray-900">${price.toFixed(2)}</span>
                  <div onClick={(e) => handleAdd(e, p)}
                    className={`flex items-center gap-2 px-5 py-3 rounded-full text-sm font-semibold transition-all active:scale-95 ${
                      isAdded
                        ? 'bg-emerald-100 text-emerald-700'
                        : 'bg-emerald-600 text-white hover:bg-emerald-500 shadow-md shadow-emerald-500/20'
                    }`}>
                    {isAdded ? <><Check size={18} /> Added</> : <><Plus size={18} /> Add</>}
                  </div>
                </div>
              </div>
            </button>
          );
        })}
      </div>

      {!isLoading && filtered.length === 0 && (
        <div className="text-center py-20">
          <ShoppingBag size={48} className="text-gray-200 mx-auto mb-4" />
          <p className="text-gray-400">No products found</p>
        </div>
      )}
    </div>
  );
}

// packages/angular/projects/kiosk/src/app/pages/menu/menu-page.ts
import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { rxResource } from '@angular/core/rxjs-interop';
import { Router } from '@angular/router';
import { ProductsGQL, type ProductsQuery } from '@cannasaas/ui-ng';
import { map } from 'rxjs';
import { CartService } from '../../core/cart/cart.service';
import { environment } from '../../../environments/environment';

type ApiProduct = ProductsQuery['products'][number];
type ApiVariant = ApiProduct['variants'][number];
type StrainKey = 'sativa' | 'indica' | 'hybrid';

interface StrainStyle {
  readonly bg: string;
  readonly badge: string;
  readonly orb: string;
}

const STRAIN_STYLE: Record<StrainKey, StrainStyle> = {
  sativa: {
    bg: 'from-amber-100 via-orange-50 to-yellow-50',
    badge: 'bg-amber-500 text-white',
    orb: '#f59e0b',
  },
  indica: {
    bg: 'from-violet-100 via-purple-50 to-indigo-50',
    badge: 'bg-violet-500 text-white',
    orb: '#8b5cf6',
  },
  hybrid: {
    bg: 'from-emerald-100 via-green-50 to-teal-50',
    badge: 'bg-emerald-500 text-white',
    orb: '#10b981',
  },
};

interface CategoryFilter {
  readonly label: string;
  /** `null` means "all" — omit productTypeId from the query. */
  readonly productTypeId: number | null;
}

const FILTERS: readonly CategoryFilter[] = [
  { label: 'All', productTypeId: null },
  { label: 'Flower', productTypeId: 1 },
  { label: 'Pre-Roll', productTypeId: 2 },
  { label: 'Vape', productTypeId: 3 },
  { label: 'Concentrate', productTypeId: 4 },
  { label: 'Edible', productTypeId: 5 },
];

const ADDED_FLASH_MS = 1500;

function asStrainKey(value: string | null | undefined): StrainKey {
  return value === 'sativa' || value === 'indica' || value === 'hybrid' ? value : 'hybrid';
}

function asStringArray(value: Record<string, unknown> | null | undefined): string[] {
  return Array.isArray(value) ? (value as string[]).filter((s) => typeof s === 'string') : [];
}

function getPrice(product: ApiProduct): number {
  const first = product.variants[0];
  return typeof first?.retailPrice === 'number' ? first.retailPrice : 0;
}

function variantInStock(variant: ApiVariant | undefined): boolean {
  if (!variant || variant.isActive === false) return false;
  if (typeof variant.stockQuantity === 'number') return variant.stockQuantity > 0;
  // Fallback when stockQuantity is null: trust stockStatus.
  return variant.stockStatus !== 'out_of_stock';
}

function hashCode(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i += 1) {
    hash = (((hash << 5) - hash) + str.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

@Component({
  selector: 'cs-menu-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="p-6 lg:p-8">
      <div class="mb-8 text-center">
        <div
          class="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-4 py-1.5 text-xs font-medium tracking-wider text-emerald-700 uppercase"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="12"
            height="12"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path
              d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.582a.5.5 0 0 1 0 .962L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"
            />
          </svg>
          Welcome
        </div>
        <h1
          class="text-3xl font-light text-gray-900 lg:text-4xl"
          style="font-family: 'Playfair Display', Georgia, serif;"
        >
          Browse Our <span class="text-emerald-700 italic">Menu</span>
        </h1>
        <p class="mt-2 text-sm text-gray-400">
          Tap a product to learn more, or add directly to your cart
        </p>
      </div>

      <div class="mb-8 flex justify-center gap-2 overflow-x-auto pb-2">
        @for (f of filters; track f.label) {
          @let active = filter().productTypeId === f.productTypeId;
          <button
            type="button"
            (click)="filter.set(f)"
            class="rounded-full px-6 py-3 text-sm font-semibold whitespace-nowrap active:scale-95"
            [class.bg-emerald-600]="active"
            [class.text-white]="active"
            [class.shadow-md]="active"
            [class.shadow-emerald-500\\/20]="active"
            [class.bg-white]="!active"
            [class.text-gray-500]="!active"
            [class.border]="!active"
            [class.border-gray-200]="!active"
          >
            {{ f.label }}
          </button>
        }
      </div>

      @if (loading()) {
        <div class="py-20 text-center text-gray-400">
          <div
            class="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-emerald-300 border-t-transparent"
          ></div>
          Loading menu...
        </div>
      } @else if (filtered().length === 0) {
        <div class="py-20 text-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="48"
            height="48"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="mx-auto mb-4 text-gray-200"
          >
            <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
            <path d="M3 6h18" />
            <path d="M16 10a4 4 0 0 1-8 0" />
          </svg>
          <p class="text-gray-400">No products found</p>
        </div>
      } @else {
        <div class="grid grid-cols-2 gap-5 lg:grid-cols-3 xl:grid-cols-4">
          @for (p of filtered(); track p.id) {
            @let strain = strainStyleFor(p.strainType);
            @let orb = orbStyle(p.name);
            @let isAdded = addedId() === p.id;
            @let inStock = isInStock(p);
            <button
              type="button"
              (click)="goToProduct(p.id)"
              class="overflow-hidden rounded-2xl border border-gray-100 bg-white text-left transition-all duration-300 active:scale-[0.98]"
            >
              <div
                class="relative aspect-[4/3] overflow-hidden bg-linear-to-br"
                [class]="strain.bg"
              >
                <div
                  class="absolute rounded-full opacity-20 blur-xl"
                  [style.width.%]="orb.size"
                  [style.height.%]="orb.size"
                  [style.top.%]="orb.top"
                  [style.left.%]="orb.left"
                  [style.background]="strain.orb"
                ></div>
                @if (p.strainType) {
                  <span
                    class="absolute top-3 left-3 rounded-full px-3 py-1 text-[11px] font-bold tracking-wider uppercase shadow-sm"
                    [class]="strain.badge"
                  >
                    {{ p.strainType }}
                  </span>
                }
                @if (p.thcPercent !== null && p.thcPercent !== undefined && p.thcPercent > 0) {
                  <span
                    class="absolute bottom-3 left-3 rounded-full bg-white/80 px-2.5 py-1 text-[11px] font-bold text-gray-700 backdrop-blur-sm"
                  >
                    THC {{ p.thcPercent }}%
                  </span>
                }
              </div>

              <div class="p-5">
                <h3 class="text-lg leading-tight font-semibold text-gray-900">
                  {{ p.name }}
                </h3>
                @if (p.strainName && p.strainName !== p.name) {
                  <p class="mt-0.5 text-xs text-gray-400 italic">{{ p.strainName }}</p>
                }
                @let effs = effectsOf(p);
                @if (effs.length > 0) {
                  <div class="mt-3 flex flex-wrap gap-1">
                    @for (effect of effs.slice(0, 3); track effect) {
                      <span
                        class="rounded-full border border-gray-100 bg-gray-50 px-2 py-0.5 text-[10px] font-medium text-gray-500"
                      >
                        {{ effect }}
                      </span>
                    }
                  </div>
                }

                <div class="mt-4 flex items-center justify-between">
                  <span class="text-2xl font-bold text-gray-900">
                    {{ priceOf(p) | currency }}
                  </span>
                  <span
                    role="button"
                    [attr.aria-disabled]="!inStock"
                    [tabindex]="inStock ? 0 : -1"
                    (click)="inStock && onAddClick($event, p)"
                    [class]="addControlClasses(inStock, isAdded)"
                  >
                    @if (!inStock) {
                      Sold out
                    } @else if (isAdded) {
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="18"
                        height="18"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path d="M20 6 9 17l-5-5" />
                      </svg>
                      Added
                    } @else {
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="18"
                        height="18"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path d="M5 12h14" />
                        <path d="M12 5v14" />
                      </svg>
                      Add
                    }
                  </span>
                </div>
              </div>
            </button>
          }
        </div>
      }
    </div>
  `,
  imports: [CurrencyPipe],
})
export class MenuPage {
  private readonly productsGQL = inject(ProductsGQL);
  private readonly cart = inject(CartService);
  private readonly router = inject(Router);

  protected readonly filters = FILTERS;
  protected readonly filter = signal<CategoryFilter>(FILTERS[0]!);
  protected readonly addedId = signal<string | null>(null);

  private readonly resource = rxResource({
    params: () => ({ productTypeId: this.filter().productTypeId }),
    stream: ({ params }) =>
      this.productsGQL
        .fetch({
          variables: {
            dispensaryId: environment.dispensaryId,
            productTypeId: params.productTypeId ?? null,
          },
        })
        .pipe(
          map((r) => (r.data?.products ?? []) as readonly ApiProduct[]),
        ),
  });

  protected readonly loading = this.resource.isLoading;
  protected readonly filtered = computed<readonly ApiProduct[]>(
    void () => this.resource.value() ?? [],
  );

  protected goToProduct(id: string): void {
    this.router.navigateByUrl(`/product/${id}`);
  }

  protected onAddClick(event: Event, product: ApiProduct): void {
    event.stopPropagation();
    const variant = product.variants[0];
    if (!variant) return;
    this.cart.addItem({
      productId: product.id,
      variantId: variant.variantId,
      name: product.name,
      variantName: variant.name,
      price: getPrice(product),
      strainType: product.strainType ?? undefined,
    });
    this.addedId.set(product.id);
    setTimeout(() => {
      if (this.addedId() === product.id) this.addedId.set(null);
    }, ADDED_FLASH_MS);
  }

  protected priceOf(p: ApiProduct): number {
    return getPrice(p);
  }

  protected effectsOf(p: ApiProduct): string[] {
    return asStringArray(p.effects);
  }

  protected strainStyleFor(value: string | null | undefined): StrainStyle {
    return STRAIN_STYLE[asStrainKey(value)];
  }

  protected orbStyle(name: string): { size: number; top: number; left: number } {
    const h = hashCode(name);
    return {
      size: 60 + (h % 40),
      top: 10 + (h % 30),
      left: 10 + ((h >> 4) % 30),
    };
  }

  protected isInStock(product: ApiProduct): boolean {
    return variantInStock(product.variants[0]);
  }

  protected addControlClasses(inStock: boolean, isAdded: boolean): string {
    const base = 'flex items-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition-all';
    if (!inStock) {
      return `${base} cursor-not-allowed bg-gray-200 text-gray-500`;
    }
    if (isAdded) {
      return `${base} bg-emerald-100 text-emerald-700 active:scale-95`;
    }
    return `${base} bg-emerald-600 text-white shadow-md shadow-emerald-500/20 active:scale-95`;
  }
}
