// apps/staff/src/pages/NewOrderPage.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Search, Plus, Minus, Trash2, UserPlus, ShoppingCart, CheckCircle,
  Leaf, Loader2, X, AlertTriangle, User,
} from 'lucide-react';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';

// ── GraphQL ──────────────────────────────────────────────────

const PRODUCTS_QUERY = `query($dispensaryId: ID!, $search: String, $limit: Int) {
  products(dispensaryId: $dispensaryId, search: $search, limit: $limit) {
    id name strainType thcPercent cbdPercent
    variants { variantId name retailPrice stockQuantity stockStatus quantityPerUnit }
  }
}`;

const SEARCH_CUSTOMERS = `query($dispensaryId: ID!, $query: String!, $limit: Int) {
  searchCustomers(dispensaryId: $dispensaryId, query: $query, limit: $limit) {
    userId email firstName lastName phone ageVerified totalOrders
  }
}`;

const CREATE_WALKIN = `mutation($input: CreateWalkInCustomerInput!) {
  createWalkInCustomer(input: $input) {
    userId email firstName lastName phone ageVerified totalOrders
  }
}`;

const CREATE_ORDER = `mutation($input: CreateOrderInput!) {
  createOrder(input: $input) {
    orderId orderStatus subtotal taxTotal total lineItemCount
  }
}`;

// ── Types ────────────────────────────────────────────────────

interface Variant {
  variantId: string; name: string; retailPrice: number | null;
  stockQuantity: number | null; stockStatus: string | null; quantityPerUnit: number | null;
}
interface Product {
  id: string; name: string; strainType: string | null;
  thcPercent: number | null; cbdPercent: number | null; variants: Variant[];
}
interface Customer {
  userId: string; email: string; firstName?: string; lastName?: string;
  phone?: string; ageVerified: boolean; totalOrders: number;
}
interface CartItem {
  productId: string; variantId: string; productName: string;
  variantName: string; price: number; quantity: number; maxStock: number;
}

const STRAIN_COLORS: Record<string, string> = {
  sativa: 'bg-orange-100 text-orange-700',
  indica: 'bg-purple-100 text-purple-700',
  hybrid: 'bg-green-100 text-green-700',
};

// ── Component ────────────────────────────────────────────────

export function NewOrderPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const queryClient = useQueryClient();

  // Cart state
  const [cart, setCart] = useState<CartItem[]>([]);
  const [customer, setCustomer] = useState<Customer | null>(null);

  // Product search
  const [productSearch, setProductSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');

  // Customer search
  const [custSearch, setCustSearch] = useState('');
  const [debouncedCust, setDebouncedCust] = useState('');
  const [showCustSearch, setShowCustSearch] = useState(false);
  const [showNewCustForm, setShowNewCustForm] = useState(false);
  const [newCust, setNewCust] = useState({ firstName: '', lastName: '', phone: '', email: '' });

  // Order result
  const [orderResult, setOrderResult] = useState<any>(null);

  // Debounce product search
  const prodTimer = useRef<any>(null);
  const handleProductSearch = (val: string) => {
    setProductSearch(val);
    clearTimeout(prodTimer.current);
    prodTimer.current = setTimeout(() => setDebouncedSearch(val), 250);
  };

  // Debounce customer search
  const custTimer = useRef<any>(null);
  const handleCustSearch = (val: string) => {
    setCustSearch(val);
    clearTimeout(custTimer.current);
    custTimer.current = setTimeout(() => setDebouncedCust(val), 300);
  };

  // ── Queries ────────────────────────────────────────────────

  const { data: products, isLoading: productsLoading } = useQuery({
    queryKey: ['posProducts', dispensaryId, debouncedSearch],
    queryFn: () => gqlRequest<{ products: Product[] }>(PRODUCTS_QUERY, {
      dispensaryId, search: debouncedSearch || undefined, limit: 30,
    }),
    select: (d) => d.products,
    enabled: !!dispensaryId,
  });

  const { data: custResults } = useQuery({
    queryKey: ['custSearch', dispensaryId, debouncedCust],
    queryFn: () => gqlRequest<{ searchCustomers: Customer[] }>(SEARCH_CUSTOMERS, {
      dispensaryId, query: debouncedCust, limit: 8,
    }),
    select: (d) => d.searchCustomers,
    enabled: !!dispensaryId && debouncedCust.length >= 2,
  });

  // ── Mutations ──────────────────────────────────────────────

  const createCustomer = useMutation({
    mutationFn: () => gqlRequest<{ createWalkInCustomer: Customer }>(CREATE_WALKIN, {
      input: { ...newCust, dispensaryId },
    }),
    onSuccess: (data) => {
      setCustomer(data.createWalkInCustomer);
      setShowNewCustForm(false);
      setShowCustSearch(false);
      setNewCust({ firstName: '', lastName: '', phone: '', email: '' });
    },
  });

  const placeOrder = useMutation({
    mutationFn: () => gqlRequest<{ createOrder: any }>(CREATE_ORDER, {
      input: {
        dispensaryId,
        customerUserId: customer!.userId,
        orderType: 'in_store',
        lineItems: cart.map((item) => ({
          productId: item.productId,
          variantId: item.variantId,
          quantity: item.quantity,
        })),
      },
    }),
    onSuccess: (data) => {
      setOrderResult(data.createOrder);
      queryClient.invalidateQueries({ queryKey: ['activeOrders'] });
      queryClient.invalidateQueries({ queryKey: ['staffDashboard'] });
    },
  });

  // ── Cart helpers ───────────────────────────────────────────

  const addToCart = useCallback((product: Product, variant: Variant) => {
    const price = variant.retailPrice ? Number(variant.retailPrice) : 0;
    const maxStock = variant.stockQuantity != null ? Number(variant.stockQuantity) : 999;
    if (maxStock <= 0) return;

    setCart((prev) => {
      const existing = prev.find((i) => i.variantId === variant.variantId);
      if (existing) {
        if (existing.quantity >= maxStock) return prev;
        return prev.map((i) =>
          i.variantId === variant.variantId
            ? { ...i, quantity: Math.min(i.quantity + 1, maxStock) }
            : i,
        );
      }
      return [...prev, {
        productId: product.id, variantId: variant.variantId,
        productName: product.name, variantName: variant.name,
        price, quantity: 1, maxStock,
      }];
    });
  }, []);

  const updateQty = useCallback((variantId: string, qty: number) => {
    setCart((prev) => {
      if (qty <= 0) return prev.filter((i) => i.variantId !== variantId);
      return prev.map((i) =>
        i.variantId === variantId
          ? { ...i, quantity: Math.min(qty, i.maxStock) }
          : i,
      );
    });
  }, []);

  const removeFromCart = useCallback((variantId: string) => {
    setCart((prev) => prev.filter((i) => i.variantId !== variantId));
  }, []);

  const cartTotal = cart.reduce((sum, i) => sum + i.price * i.quantity, 0);
  const cartCount = cart.reduce((sum, i) => sum + i.quantity, 0);

  // ── Reset for new order ────────────────────────────────────

  const startNewOrder = () => {
    setCart([]);
    setCustomer(null);
    setOrderResult(null);
    setProductSearch('');
    setDebouncedSearch('');
  };

  // ── Order success screen ───────────────────────────────────

  if (orderResult) {
    return (
      <div className="max-w-lg mx-auto py-12 text-center">
        <div className="bg-green-50 border border-green-200 rounded-2xl p-8">
          <CheckCircle size={56} className="mx-auto text-green-600 mb-4" />
          <h2 className="text-2xl font-bold text-green-800">Order Placed</h2>
          <p className="text-sm text-green-600 mt-1">
            #{orderResult.orderId.slice(0, 8).toUpperCase()}
          </p>
          <div className="mt-6 space-y-2 text-sm">
            <p className="text-green-700">
              Customer: <strong>{customer?.firstName} {customer?.lastName}</strong>
            </p>
            <p className="text-green-700">
              Items: <strong>{orderResult.lineItemCount}</strong>
            </p>
            <div className="border-t border-green-200 pt-3 mt-3 space-y-1">
              <div className="flex justify-between">
                <span className="text-green-600">Subtotal</span>
                <span className="font-medium">${parseFloat(orderResult.subtotal).toFixed(2)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-green-600">Tax</span>
                <span className="font-medium">${parseFloat(orderResult.taxTotal).toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-lg font-bold text-green-800 pt-1">
                <span>Total</span>
                <span>${parseFloat(orderResult.total).toFixed(2)}</span>
              </div>
            </div>
          </div>
          <button
            onClick={startNewOrder}
            className="mt-6 bg-green-600 text-white font-semibold px-8 py-3 rounded-xl hover:bg-green-700 transition-colors"
          >
            New Order
          </button>
        </div>
      </div>
    );
  }

  // ── Main POS layout ────────────────────────────────────────

  return (
    <div className="flex gap-6 h-[calc(100vh-7rem)]">
      {/* ── LEFT: Product Browser ─────────────────────────────── */}
      <div className="flex-1 flex flex-col min-w-0">
        <div className="flex items-center gap-3 mb-4">
          <h1 className="text-xl font-bold text-gray-900 whitespace-nowrap">New Order</h1>
          <div className="relative flex-1">
            <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input
              type="text"
              placeholder="Search products..."
              value={productSearch}
              onChange={(e) => handleProductSearch(e.target.value)}
              className="w-full pl-9 pr-4 py-2.5 rounded-lg border border-gray-200 text-sm focus:border-brand-500 focus:ring-1 focus:ring-brand-500 outline-none"
            />
          </div>
        </div>

        <div className="flex-1 overflow-y-auto -mr-2 pr-2">
          {productsLoading ? (
            <div className="flex items-center gap-2 text-gray-400 py-8 justify-center">
              <Loader2 size={16} className="animate-spin" /> Loading products...
            </div>
          ) : (products ?? []).length === 0 ? (
            <div className="text-center py-12 text-gray-400">
              <Leaf size={32} className="mx-auto mb-2 opacity-50" />
              <p>No products found</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
              {(products ?? []).map((product) => (
                <div key={product.id} className="bg-white rounded-xl border border-gray-100 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <h3 className="font-semibold text-gray-900 text-sm truncate">{product.name}</h3>
                    {product.strainType && (
                      <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full shrink-0 ${STRAIN_COLORS[product.strainType] ?? STRAIN_COLORS.hybrid}`}>
                        {product.strainType}
                      </span>
                    )}
                  </div>
                  <div className="flex gap-3 text-xs text-gray-500 mb-3">
                    {product.thcPercent != null && <span>THC {product.thcPercent}%</span>}
                    {product.cbdPercent != null && <span>CBD {product.cbdPercent}%</span>}
                  </div>
                  <div className="space-y-1.5">
                    {product.variants.map((v) => {
                      const price = v.retailPrice ? Number(v.retailPrice) : 0;
                      const stock = v.stockQuantity != null ? Number(v.stockQuantity) : null;
                      const oos = v.stockStatus === 'out_of_stock' || stock === 0;
                      const inCart = cart.find((i) => i.variantId === v.variantId);

                      return (
                        <div
                          key={v.variantId}
                          className={`flex items-center justify-between py-1.5 px-2 rounded-lg ${oos ? 'opacity-40' : 'hover:bg-gray-50'}`}
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <span className="text-xs text-gray-700 font-medium truncate">{v.name}</span>
                            {v.quantityPerUnit && (
                              <span className="text-[10px] text-gray-400">{v.quantityPerUnit}g</span>
                            )}
                            {stock != null && stock <= 5 && stock > 0 && (
                              <span className="text-[10px] text-amber-600 font-medium">{stock} left</span>
                            )}
                          </div>
                          <div className="flex items-center gap-2 shrink-0">
                            <span className="text-sm font-bold text-gray-900 tabular-nums">
                              {price > 0 ? `$${price.toFixed(2)}` : '—'}
                            </span>
                            {oos ? (
                              <span className="text-[10px] text-red-500 font-medium w-16 text-center">Sold Out</span>
                            ) : (
                              <button
                                onClick={() => addToCart(product, v)}
                                disabled={inCart != null && inCart.quantity >= (stock ?? 999)}
                                className={`p-1.5 rounded-lg transition-colors ${
                                  inCart
                                    ? 'bg-brand-100 text-brand-700'
                                    : 'bg-brand-600 text-white hover:bg-brand-700'
                                } disabled:opacity-40 disabled:cursor-not-allowed`}
                              >
                                <Plus size={14} />
                              </button>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* ── RIGHT: Cart + Customer ────────────────────────────── */}
      <div className="w-96 flex flex-col bg-white rounded-xl border border-gray-100 overflow-hidden shrink-0">

        {/* Customer Section */}
        <div className="p-4 border-b border-gray-100">
          {customer ? (
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-brand-50 rounded-full">
                  <User size={16} className="text-brand-600" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-900">
                    {customer.firstName} {customer.lastName}
                  </p>
                  <p className="text-xs text-gray-500">
                    {customer.phone || customer.email}
                  </p>
                </div>
              </div>
              <button
                onClick={() => { setCustomer(null); setShowCustSearch(true); }}
                className="text-xs text-gray-400 hover:text-gray-600"
              >
                Change
              </button>
            </div>
          ) : (
            <div>
              <div className="relative">
                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search customer by name, phone, email..."
                  value={custSearch}
                  onChange={(e) => { handleCustSearch(e.target.value); setShowCustSearch(true); }}
                  onFocus={() => setShowCustSearch(true)}
                  className="w-full pl-9 pr-4 py-2.5 rounded-lg border border-gray-200 text-sm focus:border-brand-500 focus:ring-1 focus:ring-brand-500 outline-none"
                />
              </div>

              {/* Customer search results */}
              {showCustSearch && debouncedCust.length >= 2 && (
                <div className="mt-2 border border-gray-100 rounded-lg overflow-hidden max-h-48 overflow-y-auto">
                  {(custResults ?? []).map((c) => (
                    <button
                      key={c.userId}
                      onClick={() => { setCustomer(c); setShowCustSearch(false); setCustSearch(''); setDebouncedCust(''); }}
                      className="w-full text-left px-3 py-2.5 hover:bg-gray-50 border-b border-gray-50 last:border-0"
                    >
                      <p className="text-sm font-medium text-gray-900">
                        {c.firstName} {c.lastName}
                      </p>
                      <p className="text-xs text-gray-500">
                        {c.phone && `${c.phone} · `}{c.email}
                        {c.totalOrders > 0 && ` · ${c.totalOrders} orders`}
                      </p>
                    </button>
                  ))}
                  {(custResults ?? []).length === 0 && (
                    <div className="px-3 py-4 text-center text-xs text-gray-400">
                      No customers found for "{debouncedCust}"
                    </div>
                  )}
                </div>
              )}

              {/* New customer button/form */}
              {!showNewCustForm ? (
                <button
                  onClick={() => setShowNewCustForm(true)}
                  className="mt-2 w-full flex items-center justify-center gap-2 py-2 text-sm text-brand-600 font-medium border border-dashed border-brand-300 rounded-lg hover:bg-brand-50 transition-colors"
                >
                  <UserPlus size={14} /> New Walk-In Customer
                </button>
              ) : (
                <div className="mt-2 border border-gray-200 rounded-lg p-3 space-y-2">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-gray-700">New Customer</span>
                    <button onClick={() => setShowNewCustForm(false)} className="text-gray-400 hover:text-gray-600">
                      <X size={14} />
                    </button>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <input
                      placeholder="First name *"
                      value={newCust.firstName}
                      onChange={(e) => setNewCust((p) => ({ ...p, firstName: e.target.value }))}
                      className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:border-brand-500"
                    />
                    <input
                      placeholder="Last name"
                      value={newCust.lastName}
                      onChange={(e) => setNewCust((p) => ({ ...p, lastName: e.target.value }))}
                      className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:border-brand-500"
                    />
                  </div>
                  <input
                    placeholder="Phone"
                    value={newCust.phone}
                    onChange={(e) => setNewCust((p) => ({ ...p, phone: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:border-brand-500"
                  />
                  <input
                    placeholder="Email (optional)"
                    value={newCust.email}
                    onChange={(e) => setNewCust((p) => ({ ...p, email: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:border-brand-500"
                  />
                  <button
                    onClick={() => createCustomer.mutate()}
                    disabled={!newCust.firstName.trim() || createCustomer.isPending}
                    className="w-full bg-brand-600 text-white text-sm font-semibold py-2 rounded-lg hover:bg-brand-700 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {createCustomer.isPending ? 'Creating...' : 'Create Customer'}
                  </button>
                  {createCustomer.isError && (
                    <p className="text-xs text-red-500">{(createCustomer.error as Error).message}</p>
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Cart Items */}
        <div className="flex-1 overflow-y-auto p-4">
          {cart.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-gray-300">
              <ShoppingCart size={32} className="mb-2" />
              <p className="text-sm">Add products to the order</p>
            </div>
          ) : (
            <div className="space-y-3">
              {cart.map((item) => (
                <div key={item.variantId} className="flex items-start gap-3">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-900 truncate">{item.productName}</p>
                    <p className="text-xs text-gray-500">{item.variantName}</p>
                    <p className="text-xs text-gray-400">${item.price.toFixed(2)} each</p>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <button
                      onClick={() => updateQty(item.variantId, item.quantity - 1)}
                      className="p-1 rounded border border-gray-200 text-gray-500 hover:bg-gray-50"
                    >
                      <Minus size={12} />
                    </button>
                    <span className="w-7 text-center text-sm font-semibold tabular-nums">{item.quantity}</span>
                    <button
                      onClick={() => updateQty(item.variantId, item.quantity + 1)}
                      disabled={item.quantity >= item.maxStock}
                      className="p-1 rounded border border-gray-200 text-gray-500 hover:bg-gray-50 disabled:opacity-30"
                    >
                      <Plus size={12} />
                    </button>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-sm font-bold tabular-nums">${(item.price * item.quantity).toFixed(2)}</p>
                    <button
                      onClick={() => removeFromCart(item.variantId)}
                      className="text-gray-300 hover:text-red-500 transition-colors mt-0.5"
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Cart Footer */}
        <div className="border-t border-gray-100 p-4 space-y-3">
          <div className="flex justify-between text-sm">
            <span className="text-gray-500">Subtotal ({cartCount} items)</span>
            <span className="font-bold tabular-nums">${cartTotal.toFixed(2)}</span>
          </div>
          <div className="flex justify-between text-xs text-gray-400">
            <span>Tax calculated at order creation</span>
          </div>

          {/* Validation warnings */}
          {!customer && cart.length > 0 && (
            <div className="flex items-center gap-2 text-xs text-amber-600 bg-amber-50 rounded-lg px-3 py-2">
              <AlertTriangle size={14} />
              Select or create a customer to place the order
            </div>
          )}

          <button
            onClick={() => placeOrder.mutate()}
            disabled={cart.length === 0 || !customer || placeOrder.isPending}
            className="w-full bg-brand-600 text-white font-bold text-base py-3.5 rounded-xl hover:bg-brand-500 transition-colors disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {placeOrder.isPending ? (
              <><Loader2 size={18} className="animate-spin" /> Placing Order...</>
            ) : (
              <><ShoppingCart size={18} /> Place Order — ${cartTotal.toFixed(2)}</>
            )}
          </button>

          {placeOrder.isError && (
            <p className="text-xs text-red-500 text-center">
              {(placeOrder.error as Error).message}
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

export default NewOrderPage;

// packages/angular/projects/staff/src/app/features/new-order/new-order-page.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { toObservable } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged } from 'rxjs';
import {
  CreateOrderGQL,
  CreateWalkInCustomerGQL,
  ProductsGQL,
  SearchCustomersGQL,
} from '@cannasaas/ui-ng';
import { AuthService } from '../../core/auth/auth.service';

interface Variant {
  readonly variantId: string;
  readonly name: string;
  readonly retailPrice: number | null;
  readonly stockQuantity: number | null;
  readonly stockStatus: string | null;
}

interface Product {
  readonly id: string;
  readonly name: string;
  readonly strainType: string | null;
  readonly thcPercent: number | null;
  readonly cbdPercent: number | null;
  readonly variants: readonly Variant[];
}

interface CustomerResult {
  readonly userId: string;
  readonly email: string;
  readonly firstName: string | null;
  readonly lastName: string | null;
  readonly phone: string | null;
  readonly ageVerified: boolean;
  readonly totalOrders: number;
}

interface CartItem {
  readonly productId: string;
  readonly variantId: string;
  readonly productName: string;
  readonly variantName: string;
  readonly price: number;
  quantity: number;
  readonly maxStock: number;
}

interface OrderResult {
  readonly orderId: string;
  readonly orderStatus: string;
  readonly subtotal: number;
  readonly taxTotal: number;
  readonly total: number;
  readonly lineItemCount: number;
}

@Component({
  selector: 'cs-new-order-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
  template: `
    @if (orderResult(); as result) {
      <section
        class="mx-auto max-w-lg rounded-2xl border border-(--color-border) bg-(--color-surface) p-8 text-center"
      >
        <h2 class="text-2xl font-bold">Order Placed</h2>
        <p class="mt-1 text-sm text-(--color-text-muted)">
          #{{ result.orderId.slice(0, 8).toUpperCase() }}
        </p>
        <dl class="mt-6 space-y-1 text-sm">
          <div class="flex justify-between">
            <dt>Items</dt>
            <dd>{{ result.lineItemCount }}</dd>
          </div>
          <div class="flex justify-between">
            <dt>Subtotal</dt>
            <dd class="tabular-nums">\${{ result.subtotal.toFixed(2) }}</dd>
          </div>
          <div class="flex justify-between">
            <dt>Tax</dt>
            <dd class="tabular-nums">\${{ result.taxTotal.toFixed(2) }}</dd>
          </div>
          <div class="flex justify-between border-t border-(--color-border) pt-2 text-lg font-bold">
            <dt>Total</dt>
            <dd class="tabular-nums">\${{ result.total.toFixed(2) }}</dd>
          </div>
        </dl>
        <button
          type="button"
          class="mt-6 rounded-xl bg-(--color-primary) px-8 py-3 font-semibold text-white hover:bg-(--color-primary-hover)"
          (click)="startNewOrder()"
        >
          New Order
        </button>
      </section>
    } @else {
      <div class="grid h-[calc(100vh-7rem)] grid-cols-1 gap-6 lg:grid-cols-[1fr_22rem]">
        <!-- LEFT: Product browser -->
        <section class="flex min-w-0 flex-col">
          <header class="mb-4 flex items-center gap-3">
            <h1 class="text-xl font-bold whitespace-nowrap">New Order</h1>
            <input
              type="text"
              placeholder="Search products…"
              class="min-h-11 flex-1 rounded-lg border border-(--color-border) bg-(--color-surface) px-3 py-2 text-sm"
              [ngModel]="productSearch()"
              (ngModelChange)="productSearch.set($event)"
            />
          </header>
          <div class="-mr-2 flex-1 overflow-y-auto pr-2">
            @if (productsLoading()) {
              <p class="py-8 text-center text-sm text-(--color-text-muted)">Loading products…</p>
            } @else if (products().length === 0) {
              <p class="py-12 text-center text-sm text-(--color-text-muted)">No products found</p>
            } @else {
              <ul class="grid grid-cols-1 gap-3 lg:grid-cols-2">
                @for (product of products(); track product.id) {
                  <li class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4">
                    <div class="mb-2 flex items-center gap-2">
                      <h3 class="truncate text-sm font-semibold">{{ product.name }}</h3>
                      @if (product.strainType) {
                        <span
                          class="shrink-0 rounded-full bg-(--color-surface-alt) px-2 py-0.5 text-[10px] font-semibold uppercase"
                        >
                          {{ product.strainType }}
                        </span>
                      }
                    </div>
                    <p class="mb-3 flex gap-3 text-xs text-(--color-text-muted)">
                      @if (product.thcPercent != null) {
                        <span>THC {{ product.thcPercent }}%</span>
                      }
                      @if (product.cbdPercent != null) {
                        <span>CBD {{ product.cbdPercent }}%</span>
                      }
                    </p>
                    <ul class="space-y-1.5">
                      @for (variant of product.variants; track variant.variantId) {
                        @let oos = isOutOfStock(variant);
                        @let inCart = cartItemFor(variant.variantId);
                        <li
                          class="flex items-center justify-between rounded-lg px-2 py-1.5"
                          [class.opacity-40]="oos"
                        >
                          <span class="min-w-0 truncate text-xs font-medium">
                            {{ variant.name }}
                          </span>
                          <span class="flex shrink-0 items-center gap-2">
                            <span class="text-sm font-bold tabular-nums">
                              {{ formatPrice(variant.retailPrice) }}
                            </span>
                            @if (oos) {
                              <span class="w-16 text-center text-[10px] font-medium text-rose-600">
                                Sold Out
                              </span>
                            } @else {
                              <button
                                type="button"
                                class="min-h-9 rounded-md bg-(--color-primary) px-3 text-sm font-semibold text-white disabled:opacity-50"
                                [disabled]="
                                  inCart != null && inCart.quantity >= maxStockFor(variant)
                                "
                                (click)="addToCart(product, variant)"
                              >
                                Add
                              </button>
                            }
                          </span>
                        </li>
                      }
                    </ul>
                  </li>
                }
              </ul>
            }
          </div>
        </section>

        <!-- RIGHT: Cart + customer -->
        <aside
          class="flex min-h-0 flex-col rounded-xl border border-(--color-border) bg-(--color-surface) p-4"
        >
          <div class="mb-4 border-b border-(--color-border) pb-4">
            <h2 class="mb-2 text-sm font-semibold uppercase text-(--color-text-muted)">Customer</h2>
            @if (customer(); as c) {
              <div class="flex items-center justify-between">
                <span class="text-sm">
                  @if (isWalkIn(c)) {
                    Walk-in customer
                  } @else {
                    {{ c.firstName }} {{ c.lastName }}
                  }
                </span>
                <button
                  type="button"
                  class="text-xs text-(--color-text-muted) underline"
                  (click)="clearCustomer()"
                >
                  Change
                </button>
              </div>
            } @else {
              <div class="space-y-2">
                <input
                  type="text"
                  placeholder="Search by name/phone/email…"
                  class="min-h-11 w-full rounded-md border border-(--color-border) bg-(--color-surface) px-3 py-2 text-sm"
                  [ngModel]="customerSearch()"
                  (ngModelChange)="customerSearch.set($event)"
                />
                @if (customerResults().length > 0) {
                  <ul class="max-h-40 overflow-y-auto rounded-md border border-(--color-border)">
                    @for (c of customerResults(); track c.userId) {
                      <li>
                        <button
                          type="button"
                          class="block w-full px-3 py-2 text-left text-xs hover:bg-(--color-surface-hover)"
                          (click)="selectCustomer(c)"
                        >
                          {{ c.firstName }} {{ c.lastName }}
                          <span class="block text-(--color-text-muted)">{{ c.phone }}</span>
                        </button>
                      </li>
                    }
                  </ul>
                }
                <button
                  type="button"
                  class="min-h-11 w-full rounded-md border border-(--color-border) px-3 py-2 text-sm font-medium hover:bg-(--color-surface-hover) disabled:opacity-50"
                  [disabled]="walkinCreating()"
                  (click)="createWalkIn()"
                >
                  @if (walkinCreating()) {
                    Creating…
                  } @else {
                    + Walk-in customer
                  }
                </button>
              </div>
            }
          </div>

          <div class="mb-4 flex items-center justify-between">
            <h2 class="text-sm font-semibold uppercase text-(--color-text-muted)">
              Cart ({{ cartCount() }})
            </h2>
            @if (cart().length > 0) {
              <button
                type="button"
                class="text-xs text-(--color-text-muted) underline"
                (click)="emptyCart()"
              >
                Empty
              </button>
            }
          </div>

          <ul class="-mx-2 flex-1 overflow-y-auto px-2">
            @for (item of cart(); track item.variantId) {
              <li class="mb-2 flex items-start gap-2 rounded-md border border-(--color-border) p-2">
                <div class="min-w-0 flex-1">
                  <p class="truncate text-sm font-medium">{{ item.productName }}</p>
                  <p class="truncate text-xs text-(--color-text-muted)">
                    {{ item.variantName }} · \${{ item.price.toFixed(2) }}
                  </p>
                </div>
                <div class="flex shrink-0 items-center gap-1">
                  <button
                    type="button"
                    class="min-h-9 w-9 rounded-md border border-(--color-border)"
                    (click)="updateQty(item.variantId, item.quantity - 1)"
                  >
                    −
                  </button>
                  <span class="w-8 text-center text-sm tabular-nums">
                    {{ item.quantity }}
                  </span>
                  <button
                    type="button"
                    class="min-h-9 w-9 rounded-md border border-(--color-border) disabled:opacity-50"
                    [disabled]="item.quantity >= item.maxStock"
                    (click)="updateQty(item.variantId, item.quantity + 1)"
                  >
                    +
                  </button>
                </div>
              </li>
            } @empty {
              <li class="py-6 text-center text-sm text-(--color-text-muted)">Cart is empty</li>
            }
          </ul>

          <div class="mt-4 border-t border-(--color-border) pt-4">
            <p class="mb-3 flex justify-between text-lg font-bold">
              <span>Total</span>
              <span class="tabular-nums">\${{ cartTotal().toFixed(2) }}</span>
            </p>
            @if (errorMessage(); as err) {
              <p class="mb-2 text-sm text-rose-600">{{ err }}</p>
            }
            <button
              type="button"
              class="min-h-11 w-full rounded-md bg-(--color-primary) px-4 py-2 font-semibold text-white hover:bg-(--color-primary-hover) disabled:cursor-not-allowed disabled:opacity-50"
              [disabled]="!canPlaceOrder()"
              (click)="placeOrder()"
            >
              @if (placing()) {
                Placing…
              } @else {
                Place Order
              }
            </button>
          </div>
        </aside>
      </div>
    }
  `,
})
export class NewOrderPage {
  private readonly auth = inject(AuthService);
  private readonly productsGQL = inject(ProductsGQL);
  private readonly searchCustomersGQL = inject(SearchCustomersGQL);
  private readonly createWalkInGQL = inject(CreateWalkInCustomerGQL);
  private readonly createOrderGQL = inject(CreateOrderGQL);

  protected readonly productSearch = signal('');
  protected readonly customerSearch = signal('');
  protected readonly cart = signal<CartItem[]>([]);
  protected readonly customer = signal<CustomerResult | null>(null);
  protected readonly orderResult = signal<OrderResult | null>(null);
  protected readonly errorMessage = signal<string | null>(null);
  protected readonly walkinCreating = signal(false);
  protected readonly placing = signal(false);

  protected readonly products = signal<readonly Product[]>([]);
  protected readonly productsLoading = signal(false);
  protected readonly customerResults = signal<readonly CustomerResult[]>([]);

  private readonly debouncedProductSearch = toSignal(
    toObservable(this.productSearch).pipe(debounceTime(250), distinctUntilChanged()),
    { initialValue: '' },
  );

  private readonly debouncedCustomerSearch = toSignal(
    toObservable(this.customerSearch).pipe(debounceTime(300), distinctUntilChanged()),
    { initialValue: '' },
  );

  private readonly dispensaryId = computed(() => this.auth.user()?.dispensaryId ?? null);

  protected readonly cartTotal = computed(() =>
    this.cart().reduce((sum, i) => sum + i.price * i.quantity, 0),
  );

  protected readonly cartCount = computed(() =>
    this.cart().reduce((sum, i) => sum + i.quantity, 0),
  );

  protected readonly canPlaceOrder = computed(() => {
    if (this.placing()) return false;
    if (this.cart().length === 0) return false;
    if (!this.customer()) return false;
    return true;
  });

  constructor() {
    effect(() => {
      const id = this.dispensaryId();
      const search = this.debouncedProductSearch();
      if (!id) return;
      void this.loadProducts(id, search);
    });

    effect(() => {
      const id = this.dispensaryId();
      const q = this.debouncedCustomerSearch();
      if (!id || q.length < 2) {
        this.customerResults.set([]);
        return;
      }
      void this.loadCustomers(id, q);
    });
  }

  private async loadProducts(dispensaryId: string, search: string): Promise<void> {
    this.productsLoading.set(true);
    try {
      const result = await this.productsGQL
        .fetch({
          variables: {
            dispensaryId,
            search: search || undefined,
            limit: 30,
          },
          fetchPolicy: 'network-only',
        })
        .toPromise();
      const rows = (result?.data?.products ?? []) as unknown as Product[];
      this.products.set(rows);
    } catch {
      this.products.set([]);
    } finally {
      this.productsLoading.set(false);
    }
  }

  private async loadCustomers(dispensaryId: string, query: string): Promise<void> {
    try {
      const result = await this.searchCustomersGQL
        .fetch({
          variables: { dispensaryId, query, limit: 8 },
          fetchPolicy: 'network-only',
        })
        .toPromise();
      const rows = (result?.data?.searchCustomers ?? []) as unknown as CustomerResult[];
      this.customerResults.set(rows);
    } catch {
      this.customerResults.set([]);
    }
  }

  protected isOutOfStock(variant: Variant): boolean {
    if (variant.stockStatus === 'out_of_stock') return true;
    return variant.stockQuantity === 0;
  }

  protected maxStockFor(variant: Variant): number {
    return variant.stockQuantity ?? 999;
  }

  protected formatPrice(p: number | null): string {
    return p != null && p > 0 ? `$${p.toFixed(2)}` : '—';
  }

  protected cartItemFor(variantId: string): CartItem | undefined {
    return this.cart().find((i) => i.variantId === variantId);
  }

  protected isWalkIn(c: CustomerResult): boolean {
    return c.email.startsWith('walkin-');
  }

  protected addToCart(product: Product, variant: Variant): void {
    const price = variant.retailPrice ?? 0;
    const maxStock = this.maxStockFor(variant);
    if (maxStock <= 0) return;

    const existing = this.cart().find((i) => i.variantId === variant.variantId);
    if (existing) {
      if (existing.quantity >= maxStock) return;
      this.cart.update((items) =>
        items.map((i) =>
          i.variantId === variant.variantId
            ? { ...i, quantity: Math.min(i.quantity + 1, maxStock) }
            : i,
        ),
      );
      return;
    }
    this.cart.update((items) => [
      ...items,
      {
        productId: product.id,
        variantId: variant.variantId,
        productName: product.name,
        variantName: variant.name,
        price,
        quantity: 1,
        maxStock,
      },
    ]);
  }

  protected updateQty(variantId: string, qty: number): void {
    if (qty <= 0) {
      this.cart.update((items) => items.filter((i) => i.variantId !== variantId));
      return;
    }
    this.cart.update((items) =>
      items.map((i) =>
        i.variantId === variantId ? { ...i, quantity: Math.min(qty, i.maxStock) } : i,
      ),
    );
  }

  protected emptyCart(): void {
    this.cart.set([]);
  }

  protected selectCustomer(c: CustomerResult): void {
    this.customer.set(c);
    this.customerSearch.set('');
    this.customerResults.set([]);
  }

  protected clearCustomer(): void {
    this.customer.set(null);
  }

  protected async createWalkIn(): Promise<void> {
    const id = this.dispensaryId();
    if (!id || this.walkinCreating()) return;
    this.walkinCreating.set(true);
    try {
      const result = await this.createWalkInGQL
        .mutate({
          variables: {
            input: {
              dispensaryId: id,
              firstName: '',
              lastName: '',
            },
          },
        })
        .toPromise();
      const c = result?.data?.createWalkInCustomer as unknown as CustomerResult | undefined;
      if (!c) throw new Error('Walk-in creation returned no customer');
      this.customer.set(c);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to create walk-in';
      this.errorMessage.set(message);
    } finally {
      this.walkinCreating.set(false);
    }
  }

  protected async placeOrder(): Promise<void> {
    const id = this.dispensaryId();
    const c = this.customer();
    if (!id || !c || this.placing() || this.cart().length === 0) return;

    this.placing.set(true);
    this.errorMessage.set(null);
    try {
      const result = await this.createOrderGQL
        .mutate({
          variables: {
            input: {
              dispensaryId: id,
              customerUserId: c.userId,
              orderType: 'in_store',
              lineItems: this.cart().map((i) => ({
                productId: i.productId,
                variantId: i.variantId,
                quantity: i.quantity,
              })),
            },
          },
        })
        .toPromise();
      const order = result?.data?.createOrder;
      if (!order) throw new Error('Order creation returned no result');
      this.orderResult.set({
        orderId: order.orderId,
        orderStatus: order.orderStatus,
        subtotal: Number(order.subtotal),
        taxTotal: Number(order.taxTotal),
        total: Number(order.total),
        lineItemCount: order.lineItemCount,
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to place order';
      this.errorMessage.set(message);
    } finally {
      this.placing.set(false);
    }
  }

  protected startNewOrder(): void {
    this.cart.set([]);
    this.customer.set(null);
    this.orderResult.set(null);
    this.productSearch.set('');
    this.customerSearch.set('');
    this.errorMessage.set(null);
    this.customerResults.set([]);
  }
}
