// packages/angular/projects/kiosk/src/app/pages/cart/cart-page.ts
import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { CartService, type CartItem } from '../../core/cart/cart.service';

@Component({
  selector: 'cs-cart-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CurrencyPipe, RouterLink],
  template: `
    @if (cart.isEmpty()) {
      <div class="flex h-[60vh] flex-col items-center justify-center">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="64"
          height="64"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="mb-4 text-gray-300"
        >
          <circle cx="8" cy="21" r="1" />
          <circle cx="19" cy="21" r="1" />
          <path
            d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"
          />
        </svg>
        <p class="mb-6 text-xl text-gray-400">Your cart is empty</p>
        <a
          routerLink="/"
          class="rounded-full bg-emerald-600 px-8 py-4 text-lg font-semibold text-white active:bg-emerald-800"
        >
          Browse Menu
        </a>
      </div>
    } @else {
      <div class="mx-auto max-w-2xl p-6">
        <h1 class="mb-6 text-2xl font-bold text-gray-900">Your Cart</h1>

        <div class="space-y-3">
          @for (item of cart.items(); track item.variantId) {
            <div
              class="flex items-center gap-4 rounded-2xl border border-gray-100 bg-white p-4"
            >
              <div class="flex-1">
                <p class="text-lg font-semibold text-gray-900">{{ item.name }}</p>
                <p class="text-sm text-gray-500">
                  {{ item.variantName }} · {{ item.price | currency }} each
                </p>
              </div>
              <div
                class="flex items-center gap-2 rounded-full border border-gray-200"
              >
                <button
                  type="button"
                  (click)="dec(item)"
                  aria-label="Decrease quantity"
                  class="p-3 active:bg-gray-100"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M5 12h14" />
                  </svg>
                </button>
                <span class="px-2 text-lg font-bold tabular-nums">
                  {{ item.quantity }}
                </span>
                <button
                  type="button"
                  (click)="inc(item)"
                  aria-label="Increase quantity"
                  class="p-3 active:bg-gray-100"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M5 12h14" />
                    <path d="M12 5v14" />
                  </svg>
                </button>
              </div>
              <p class="w-20 text-right text-lg font-bold tabular-nums">
                {{ item.price * item.quantity | currency }}
              </p>
              <button
                type="button"
                (click)="remove(item)"
                aria-label="Remove from cart"
                class="p-2 text-red-400 active:text-red-700"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M3 6h18" />
                  <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
                  <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                  <line x1="10" x2="10" y1="11" y2="17" />
                  <line x1="14" x2="14" y1="11" y2="17" />
                </svg>
              </button>
            </div>
          }
        </div>

        <div class="mt-8 rounded-2xl border border-gray-100 bg-white p-6">
          <div class="flex justify-between text-xl font-bold">
            <span>Subtotal</span>
            <span class="tabular-nums">{{ cart.subtotal() | currency }}</span>
          </div>
          <p class="mt-1 text-sm text-gray-400">Tax calculated at checkout</p>
          <button
            type="button"
            (click)="checkout()"
            class="mt-4 flex w-full items-center justify-center gap-2 rounded-full bg-emerald-600 py-4 text-lg font-bold text-white active:bg-emerald-800"
          >
            Checkout
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M5 12h14" />
              <path d="m12 5 7 7-7 7" />
            </svg>
          </button>
        </div>
      </div>
    }
  `,
})
export class CartPage {
  protected readonly cart = inject(CartService);
  private readonly router = inject(Router);

  protected inc(item: CartItem): void {
    this.cart.updateQuantity(item.variantId, item.quantity + 1);
  }

  protected dec(item: CartItem): void {
    this.cart.updateQuantity(item.variantId, item.quantity - 1);
  }

  protected remove(item: CartItem): void {
    void this.cart.removeItem(item.variantId);
  }

  protected checkout(): void {
    this.router.navigateByUrl('/checkout');
  }
}

// apps/kiosk/src/pages/CartPage.tsx
// === CartPage.tsx ===
import { useNavigate } from 'react-router-dom';
import { useCartStore } from '../stores/cart.store';
import { Trash2, Minus, Plus, ShoppingCart, ArrowRight } from 'lucide-react';

export function CartPage() {
  const navigate = useNavigate();
  const { items, updateQuantity, removeItem, subtotal, clearCart } = useCartStore();
  const total = subtotal();

  if (items.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh]">
        <ShoppingCart size={64} className="text-gray-300 mb-4" />
        <p className="text-xl text-gray-400 mb-6">Your cart is empty</p>
        <button onClick={() => navigate('/')} className="bg-emerald-600 text-white text-lg font-semibold px-8 py-4 rounded-full hover:bg-emerald-700">
          Browse Menu
        </button>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-2xl mx-auto">
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Your Cart</h1>

      <div className="space-y-3">
        {items.map((item) => (
          <div key={item.variantId} className="bg-white rounded-full border border-gray-100 p-4 flex items-center gap-4">
            <div className="flex-1">
              <p className="font-semibold text-gray-900 text-lg">{item.name}</p>
              <p className="text-sm text-gray-500">{item.variantName} · ${item.price.toFixed(2)} each</p>
            </div>
            <div className="flex items-center gap-2 border border-gray-200 rounded-full">
              <button onClick={() => updateQuantity(item.variantId, item.quantity - 1)} className="p-3"><Minus size={18} /></button>
              <span className="px-2 text-lg font-bold tabular-nums">{item.quantity}</span>
              <button onClick={() => updateQuantity(item.variantId, item.quantity + 1)} className="p-3"><Plus size={18} /></button>
            </div>
            <p className="text-lg font-bold tabular-nums w-20 text-right">${(item.price * item.quantity).toFixed(2)}</p>
            <button onClick={() => removeItem(item.variantId)} className="p-2 text-red-400 hover:text-red-600"><Trash2 size={20} /></button>
          </div>
        ))}
      </div>

      <div className="mt-8 bg-white rounded-full border border-gray-100 p-6">
        <div className="flex justify-between text-xl font-bold">
          <span>Subtotal</span>
          <span className="tabular-nums">${total.toFixed(2)}</span>
        </div>
        <p className="text-sm text-gray-400 mt-1">Tax calculated at checkout</p>
        <button onClick={() => navigate('/checkout')}
          className="w-full mt-4 bg-emerald-600 text-white text-lg font-bold py-4 rounded-full hover:bg-emerald-700 active:bg-emerald-800 flex items-center justify-center gap-2">
          Checkout <ArrowRight size={20} />
        </button>
      </div>
    </div>
  );
}
