// packages/angular/projects/kiosk/src/app/pages/checkout/checkout-page.ts
import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { CreateOrderGQL } from '@cannasaas/ui-ng';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { CartService } from '../../core/cart/cart.service';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'cs-checkout-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CurrencyPipe],
  template: `
    @if (cart.isEmpty()) {
      <div class="flex h-[60vh] flex-col items-center justify-center text-gray-400">
        <p class="mb-4 text-xl">Your cart is empty.</p>
        <button
          type="button"
          (click)="goHome()"
          class="rounded-full bg-emerald-600 px-8 py-4 text-lg font-semibold text-white active:bg-emerald-800"
        >
          Browse Menu
        </button>
      </div>
    } @else {
      <div class="mx-auto max-w-lg p-6">
        <h1 class="mb-6 text-2xl font-bold text-gray-900">Checkout</h1>

        <div class="mb-6 rounded-2xl border border-gray-100 bg-white p-6">
          <h2 class="mb-3 font-semibold text-gray-900">Order Summary</h2>
          @for (i of cart.items(); track i.variantId) {
            <div class="flex justify-between py-2 text-sm">
              <span>{{ i.name }} × {{ i.quantity }}</span>
              <span class="font-medium tabular-nums">
                {{ i.price * i.quantity | currency }}
              </span>
            </div>
          }
          <div class="mt-3 flex justify-between border-t border-gray-100 pt-3 text-lg font-bold">
            <span>Total</span>
            <span class="tabular-nums">{{ cart.subtotal() | currency }}</span>
          </div>
          <p class="mt-1 text-xs text-gray-400">+ tax · Pay at counter</p>
        </div>

        @if (error(); as e) {
          <div
            class="mb-4 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-red-700"
            role="alert"
          >
            {{ e }}
          </div>
        }

        <button
          type="button"
          (click)="placeOrder()"
          [disabled]="loading()"
          class="flex w-full items-center justify-center gap-2 rounded-full bg-emerald-600 py-5 text-lg font-bold text-white active:bg-emerald-800 disabled:opacity-50"
        >
          @if (loading()) {
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="22"
              height="22"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="animate-spin"
            >
              <path d="M21 12a9 9 0 1 1-6.219-8.56" />
            </svg>
            Placing Order...
          } @else {
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="22"
              height="22"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M20 6 9 17l-5-5" />
            </svg>
            Place Order — Pay at Counter
          }
        </button>
      </div>
    }
  `,
})
export class CheckoutPage {
  protected readonly cart = inject(CartService);
  private readonly router = inject(Router);
  private readonly createOrderGQL = inject(CreateOrderGQL);
  private readonly auth = inject(AuthService);

  protected readonly loading = signal(false);
  protected readonly error = signal<string | null>(null);

  protected goHome(): void {
    void this.router.navigateByUrl('/');
  }

  protected async placeOrder(): Promise<void> {
    if (this.cart.isEmpty() || this.loading()) return;
    this.loading.set(true);
    this.error.set(null);

    try {
      await this.auth.ensureLoggedIn();
      const lineItems = this.cart.items().map((i) => ({
        productId: i.productId,
        variantId: i.variantId,
        quantity: i.quantity,
      }));
      const result = await firstValueFrom(
        this.createOrderGQL.mutate({
          variables: {
            input: {
              dispensaryId: environment.dispensaryId,
              orderType: 'pickup',
              notes: 'Kiosk pre-order',
              lineItems,
            },
          },
        }),
      );
      const orderId = result.data?.createOrder?.orderId;
      if (orderId) {
        this.cart.clearCart();
        void this.router.navigateByUrl(`/confirm/${orderId}`);
      } else {
        this.error.set('Order failed — please try again');
      }
    } catch (err: unknown) {
      this.error.set(err instanceof Error ? err.message : 'Order failed');
    } finally {
      this.loading.set(false);
    }
  }
}

// apps/kiosk/src/pages/CheckoutPage.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCartStore } from '../stores/cart.store';
import { gql, DISPENSARY_ID } from '../lib/graphql';
import { Check, Loader2 } from 'lucide-react';

const CREATE_ORDER = `mutation($input: CreateOrderInput!) { createOrder(input: $input) { orderId dispensaryId orderStatus total taxTotal } }`;

export function CheckoutPage() {
  const navigate = useNavigate();
  const { items, subtotal, clearCart } = useCartStore();
  const [name, setName] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const total = subtotal();

  const handleOrder = async () => {
    if (!name.trim()) { setError('Please enter your name'); return; }
    setLoading(true);
    setError('');
    try {
      const input = {
        dispensaryId: DISPENSARY_ID,
        orderType: 'pickup',
        notes: 'Kiosk order for: ' + name.trim(),
        lineItems: items.map((i) => ({ productId: i.productId, variantId: i.variantId, quantity: i.quantity })),
      };
      const data = await gql<any>(CREATE_ORDER, { input });
      if (data.createOrder) {
        clearCart();
        navigate('/confirm/' + data.createOrder.orderId);
      } else {
        setError('Order failed — please try again');
      }
    } catch (err: any) {
      setError(err.message || 'Order failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 max-w-lg mx-auto">
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Checkout</h1>

      <div className="bg-white rounded-full border border-gray-100 p-6 mb-6">
        <h2 className="font-semibold text-gray-900 mb-3">Order Summary</h2>
        {items.map((i) => (
          <div key={i.variantId} className="flex justify-between py-2 text-sm">
            <span>{i.name} x {i.quantity}</span>
            <span className="tabular-nums font-medium">${(i.price * i.quantity).toFixed(2)}</span>
          </div>
        ))}
        <div className="border-t border-gray-100 mt-3 pt-3 flex justify-between text-lg font-bold">
          <span>Total</span>
          <span className="tabular-nums">${total.toFixed(2)}</span>
        </div>
        <p className="text-xs text-gray-400 mt-1">+ tax · Pay at counter</p>
      </div>

      <div className="bg-white rounded-full border border-gray-100 p-6 mb-6">
        <label className="block text-sm font-medium text-gray-700 mb-2">Your Name (for pickup)</label>
        <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="First name"
          className="w-full px-4 py-4 border border-gray-200 rounded-full text-lg focus:outline-none focus:ring-2 focus:ring-emerald-500"
          autoFocus />
      </div>

      {error && <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-full mb-4">{error}</div>}

      <button onClick={handleOrder} disabled={loading}
        className="w-full bg-emerald-600 text-white text-lg font-bold py-5 rounded-full hover:bg-emerald-700 active:bg-emerald-800 disabled:opacity-50 flex items-center justify-center gap-2">
        {loading ? <><Loader2 size={22} className="animate-spin" /> Placing Order...</> : <><Check size={22} /> Place Order</>}
      </button>
    </div>
  );
}
