// packages/angular/projects/kiosk/src/app/pages/product/product-page.ts
import { CurrencyPipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { rxResource, toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductGQL, type ProductQuery } from '@cannasaas/ui-ng';
import { map, of } from 'rxjs';
import { CartService } from '../../core/cart/cart.service';
import { environment } from '../../../environments/environment';

type ApiProduct = NonNullable<ProductQuery['product']>;
type ApiVariant = ApiProduct['variants'][number];

interface StrainStyle {
  readonly bg: string;
  readonly badge: string;
  readonly orb: string;
}

const STRAIN_STYLE: Record<'sativa' | 'indica' | 'hybrid', StrainStyle> = {
  sativa: {
    bg: 'from-amber-100 via-orange-50 to-yellow-50',
    badge: 'bg-amber-500 text-white',
    orb: '#f59e0b',
  },
  indica: {
    bg: 'from-violet-100 via-purple-50 to-indigo-50',
    badge: 'bg-violet-500 text-white',
    orb: '#8b5cf6',
  },
  hybrid: {
    bg: 'from-emerald-100 via-green-50 to-teal-50',
    badge: 'bg-emerald-500 text-white',
    orb: '#10b981',
  },
};

const ADDED_RESET_MS = 1500;

function asStrainKey(value: string | null | undefined): 'sativa' | 'indica' | 'hybrid' {
  return value === 'sativa' || value === 'indica' || value === 'hybrid' ? value : 'hybrid';
}

function asStringArray(value: Record<string, unknown> | null | undefined): string[] {
  return Array.isArray(value) ? (value as string[]).filter((s) => typeof s === 'string') : [];
}

function priceOf(variant: ApiVariant | undefined): number {
  return typeof variant?.retailPrice === 'number' ? variant.retailPrice : 0;
}

function variantInStock(variant: ApiVariant | undefined): boolean {
  if (!variant || variant.isActive === false) return false;
  if (typeof variant.stockQuantity === 'number') return variant.stockQuantity > 0;
  return variant.stockStatus !== 'out_of_stock';
}

function variantStockQty(variant: ApiVariant | undefined): number {
  return typeof variant?.stockQuantity === 'number' ? Math.max(0, Math.floor(variant.stockQuantity)) : 0;
}

function hashCode(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i += 1) {
    hash = (((hash << 5) - hash) + str.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

@Component({
  selector: 'cs-product-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CurrencyPipe],
  template: `
    @if (loading()) {
      <div class="flex h-[60vh] items-center justify-center">
        <div
          class="h-8 w-8 animate-spin rounded-full border-2 border-emerald-300 border-t-transparent"
        ></div>
      </div>
    } @else if (product(); as p) {
      @let strain = strainStyleFor(p.strainType);
      @let orb = orbStyle(p.name);
      @let active = activeVariant();
      @let qty = quantity();
      @let price = priceFor(active);
      @let effs = effectsOf(p);
      @let flavs = flavorsOf(p);
      @let stock = stockFor(active);
      @let inStock = stock > 0;
      @let canIncrease = qty < stock;
      <div class="mx-auto max-w-5xl p-6 lg:p-8">
        <div class="grid grid-cols-1 gap-8 md:grid-cols-2 lg:gap-12">
          <div
            class="relative aspect-square overflow-hidden rounded-3xl bg-linear-to-br"
            [class]="strain.bg"
          >
            <div
              class="absolute rounded-full opacity-20 blur-3xl"
              [style.width.%]="orb.size"
              [style.height.%]="orb.size"
              [style.top.%]="orb.top"
              [style.left.%]="orb.left"
              [style.background]="strain.orb"
            ></div>
            @if (p.strainType) {
              <span
                class="absolute top-5 left-5 rounded-full px-4 py-1.5 text-sm font-bold tracking-wider uppercase shadow-md"
                [class]="strain.badge"
              >
                {{ p.strainType }}
              </span>
            }
            <div class="absolute bottom-5 left-5 flex gap-2">
              @if (p.thcPercent !== null && p.thcPercent !== undefined) {
                <div
                  class="rounded-xl bg-white/90 px-4 py-2 shadow-sm backdrop-blur-sm"
                >
                  <span
                    class="text-[10px] tracking-wider text-gray-500 uppercase"
                  >
                    THC
                  </span>
                  <p class="text-lg font-bold text-gray-900">
                    {{ p.thcPercent }}%
                  </p>
                </div>
              }
              @if (p.cbdPercent !== null && p.cbdPercent !== undefined && p.cbdPercent > 0) {
                <div
                  class="rounded-xl bg-white/90 px-4 py-2 shadow-sm backdrop-blur-sm"
                >
                  <span
                    class="text-[10px] tracking-wider text-gray-500 uppercase"
                  >
                    CBD
                  </span>
                  <p class="text-lg font-bold text-gray-900">
                    {{ p.cbdPercent }}%
                  </p>
                </div>
              }
            </div>
          </div>

          <div class="flex flex-col justify-center">
            <h1
              class="text-3xl font-light text-gray-900 lg:text-4xl"
              style="font-family: 'Playfair Display', Georgia, serif;"
            >
              {{ p.name }}
            </h1>
            @if (p.strainName && p.strainName !== p.name) {
              <p class="mt-1 text-sm text-gray-400 italic">{{ p.strainName }}</p>
            }
            @if (p.description) {
              <p class="mt-5 leading-relaxed text-gray-500">{{ p.description }}</p>
            }

            @if (effs.length > 0) {
              <div class="mt-6">
                <p
                  class="mb-2 text-xs font-medium tracking-wider text-gray-400 uppercase"
                >
                  Effects
                </p>
                <div class="flex flex-wrap gap-2">
                  @for (e of effs; track e) {
                    <span
                      class="rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1.5 text-sm font-medium text-emerald-700"
                    >
                      {{ e }}
                    </span>
                  }
                </div>
              </div>
            }

            @if (flavs.length > 0) {
              <div class="mt-4">
                <p
                  class="mb-2 text-xs font-medium tracking-wider text-gray-400 uppercase"
                >
                  Flavors
                </p>
                <div class="flex flex-wrap gap-2">
                  @for (f of flavs; track f) {
                    <span
                      class="rounded-full border border-orange-100 bg-orange-50 px-3 py-1.5 text-sm font-medium text-orange-700"
                    >
                      {{ f }}
                    </span>
                  }
                </div>
              </div>
            }

            @if (p.variants.length > 1) {
              <div class="mt-6">
                <p
                  class="mb-2 text-xs font-medium tracking-wider text-gray-400 uppercase"
                >
                  Options
                </p>
                <div class="flex flex-wrap gap-2">
                  @for (v of p.variants; track v.variantId) {
                    @let vInStock = isVariantInStock(v);
                    <button
                      type="button"
                      [disabled]="!vInStock"
                      (click)="selectVariant(v.variantId)"
                      class="rounded-full border-2 px-5 py-3 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50"
                      [class.active:scale-95]="vInStock"
                      [class.border-emerald-500]="active?.variantId === v.variantId && vInStock"
                      [class.bg-emerald-50]="active?.variantId === v.variantId && vInStock"
                      [class.text-emerald-700]="active?.variantId === v.variantId && vInStock"
                      [class.border-gray-200]="active?.variantId !== v.variantId || !vInStock"
                      [class.text-gray-500]="active?.variantId !== v.variantId || !vInStock"
                    >
                      {{ v.name }}@if (!vInStock) {
                        <span class="ml-1 text-xs">(Sold out)</span>
                      }
                    </button>
                  }
                </div>
              </div>
            }

            <div class="mt-8 rounded-2xl bg-gray-50 p-6">
              <div class="mb-5 flex items-center justify-between">
                <span class="text-4xl font-bold text-gray-900">
                  {{ price | currency }}
                </span>
                @if (active && active.name && active.name !== 'Standard') {
                  <span class="text-sm text-gray-400">/ {{ active.name }}</span>
                }
              </div>

              @if (inStock) {
                <p class="mb-3 text-xs font-medium tracking-wider text-gray-400 uppercase">
                  {{ stock }} in stock
                </p>
              } @else {
                <p class="mb-3 text-xs font-medium tracking-wider text-red-600 uppercase">
                  Sold out
                </p>
              }

              <div class="flex items-center gap-4">
                <div
                  class="flex items-center rounded-full border border-gray-200 bg-white"
                >
                  <button
                    type="button"
                    (click)="dec()"
                    [disabled]="!inStock || qty <= 1"
                    aria-label="Decrease quantity"
                    class="rounded-l-full p-4 active:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-30"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      class="text-gray-600"
                    >
                      <path d="M5 12h14" />
                    </svg>
                  </button>
                  <span class="px-5 text-xl font-bold text-gray-900 tabular-nums">
                    {{ qty }}
                  </span>
                  <button
                    type="button"
                    (click)="inc()"
                    [disabled]="!canIncrease"
                    aria-label="Increase quantity"
                    class="rounded-r-full p-4 active:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-30"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      class="text-gray-600"
                    >
                      <path d="M5 12h14" />
                      <path d="M12 5v14" />
                    </svg>
                  </button>
                </div>

                <button
                  type="button"
                  (click)="add()"
                  [disabled]="!active || !inStock"
                  class="flex flex-1 items-center justify-center gap-3 rounded-full py-4 text-lg font-semibold text-white transition-all active:scale-95 disabled:cursor-not-allowed disabled:bg-gray-300 disabled:text-gray-600 disabled:shadow-none"
                  [class.bg-emerald-400]="added() && inStock"
                  [class.bg-emerald-600]="!added() && inStock"
                  [class.shadow-lg]="!added() && inStock"
                  [class.shadow-emerald-500\\/20]="!added() && inStock"
                >
                  @if (!inStock) {
                    Sold Out
                  } @else if (added()) {
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="22"
                      height="22"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="M20 6 9 17l-5-5" />
                    </svg>
                    Added!
                  } @else {
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="22"
                      height="22"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
                      <path d="M3 6h18" />
                      <path d="M16 10a4 4 0 0 1-8 0" />
                    </svg>
                    Add — {{ price * qty | currency }}
                  }
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    } @else {
      <div class="p-8 text-center text-gray-400">Product not found.</div>
    }
  `,
})
export class ProductPage {
  private readonly productGQL = inject(ProductGQL);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly cart = inject(CartService);

  protected readonly quantity = signal(1);
  protected readonly added = signal(false);
  private readonly selectedVariantId = signal<string | null>(null);

  private readonly id = toSignal(
    this.route.paramMap.pipe(map((p) => p.get('id'))),
    { initialValue: null },
  );

  private readonly resource = rxResource({
    params: () => this.id(),
    stream: ({ params: id }) =>
      id
        ? this.productGQL
            .fetch({ variables: { dispensaryId: environment.dispensaryId, id } })
            .pipe(map((r) => (r.data?.product ?? null) as ApiProduct | null))
        : of(null),
  });

  protected readonly loading = this.resource.isLoading;
  protected readonly product = computed<ApiProduct | null>(
    () => this.resource.value() ?? null,
  );

  protected readonly activeVariant = computed<ApiVariant | undefined>(() => {
    const p = this.product();
    if (!p) return undefined;
    const selectedId = this.selectedVariantId();
    if (selectedId) {
      const found = p.variants.find((v) => v.variantId === selectedId);
      if (found) return found;
    }
    return p.variants[0];
  });

  constructor() {
    effect(() => {
      const id = this.id();
      if (id) {
        this.selectedVariantId.set(null);
        this.quantity.set(1);
        this.added.set(false);
      }
    });
  }

  protected priceFor(variant: ApiVariant | undefined): number {
    return priceOf(variant);
  }

  protected effectsOf(p: ApiProduct): string[] {
    return asStringArray(p.effects);
  }

  protected flavorsOf(p: ApiProduct): string[] {
    return asStringArray(p.flavors);
  }

  protected strainStyleFor(value: string | null | undefined): StrainStyle {
    return STRAIN_STYLE[asStrainKey(value)];
  }

  protected orbStyle(name: string): { size: number; top: number; left: number } {
    const h = hashCode(name);
    return {
      size: 60 + (h % 30),
      top: 10 + (h % 25),
      left: 10 + ((h >> 4) % 25),
    };
  }

  protected selectVariant(variantId: string): void {
    if (!variantInStock(this.product()?.variants.find((v) => v.variantId === variantId))) return;
    this.selectedVariantId.set(variantId);
    this.quantity.set(1);
  }

  protected isVariantInStock(variant: ApiVariant): boolean {
    return variantInStock(variant);
  }

  protected stockFor(variant: ApiVariant | undefined): number {
    return variantStockQty(variant);
  }

  protected inc(): void {
    const max = variantStockQty(this.activeVariant());
    this.quantity.update((q) => Math.min(max, q + 1));
  }

  protected dec(): void {
    void this.quantity.update((q) => Math.max(1, q - 1));
  }

  protected add(): void {
    const p = this.product();
    const v = this.activeVariant();
    if (!p || !v || !variantInStock(v)) return;
    const max = variantStockQty(v);
    const price = priceOf(v);
    const qty = Math.min(this.quantity(), max);
    if (qty <= 0) return;
    for (let i = 0; i < qty; i += 1) {
      this.cart.addItem({
        productId: p.id,
        variantId: v.variantId,
        name: p.name,
        variantName: v.name,
        price,
        strainType: p.strainType ?? undefined,
      });
    }
    this.added.set(true);
    setTimeout(() => {
      this.added.set(false);
      this.router.navigateByUrl('/');
    }, ADDED_RESET_MS);
  }
}

// apps/kiosk/src/pages/ProductPage.tsx
import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { gql, DISPENSARY_ID } from '../lib/graphql';
import { useCartStore } from '../stores/cart.store';
import { ShoppingBag, Check, Minus, Plus } from 'lucide-react';

const QUERY = `query($id: ID!) { products(dispensaryId: $id) {
  id name description strainType strainName thcPercent cbdPercent effects flavors
  variants { variantId name sku retailPrice }
}}`;

const STRAIN_STYLE: Record<string, { bg: string; badge: string; orb: string }> = {
  sativa:  { bg: 'from-amber-100 via-orange-50 to-yellow-50', badge: 'bg-amber-500 text-white', orb: '#f59e0b' },
  indica:  { bg: 'from-violet-100 via-purple-50 to-indigo-50', badge: 'bg-violet-500 text-white', orb: '#8b5cf6' },
  hybrid:  { bg: 'from-emerald-100 via-green-50 to-teal-50', badge: 'bg-emerald-500 text-white', orb: '#10b981' },
};

function hashCode(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) hash = ((hash << 5) - hash) + str.charCodeAt(i) | 0;
  return Math.abs(hash);
}

export function ProductPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const addItem = useCartStore((s) => s.addItem);
  const [selVariant, setSelVariant] = useState<string | null>(null);
  const [qty, setQty] = useState(1);
  const [added, setAdded] = useState(false);

  const { data: product } = useQuery({
    queryKey: ['kioskProduct', id],
    queryFn: async () => {
      const d = await gql<any>(QUERY, { id: DISPENSARY_ID });
      return (d.products ?? []).find((p: any) => p.id === id);
    },
  });

  if (!product) return (
    <div className="flex items-center justify-center h-[60vh]">
      <div className="w-8 h-8 border-2 border-emerald-300 border-t-transparent rounded-full animate-spin" />
    </div>
  );

  const variants = product.variants ?? [];
  const active = selVariant ? variants.find((v: any) => v.variantId === selVariant) : variants[0];
  const price = active?.retailPrice ? Number(active.retailPrice) : 0;
  const effects: string[] = Array.isArray(product.effects) ? product.effects : [];
  const flavors: string[] = Array.isArray(product.flavors) ? product.flavors : [];
  const strain = STRAIN_STYLE[product.strainType || 'hybrid'] || STRAIN_STYLE.hybrid;
  const hash = hashCode(product.name);

  const handleAdd = () => {
    if (!active) return;
    for (let i = 0; i < qty; i++) addItem({ productId: product.id, variantId: active.variantId, name: product.name, variantName: active.name, price, strainType: product.strainType });
    setAdded(true);
    setTimeout(() => { setAdded(false); navigate('/'); }, 1500);
  };

  return (
    <div className="p-6 lg:p-8 max-w-5xl mx-auto">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
        {/* Product visual */}
        <div className={`aspect-square bg-gradient-to-br ${strain.bg} rounded-3xl overflow-hidden relative`}>
          <div className="absolute rounded-full opacity-20 blur-3xl"
            style={{
              width: `${60 + (hash % 30)}%`, height: `${60 + (hash % 30)}%`,
              top: `${10 + (hash % 25)}%`, left: `${10 + ((hash >> 4) % 25)}%`,
              background: strain.orb,
            }} />
          <div className="absolute rounded-full opacity-10 blur-2xl"
            style={{
              width: `${40 + ((hash >> 8) % 25)}%`, height: `${40 + ((hash >> 8) % 25)}%`,
              bottom: `${10 + ((hash >> 12) % 20)}%`, right: `${10 + ((hash >> 16) % 20)}%`,
              background: strain.orb,
            }} />
          {product.strainType && (
            <span className={`absolute top-5 left-5 text-sm font-bold tracking-wider uppercase px-4 py-1.5 rounded-full ${strain.badge} shadow-md`}>
              {product.strainType}
            </span>
          )}
          <div className="absolute bottom-5 left-5 flex gap-2">
            {product.thcPercent != null && (
              <div className="bg-white/90 backdrop-blur-sm rounded-xl px-4 py-2 shadow-sm">
                <span className="text-[10px] text-gray-500 uppercase tracking-wider">THC</span>
                <p className="text-lg font-bold text-gray-900">{product.thcPercent}%</p>
              </div>
            )}
            {product.cbdPercent != null && product.cbdPercent > 0 && (
              <div className="bg-white/90 backdrop-blur-sm rounded-xl px-4 py-2 shadow-sm">
                <span className="text-[10px] text-gray-500 uppercase tracking-wider">CBD</span>
                <p className="text-lg font-bold text-gray-900">{product.cbdPercent}%</p>
              </div>
            )}
          </div>
        </div>

        {/* Details */}
        <div className="flex flex-col justify-center">
          <h1 className="text-3xl lg:text-4xl font-light text-gray-900" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
            {product.name}
          </h1>
          {product.strainName && product.strainName !== product.name && (
            <p className="text-sm text-gray-400 mt-1 italic">{product.strainName}</p>
          )}

          {product.description && (
            <p className="text-gray-500 mt-5 leading-relaxed">{product.description}</p>
          )}

          {effects.length > 0 && (
            <div className="mt-6">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider mb-2">Effects</p>
              <div className="flex flex-wrap gap-2">
                {effects.map((e: string) => (
                  <span key={e} className="bg-emerald-50 text-emerald-700 text-sm font-medium px-3 py-1.5 rounded-full border border-emerald-100">
                    {e}
                  </span>
                ))}
              </div>
            </div>
          )}

          {flavors.length > 0 && (
            <div className="mt-4">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider mb-2">Flavors</p>
              <div className="flex flex-wrap gap-2">
                {flavors.map((f: string) => (
                  <span key={f} className="bg-orange-50 text-orange-700 text-sm font-medium px-3 py-1.5 rounded-full border border-orange-100">
                    {f}
                  </span>
                ))}
              </div>
            </div>
          )}

          {variants.length > 1 && (
            <div className="mt-6">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider mb-2">Options</p>
              <div className="flex gap-2">
                {variants.map((v: any) => (
                  <button key={v.variantId} onClick={() => setSelVariant(v.variantId)}
                    className={`px-5 py-3 rounded-full text-sm font-semibold border-2 transition-all active:scale-95 ${
                      (selVariant || variants[0]?.variantId) === v.variantId
                        ? 'border-emerald-500 bg-emerald-50 text-emerald-700'
                        : 'border-gray-200 text-gray-500 hover:border-emerald-200'
                    }`}>
                    {v.name}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Price + Add */}
          <div className="mt-8 p-6 bg-gray-50 rounded-2xl">
            <div className="flex items-center justify-between mb-5">
              <span className="text-4xl font-bold text-gray-900">${price.toFixed(2)}</span>
              {variants[0]?.name && variants[0].name !== 'Standard' && (
                <span className="text-sm text-gray-400">/ {active?.name}</span>
              )}
            </div>

            <div className="flex items-center gap-4">
              <div className="flex items-center bg-white border border-gray-200 rounded-full">
                <button onClick={() => setQty(Math.max(1, qty - 1))} className="p-4 hover:bg-gray-50 rounded-l-full active:bg-gray-100">
                  <Minus size={20} className="text-gray-600" />
                </button>
                <span className="px-5 text-xl font-bold tabular-nums text-gray-900">{qty}</span>
                <button onClick={() => setQty(qty + 1)} className="p-4 hover:bg-gray-50 rounded-r-full active:bg-gray-100">
                  <Plus size={20} className="text-gray-600" />
                </button>
              </div>

              <button onClick={handleAdd}
                className={`flex-1 flex items-center justify-center gap-3 py-4 rounded-full text-lg font-semibold text-white transition-all active:scale-95 ${
                  added
                    ? 'bg-emerald-400'
                    : 'bg-emerald-600 hover:bg-emerald-500 shadow-lg shadow-emerald-500/20'
                }`}>
                {added ? <><Check size={22} /> Added!</> : <><ShoppingBag size={22} /> Add — ${(price * qty).toFixed(2)}</>}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
