// apps/admin/src/pages/LoyaltyPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { Star, Gift, Users, TrendingUp, Plus } from 'lucide-react';

const DISP = localStorage.getItem('cannasaas-dispensary-id') || 'b406186e-4d6a-425b-b7af-851cde868c5c';
const STATS_Q = `query($id: ID!) { loyaltyStats(dispensaryId: $id) { activeMembers totalEarned totalRedeemed redemptionCount birthdayClaims tierBreakdown { tier count } } }`;
const REWARDS_Q = `query($id: ID!) { availableRewards(dispensaryId: $id) { rewardId name description pointsCost rewardType rewardValue } }`;
const CREATE_REWARD = `mutation($id:ID!,$n:String!,$pts:Int!,$t:String!,$v:Float!,$desc:String) { createReward(dispensaryId:$id,name:$n,pointsCost:$pts,rewardType:$t,rewardValue:$v,description:$desc) }`;

const TIER_COLORS: Record<string,string> = { bronze:'bg-amber-100 text-amber-800', silver:'bg-gray-200 text-gray-700', gold:'bg-yellow-100 text-yellow-800', platinum:'bg-slate-200 text-slate-700' };

export function LoyaltyPage() {
  const qc = useQueryClient();
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name:'', pointsCost:'', rewardType:'discount_percent', rewardValue:'', description:'' });

  const { data: stats } = useQuery({ queryKey: ['loyaltyStats'], queryFn: () => gqlRequest<any>(STATS_Q, { id: DISP }), select: d => d.loyaltyStats });
  const { data: rewards } = useQuery({ queryKey: ['rewards'], queryFn: () => gqlRequest<any>(REWARDS_Q, { id: DISP }), select: d => d.availableRewards });

  const createMut = useMutation({
    mutationFn: () => gqlRequest(CREATE_REWARD, { id: DISP, n: form.name, pts: parseInt(form.pointsCost), t: form.rewardType, v: parseFloat(form.rewardValue), desc: form.description || null }),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['rewards'] }); setShowCreate(false); setForm({ name:'', pointsCost:'', rewardType:'discount_percent', rewardValue:'', description:'' }); },
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-txt">Loyalty Program</h1>
        <button onClick={() => setShowCreate(!showCreate)} className="flex items-center gap-1.5 bg-brand-600 text-txt-inverse px-4 py-2 rounded-lg text-sm font-medium hover:bg-brand-700">
          <Plus size={16} /> New Reward
        </button>
      </div>

      {/* KPIs */}
      {stats && (
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          <div className="bg-surface rounded-xl border border-border p-4 text-center">
            <Users size={18} className="mx-auto text-brand-600 mb-1" />
            <p className="text-2xl font-bold">{stats.activeMembers}</p>
            <p className="text-xs text-txt-secondary">Active Members</p>
          </div>
          <div className="bg-surface rounded-xl border border-border p-4 text-center">
            <TrendingUp size={18} className="mx-auto text-green-600 mb-1" />
            <p className="text-2xl font-bold">{stats.totalEarned.toLocaleString()}</p>
            <p className="text-xs text-txt-secondary">Points Earned</p>
          </div>
          <div className="bg-surface rounded-xl border border-border p-4 text-center">
            <Gift size={18} className="mx-auto text-purple-600 mb-1" />
            <p className="text-2xl font-bold">{stats.totalRedeemed.toLocaleString()}</p>
            <p className="text-xs text-txt-secondary">Points Redeemed</p>
          </div>
          <div className="bg-surface rounded-xl border border-border p-4 text-center">
            <p className="text-2xl font-bold">{stats.redemptionCount}</p>
            <p className="text-xs text-txt-secondary">Redemptions</p>
          </div>
          <div className="bg-surface rounded-xl border border-border p-4 text-center">
            <Star size={18} className="mx-auto text-amber-500 mb-1" />
            <p className="text-2xl font-bold">{stats.birthdayClaims}</p>
            <p className="text-xs text-txt-secondary">Birthday Claims</p>
          </div>
        </div>
      )}

      {/* Tier breakdown */}
      {stats?.tierBreakdown && (
        <div className="bg-surface rounded-xl border border-border p-6">
          <h2 className="font-semibold text-txt mb-3">Member Tiers</h2>
          <div className="grid grid-cols-4 gap-3">
            {stats.tierBreakdown.map((t: any) => (
              <div key={t.tier} className="text-center">
                <span className={'inline-block text-xs font-bold px-3 py-1 rounded-full mb-2 capitalize ' + (TIER_COLORS[t.tier] || 'bg-gray-100 text-gray-700')}>{t.tier}</span>
                <p className="text-2xl font-bold text-txt">{t.count}</p>
                <p className="text-xs text-txt-secondary">members</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Create reward form */}
      {showCreate && (
        <div className="bg-surface rounded-xl border border-border p-6 space-y-3">
          <h2 className="font-semibold">New Reward</h2>
          <div className="grid grid-cols-3 gap-3">
            <input value={form.name} onChange={e => setForm({...form, name: e.target.value})} placeholder="Reward name *" className="px-3 py-2 border border-border rounded-lg text-sm" />
            <input value={form.pointsCost} onChange={e => setForm({...form, pointsCost: e.target.value})} placeholder="Points cost *" type="number" className="px-3 py-2 border border-border rounded-lg text-sm" />
            <select value={form.rewardType} onChange={e => setForm({...form, rewardType: e.target.value})} className="px-3 py-2 border border-border rounded-lg text-sm">
              <option value="discount_percent">% Discount</option><option value="discount_fixed">$ Off</option><option value="free_item">Free Item</option><option value="free_delivery">Free Delivery</option>
            </select>
            <input value={form.rewardValue} onChange={e => setForm({...form, rewardValue: e.target.value})} placeholder="Value (e.g. 10 for 10%)" type="number" className="px-3 py-2 border border-border rounded-lg text-sm" />
            <input value={form.description} onChange={e => setForm({...form, description: e.target.value})} placeholder="Description" className="px-3 py-2 border border-border rounded-lg text-sm col-span-2" />
          </div>
          <button onClick={() => createMut.mutate()} disabled={!form.name || !form.pointsCost} className="bg-brand-600 text-txt-inverse px-4 py-2 rounded-lg text-sm font-medium hover:bg-brand-700 disabled:opacity-50">Create Reward</button>
        </div>
      )}

      {/* Rewards catalog */}
      <div className="bg-surface rounded-xl border border-border overflow-hidden">
        <div className="px-4 py-3 bg-bg-alt border-b font-semibold text-gray-700">Rewards Catalog</div>
        <table className="w-full text-sm">
          <thead><tr>
            <th className="text-left px-4 py-2 text-txt-secondary">Reward</th>
            <th className="text-right px-4 py-2 text-txt-secondary">Points Cost</th>
            <th className="text-center px-4 py-2 text-txt-secondary">Type</th>
            <th className="text-right px-4 py-2 text-txt-secondary">Value</th>
          </tr></thead>
          <tbody className="divide-y divide-gray-50">
            {(rewards ?? []).map((r: any) => (
              <tr key={r.rewardId}>
                <td className="px-4 py-3"><p className="font-medium text-txt">{r.name}</p>{r.description && <p className="text-xs text-txt-muted">{r.description}</p>}</td>
                <td className="px-4 py-3 text-right tabular-nums font-bold text-brand-700">{r.pointsCost} pts</td>
                <td className="px-4 py-3 text-center text-xs text-txt-secondary">{r.rewardType.replace(/_/g, ' ')}</td>
                <td className="px-4 py-3 text-right tabular-nums">{r.rewardType.includes('percent') ? r.rewardValue + '%' : '$' + parseFloat(r.rewardValue).toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// packages/angular/projects/admin/src/app/pages/loyalty/loyalty-page.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { LoyaltyService, type LoyaltyReward } from './loyalty.service';

interface CreateRewardFormControls {
  readonly name: FormControl<string>;
  readonly pointsCost: FormControl<string>;
  readonly rewardType: FormControl<string>;
  readonly rewardValue: FormControl<string>;
  readonly description: FormControl<string>;
}

const REWARD_TYPES = [
  { value: 'discount_percent', label: '% Discount' },
  { value: 'discount_fixed', label: '$ Off' },
  { value: 'free_item', label: 'Free Item' },
  { value: 'free_delivery', label: 'Free Delivery' },
];

/**
 * Loyalty admin: 5 KPI cards + tier breakdown + create-reward form
 * + rewards catalog table. Mirrors React parity.
 *
 * Filed scope mentioned customer-points adjust (manual credit/debit
 * with audit reason) and "loyalty settings" (points-per-dollar,
 * redemption rules). React surfaces neither — file a follow-up if
 * those become workflow needs.
 */
@Component({
  selector: 'cs-loyalty-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule],
  template: `
    <section class="space-y-6">
      <header class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-(--color-text)">Loyalty program</h1>
        <button
          type="button"
          (click)="toggleCreate()"
          class="rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover)"
        >
          {{ showCreate() ? 'Cancel' : '+ New reward' }}
        </button>
      </header>

      @if (loading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading loyalty…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load loyalty</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else {
        @if (stats(); as s) {
          <div class="grid grid-cols-2 gap-3 md:grid-cols-5">
            <article
              class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
            >
              <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                {{ s.activeMembers }}
              </p>
              <p class="text-xs text-(--color-text-secondary)">Active members</p>
            </article>
            <article
              class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
            >
              <p class="text-2xl font-bold text-emerald-500 tabular-nums">
                {{ s.totalEarned.toLocaleString() }}
              </p>
              <p class="text-xs text-(--color-text-secondary)">Points earned</p>
            </article>
            <article
              class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
            >
              <p class="text-2xl font-bold text-purple-500 tabular-nums">
                {{ s.totalRedeemed.toLocaleString() }}
              </p>
              <p class="text-xs text-(--color-text-secondary)">Points redeemed</p>
            </article>
            <article
              class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
            >
              <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                {{ s.redemptionCount }}
              </p>
              <p class="text-xs text-(--color-text-secondary)">Redemptions</p>
            </article>
            <article
              class="rounded-xl border border-(--color-border) bg-(--color-surface) p-4 text-center"
            >
              <p class="text-2xl font-bold text-amber-500 tabular-nums">
                {{ s.birthdayClaims }}
              </p>
              <p class="text-xs text-(--color-text-secondary)">Birthday claims</p>
            </article>
          </div>

          @if (s.tierBreakdown.length > 0) {
            <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
              <h2 class="mb-3 font-semibold text-(--color-text)">Member tiers</h2>
              <ul class="grid grid-cols-2 gap-3 md:grid-cols-4">
                @for (t of s.tierBreakdown; track t.tier) {
                  <li class="text-center">
                    <span
                      class="mb-2 inline-block rounded-full px-3 py-1 text-xs font-bold capitalize"
                      [class]="tierBadgeClass(t.tier)"
                    >
                      {{ t.tier }}
                    </span>
                    <p class="text-2xl font-bold text-(--color-text) tabular-nums">
                      {{ t.count }}
                    </p>
                    <p class="text-xs text-(--color-text-secondary)">members</p>
                  </li>
                }
              </ul>
            </div>
          }
        }

        @if (showCreate()) {
          <form
            [formGroup]="createForm"
            (ngSubmit)="onSubmit()"
            class="space-y-4 rounded-xl border border-(--color-border) bg-(--color-surface) p-6"
            aria-label="Create reward"
          >
            <h2 class="text-lg font-semibold text-(--color-text)">New reward</h2>
            <div class="grid grid-cols-1 gap-3 md:grid-cols-3">
              <input
                type="text"
                formControlName="name"
                placeholder="Reward name *"
                aria-label="Reward name"
                class="rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
              <input
                type="number"
                formControlName="pointsCost"
                placeholder="Points cost *"
                aria-label="Points cost"
                class="rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
              <select
                formControlName="rewardType"
                aria-label="Reward type"
                class="rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              >
                @for (t of rewardTypes; track t.value) {
                  <option [value]="t.value">{{ t.label }}</option>
                }
              </select>
              <input
                type="number"
                step="any"
                formControlName="rewardValue"
                placeholder="Value (e.g. 10 for 10%)"
                aria-label="Reward value"
                class="rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none"
              />
              <input
                type="text"
                formControlName="description"
                placeholder="Description"
                aria-label="Description"
                class="rounded-lg border border-(--color-border) bg-(--color-bg) px-3 py-2 text-sm text-(--color-text) focus:border-(--color-primary) focus:outline-none md:col-span-2"
              />
            </div>
            <button
              type="submit"
              [disabled]="createForm.invalid || saving()"
              class="rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover) disabled:opacity-50"
            >
              @if (saving()) {
                Saving…
              } @else {
                Create reward
              }
            </button>
          </form>
        }

        <div class="overflow-hidden rounded-xl border border-(--color-border) bg-(--color-surface)">
          <header
            class="border-b border-(--color-border) bg-(--color-bg) px-4 py-3 font-semibold text-(--color-text)"
          >
            Rewards catalog
          </header>
          @if (rewards().length === 0) {
            <p class="p-8 text-center text-sm text-(--color-text-muted)">No rewards yet.</p>
          } @else {
            <table class="w-full text-sm">
              <thead>
                <tr class="text-(--color-text-secondary)">
                  <th class="px-4 py-2 text-left">Reward</th>
                  <th class="px-4 py-2 text-right">Points cost</th>
                  <th class="px-4 py-2 text-center">Type</th>
                  <th class="px-4 py-2 text-right">Value</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-(--color-border)">
                @for (r of rewards(); track r.rewardId) {
                  <tr>
                    <td class="px-4 py-3">
                      <p class="font-medium text-(--color-text)">{{ r.name }}</p>
                      @if (r.description) {
                        <p class="text-xs text-(--color-text-muted)">{{ r.description }}</p>
                      }
                    </td>
                    <td class="px-4 py-3 text-right font-bold tabular-nums text-(--color-primary)">
                      {{ r.pointsCost }} pts
                    </td>
                    <td class="px-4 py-3 text-center text-xs text-(--color-text-secondary)">
                      {{ formatType(r.rewardType) }}
                    </td>
                    <td class="px-4 py-3 text-right tabular-nums text-(--color-text)">
                      {{ formatValue(r) }}
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          }
        </div>
      }
    </section>
  `,
})
export class LoyaltyPage {
  private readonly svc = inject(LoyaltyService);

  protected readonly rewardTypes = REWARD_TYPES;

  protected readonly stats = this.svc.stats;
  protected readonly rewards = this.svc.rewards;
  protected readonly loading = this.svc.isLoading;
  protected readonly error = this.svc.error;
  protected readonly saving = this.svc.saving;

  protected readonly showCreate = signal<boolean>(false);

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load loyalty data.';
  });

  /* eslint-disable @typescript-eslint/unbound-method --
   * Validators.* are pure functions; the rule's `this:void` warning
   * is a false positive for these references.
   */
  protected readonly createForm = new FormGroup<CreateRewardFormControls>({
    name: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    pointsCost: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    rewardType: new FormControl('discount_percent', { nonNullable: true }),
    rewardValue: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    description: new FormControl('', { nonNullable: true }),
  });
  /* eslint-enable @typescript-eslint/unbound-method */

  protected toggleCreate(): void {
    this.showCreate.update((v) => !v);
  }

  protected async onSubmit(): Promise<void> {
    if (this.createForm.invalid) return;
    const v = this.createForm.getRawValue();
    const points = parseInt(v.pointsCost, 10);
    const value = parseFloat(v.rewardValue);
    if (Number.isNaN(points) || Number.isNaN(value)) return;
    await this.svc.createReward({
      name: v.name,
      pointsCost: points,
      rewardType: v.rewardType,
      rewardValue: value,
      description: v.description.trim() || null,
    });
    this.createForm.reset({
      name: '',
      pointsCost: '',
      rewardType: 'discount_percent',
      rewardValue: '',
      description: '',
    });
    this.showCreate.set(false);
  }

  protected tierBadgeClass(tier: string): string {
    switch (tier.toLowerCase()) {
      case 'bronze':
        return 'bg-amber-500/15 text-amber-500';
      case 'silver':
        return 'bg-(--color-surface-hover) text-(--color-text-secondary)';
      case 'gold':
        return 'bg-yellow-500/15 text-yellow-500';
      case 'platinum':
        return 'bg-purple-500/15 text-purple-500';
      default:
        return 'bg-(--color-surface-hover) text-(--color-text-secondary)';
    }
  }

  protected formatType(type: string): string {
    return type.replace(/_/g, ' ');
  }

  protected formatValue(r: LoyaltyReward): string {
    return r.rewardType.includes('percent') ? r.rewardValue + '%' : '$' + r.rewardValue.toFixed(2);
  }
}
