// packages/angular/projects/storefront/src/app/features/account/loyalty-card.ts
import { ChangeDetectionStrategy, Component, computed, inject, resource } from '@angular/core';
import {
  AvailableRewardsGQL,
  AvailableRewardsQuery,
  MyLoyaltyGQL,
  MyLoyaltyQuery,
} from '@cannasaas/ui-ng';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { DispensaryContextService } from '../../core/tenant/dispensary-context.service';

type Loyalty = NonNullable<MyLoyaltyQuery['myLoyalty']>;
type Reward = AvailableRewardsQuery['availableRewards'][number];

@Component({
  selector: 'cs-loyalty-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (loyalty(); as l) {
      <div class="space-y-4">
        <section class="rounded-2xl border border-stone-200 bg-white p-6">
          <div class="mb-4 flex items-center justify-between">
            <div class="flex items-center gap-2">
              <svg
                class="h-5 w-5 text-amber-500"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
              >
                <path
                  d="M12 2l2.4 7.4H22l-6.2 4.5L18.2 21 12 16.5 5.8 21l2.4-7.1L2 9.4h7.6z"
                />
              </svg>
              <h3 class="font-semibold text-stone-900">Loyalty Rewards</h3>
            </div>
            <span
              class="rounded-full px-2.5 py-1 text-xs font-medium"
              [style.background-color]="tierBadgeBg()"
              [style.color]="tierColor()"
            >
              {{ l.tierName }}
            </span>
          </div>

          <p class="text-3xl font-bold tabular-nums text-stone-900">
            {{ l.points.toLocaleString() }}
            <span class="text-sm font-normal text-stone-500">points</span>
          </p>
          <p class="mt-1 text-xs text-stone-400">
            Earning {{ l.multiplier }}x points per $1
          </p>

          @if (l.nextTier; as next) {
            <div class="mt-4">
              <div class="mb-1 flex justify-between text-xs text-stone-500">
                <span>{{ l.tierName }}</span>
                <span>{{ next.name }} — {{ next.pointsNeeded }} pts to go</span>
              </div>
              <div class="h-2 overflow-hidden rounded-full bg-stone-100">
                <div
                  class="h-full rounded-full transition-all"
                  [style.width.%]="progressPct()"
                  [style.background-color]="tierColor()"
                ></div>
              </div>
            </div>
          }
        </section>

        @if (rewards().length > 0) {
          <section class="rounded-2xl border border-stone-200 bg-white p-6">
            <h3 class="mb-3 flex items-center gap-2 font-semibold text-stone-900">
              <svg
                class="h-4 w-4 text-emerald-700"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                aria-hidden="true"
              >
                <path d="M20 12v10H4V12M22 7H2v5h20V7zM12 22V7M12 7H7.5a2.5 2.5 0 010-5C11 2 12 7 12 7zM12 7h4.5a2.5 2.5 0 000-5C13 2 12 7 12 7z" />
              </svg>
              Available Rewards
            </h3>
            <div class="space-y-2">
              @for (r of rewards().slice(0, 4); track r.rewardId) {
                <div
                  class="flex items-center justify-between border-b border-stone-50 py-2 last:border-0"
                >
                  <div>
                    <p class="text-sm font-medium text-stone-900">{{ r.name }}</p>
                    @if (r.description) {
                      <p class="text-xs text-stone-400">{{ r.description }}</p>
                    }
                  </div>
                  <span
                    class="rounded-full px-2 py-1 text-xs font-bold tabular-nums"
                    [class]="
                      l.points >= r.pointsCost
                        ? 'bg-emerald-100 text-emerald-700'
                        : 'bg-stone-100 text-stone-500'
                    "
                  >
                    {{ r.pointsCost }} pts
                  </span>
                </div>
              }
            </div>
          </section>
        }
      </div>
    }
  `,
})
export class LoyaltyCard {
  private readonly auth = inject(AuthService);
  private readonly dispensary = inject(DispensaryContextService);
  private readonly myLoyaltyGQL = inject(MyLoyaltyGQL);
  private readonly availableRewardsGQL = inject(AvailableRewardsGQL);

  private readonly isAuthenticated = this.auth.isAuthenticated;

  private readonly loyaltyResource = resource<
    Loyalty | null,
    { dispensaryId: string | null; isAuthenticated: boolean }
  >({
    params: () => ({
      dispensaryId: this.dispensary.entityId(),
      isAuthenticated: this.isAuthenticated(),
    }),
    loader: async ({ params }) => {
      if (!params.isAuthenticated || !params.dispensaryId) return null;
      const result = await firstValueFrom(
        this.myLoyaltyGQL.fetch({
          variables: { dispensaryId: params.dispensaryId },
        }),
      );
      return result.data?.myLoyalty ?? null;
    },
  });

  private readonly rewardsResource = resource<
    readonly Reward[],
    { dispensaryId: string | null; isAuthenticated: boolean }
  >({
    params: () => ({
      dispensaryId: this.dispensary.entityId(),
      isAuthenticated: this.isAuthenticated(),
    }),
    loader: async ({ params }) => {
      if (!params.isAuthenticated || !params.dispensaryId) return [];
      const result = await firstValueFrom(
        this.availableRewardsGQL.fetch({
          variables: { dispensaryId: params.dispensaryId },
        }),
      );
      return result.data?.availableRewards ?? [];
    },
  });

  protected readonly loyalty = computed(() => this.loyaltyResource.value() ?? null);
  protected readonly rewards = computed(() => this.rewardsResource.value() ?? []);

  protected readonly tierColor = computed(() => this.loyalty()?.tierColor ?? '#CD7F32');
  protected readonly tierBadgeBg = computed(() => this.tierColor() + '22');

  protected readonly progressPct = computed(() => {
    const l = this.loyalty();
    if (!l?.nextTier) return 100;
    const currentMin = l.allTiers.find((t) => t.code === l.tier)?.minPoints ?? 0;
    const earnedInTier = l.lifetimePoints - currentMin;
    const tierSpan = l.nextTier.pointsNeeded + earnedInTier;
    if (tierSpan <= 0) return 100;
    return Math.min(100, (earnedInTier / tierSpan) * 100);
  });
}

// apps/storefront/src/components/loyalty/LoyaltyCard.tsx
'use client';
import { useEffect, useState } from 'react';
import { gqlAuth, DEFAULT_DISPENSARY_ID } from '@/lib/graphql';
import { Star, Gift } from 'lucide-react';

const LOYALTY_Q = `query($id: ID!) { myLoyalty(dispensaryId: $id) { points lifetimePoints tier tierName tierColor multiplier nextTier { name pointsNeeded } allTiers { name code minPoints color } } }`;
const REWARDS_Q = `query($id: ID!) { availableRewards(dispensaryId: $id) { rewardId name description pointsCost rewardType rewardValue } }`;

export function LoyaltyCard() {
  const [loyalty, setLoyalty] = useState<any>(null);
  const [rewards, setRewards] = useState<any[]>([]);

  useEffect(() => {
    gqlAuth<any>(LOYALTY_Q, { id: DEFAULT_DISPENSARY_ID }).then(d => { if (d.myLoyalty) setLoyalty(d.myLoyalty); }).catch(() => {});
    gqlAuth<any>(REWARDS_Q, { id: DEFAULT_DISPENSARY_ID }).then(d => { if (d.availableRewards) setRewards(d.availableRewards); }).catch(() => {});
  }, []);

  if (!loyalty) return null;

  const currentMin = loyalty.allTiers?.find((t: any) => t.code === loyalty.tier)?.minPoints || 0;
  const progress = loyalty.nextTier ? Math.min(100, ((loyalty.lifetimePoints - currentMin) / (loyalty.nextTier.pointsNeeded + loyalty.lifetimePoints - currentMin)) * 100) : 100;

  return (
    <div className="space-y-4">
      <div className="bg-white rounded-xl border border-gray-100 p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2"><Star size={20} className="text-amber-500" /><h3 className="font-semibold text-gray-900">Loyalty Rewards</h3></div>
          <span className="text-xs font-medium px-2.5 py-1 rounded-full" style={{ backgroundColor: (loyalty.tierColor || '#CD7F32') + '22', color: loyalty.tierColor || '#CD7F32' }}>{loyalty.tierName}</span>
        </div>
        <p className="text-3xl font-bold text-gray-900">{loyalty.points.toLocaleString()} <span className="text-sm font-normal text-gray-500">points</span></p>
        <p className="text-xs text-gray-400 mt-1">Earning {loyalty.multiplier}x points per $1</p>
        {loyalty.nextTier && (
          <div className="mt-4">
            <div className="flex justify-between text-xs text-gray-500 mb-1"><span>{loyalty.tierName}</span><span>{loyalty.nextTier.name} — {loyalty.nextTier.pointsNeeded} pts to go</span></div>
            <div className="h-2 bg-gray-100 rounded-full overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: progress + '%', backgroundColor: loyalty.tierColor || '#CD7F32' }} /></div>
          </div>
        )}
      </div>
      {rewards.length > 0 && (
        <div className="bg-white rounded-xl border border-gray-100 p-6">
          <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2"><Gift size={18} className="text-brand-600" /> Available Rewards</h3>
          <div className="space-y-2">
            {rewards.slice(0, 4).map(r => (
              <div key={r.rewardId} className="flex items-center justify-between py-2 border-b border-gray-50 last:border-0">
                <div><p className="text-sm font-medium text-gray-900">{r.name}</p>{r.description && <p className="text-xs text-gray-400">{r.description}</p>}</div>
                <span className={'text-xs font-bold px-2 py-1 rounded-full ' + (loyalty.points >= r.pointsCost ? 'bg-brand-100 text-brand-700' : 'bg-gray-100 text-gray-500')}>{r.pointsCost} pts</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
