// apps/admin/src/pages/MenuBoardPage.tsx
import { useState, useEffect, useCallback } from 'react';
import { useQuery } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { Maximize, Minimize, Leaf } from 'lucide-react';

const PRODUCTS_QUERY = `query($dispensaryId: ID!) {
  adminProducts(dispensaryId: $dispensaryId) {
    id name strainType thcPercent cbdPercent
    variants { variantId name retailPrice }
    category
  }
}`;

const PROMOTIONS_QUERY = `query($dispensaryId: ID!) {
  activePromotions(dispensaryId: $dispensaryId) {
    id title description productIds discountPercent
  }
}`;

const CATEGORIES = ['Flower', 'Edible', 'Vape', 'Pre-Roll', 'Concentrate', 'Topical', 'Tincture'];

const STRAIN_BADGE: Record<string, string> = {
  sativa: 'bg-amber-500/20 text-amber-300 border border-amber-500/30',
  indica: 'bg-purple-500/20 text-purple-300 border border-purple-500/30',
  hybrid: 'bg-green-500/20 text-green-300 border border-green-500/30',
};

export function MenuBoardPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const [activeCategoryIndex, setActiveCategoryIndex] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [clock, setClock] = useState(new Date());

  // Clock update every second
  useEffect(() => {
    const id = setInterval(() => setClock(new Date()), 1000);
    return () => clearInterval(id);
  }, []);

  // Auto-rotate categories every 15 seconds
  useEffect(() => {
    const id = setInterval(() => {
      setActiveCategoryIndex((prev) => (prev + 1) % CATEGORIES.length);
    }, 15_000);
    return () => clearInterval(id);
  }, []);

  // Products query — auto-refresh every 60s
  const { data: products } = useQuery({
    queryKey: ['menuBoardProducts', dispensaryId],
    queryFn: () => gqlRequest<any>(PRODUCTS_QUERY, { dispensaryId }),
    select: (d) => d.adminProducts ?? [],
    enabled: !!dispensaryId,
    refetchInterval: 60_000,
  });

  const { data: promotions } = useQuery({
    queryKey: ['menuBoardPromos', dispensaryId],
    queryFn: () => gqlRequest<any>(PROMOTIONS_QUERY, { dispensaryId }),
    select: (d) => d.activePromotions ?? [],
    enabled: !!dispensaryId,
    refetchInterval: 60_000,
  });

  const toggleFullscreen = useCallback(() => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen();
      setIsFullscreen(true);
    } else {
      document.exitFullscreen();
      setIsFullscreen(false);
    }
  }, []);

  useEffect(() => {
    const handler = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener('fullscreenchange', handler);
    return () => document.removeEventListener('fullscreenchange', handler);
  }, []);

  const activeCategory = CATEGORIES[activeCategoryIndex];
  const filtered = (products ?? []).filter(
    (p: any) => (p.category ?? '').toLowerCase() === activeCategory.toLowerCase(),
  );

  const promoProductIds = new Set(
    (promotions ?? []).flatMap((promo: any) => promo.productIds ?? []),
  );

  const getPrice = (p: any) => {
    const v = p.variants?.[0];
    return v?.retailPrice ? Number(v.retailPrice) : 0;
  };

  const formatTime = (d: Date) =>
    d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  return (
    <div className="min-h-screen bg-gray-950 text-white -m-8 p-8 relative">
      {/* Top bar */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <Leaf size={32} className="text-brand-400" />
          <h1 className="text-3xl font-bold">Menu Board</h1>
        </div>
        <div className="flex items-center gap-6">
          <span className="text-2xl font-mono text-gray-400 tabular-nums">{formatTime(clock)}</span>
          <button
            onClick={toggleFullscreen}
            className="p-2 text-gray-400 hover:text-white transition-colors"
            title={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
          >
            {isFullscreen ? <Minimize size={24} /> : <Maximize size={24} />}
          </button>
        </div>
      </div>

      {/* Category tabs */}
      <div className="flex gap-3 mb-8 overflow-x-auto pb-2">
        {CATEGORIES.map((cat, i) => (
          <button
            key={cat}
            onClick={() => setActiveCategoryIndex(i)}
            className={`px-6 py-3 rounded-xl text-sm font-semibold whitespace-nowrap transition-colors ${
              i === activeCategoryIndex
                ? 'bg-brand-600 text-white'
                : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Promotions banner */}
      {promotions && promotions.length > 0 && (
        <div className="mb-8 bg-gradient-to-r from-brand-600/20 to-purple-600/20 border border-brand-500/30 rounded-2xl p-6">
          <h2 className="text-xl font-bold text-brand-400 mb-2">Daily Specials</h2>
          <div className="flex flex-wrap gap-4">
            {promotions.map((promo: any) => (
              <div key={promo.id} className="bg-gray-900/50 rounded-xl px-5 py-3">
                <p className="font-semibold text-white">{promo.title}</p>
                {promo.discountPercent && (
                  <p className="text-brand-400 text-sm font-bold">{promo.discountPercent}% OFF</p>
                )}
                {promo.description && (
                  <p className="text-gray-400 text-sm mt-1">{promo.description}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Product grid */}
      {filtered.length > 0 ? (
        <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
          {filtered.map((p: any) => {
            const price = getPrice(p);
            const isPromo = promoProductIds.has(p.id);
            return (
              <div
                key={p.id}
                className={`bg-gray-900 rounded-2xl p-6 border transition-colors ${
                  isPromo ? 'border-brand-500/50 ring-1 ring-brand-500/20' : 'border-gray-800'
                }`}
              >
                {isPromo && (
                  <span className="inline-block text-xs font-bold text-brand-400 bg-brand-500/10 px-3 py-1 rounded-full mb-3">
                    SPECIAL
                  </span>
                )}
                <h3 className="text-xl font-bold text-white mb-2 leading-tight">{p.name}</h3>
                <div className="flex items-center gap-2 mb-3">
                  {p.strainType && (
                    <span className={`text-xs font-semibold uppercase px-3 py-1 rounded-full ${
                      STRAIN_BADGE[p.strainType] ?? STRAIN_BADGE.hybrid
                    }`}>
                      {p.strainType}
                    </span>
                  )}
                  {p.thcPercent && (
                    <span className="text-xs font-medium text-gray-400 bg-gray-800 px-3 py-1 rounded-full">
                      THC {p.thcPercent}%
                    </span>
                  )}
                </div>
                <p className="text-3xl font-bold text-brand-400">${price.toFixed(2)}</p>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="text-center py-20 text-gray-600">
          <p className="text-xl">No products in {activeCategory}</p>
        </div>
      )}
    </div>
  );
}

// packages/angular/projects/admin/src/app/pages/menu-board/menu-board-page.ts
import { DOCUMENT } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';

import {
  MenuBoardService,
  type ActivePromotion,
  type MenuBoardProduct,
} from './menu-board.service';

const CLOCK_INTERVAL_MS = 1_000;
const CATEGORY_ROTATE_MS = 15_000;
const CATEGORIES = [
  'Flower',
  'Edible',
  'Vape',
  'Pre-Roll',
  'Concentrate',
  'Topical',
  'Tincture',
] as const;

/**
 * In-store digital menu board. Mirrors the React `MenuBoardPage`:
 * full-bleed dark layout, live clock, auto-rotating category tabs,
 * promotions banner, product grid with strain + THC badges, and a
 * fullscreen toggle.
 *
 * **Known parity caveat:** the React filter `p.category === activeCategory`
 * runs against a field that doesn't exist on the current `Product`
 * type — so the React board renders empty grids in production today.
 * The Angular port keeps the category tabs as decorative auto-rotators
 * but shows all products in the grid. File a follow-up if real
 * category filtering is needed (the API has `primaryCategoryId` —
 * we'd need a categories lookup query to resolve the display name).
 *
 * Filed scope mentioned a "configure" form (featured products, layout,
 * refresh interval). React doesn't have one — this page IS the display,
 * not the configurator. Defer.
 */
@Component({
  selector: 'cs-menu-board-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="-m-8 min-h-screen bg-gray-950 p-8 text-white">
      <!-- Top bar -->
      <div class="mb-8 flex items-center justify-between">
        <div class="flex items-center gap-4">
          <span class="text-3xl text-emerald-400" aria-hidden="true">🌿</span>
          <h1 class="text-3xl font-bold">Menu Board</h1>
        </div>
        <div class="flex items-center gap-6">
          <span class="font-mono text-2xl tabular-nums text-gray-400" aria-label="Current time">
            {{ timeLabel() }}
          </span>
          <button
            type="button"
            (click)="onToggleFullscreen()"
            class="rounded-lg p-2 text-gray-400 transition-colors hover:text-white"
            [attr.aria-label]="isFullscreen() ? 'Exit fullscreen' : 'Enter fullscreen'"
            [attr.title]="isFullscreen() ? 'Exit fullscreen' : 'Enter fullscreen'"
          >
            {{ isFullscreen() ? '⊟' : '⊞' }}
          </button>
        </div>
      </div>

      <!-- Category tabs (auto-rotate every 15s) -->
      <nav class="mb-8 flex gap-3 overflow-x-auto pb-2" role="tablist" aria-label="Category tabs">
        @for (cat of categories; track cat; let i = $index) {
          <button
            type="button"
            role="tab"
            [attr.aria-selected]="activeCategoryIndex() === i"
            (click)="setActiveCategory(i)"
            class="whitespace-nowrap rounded-xl px-6 py-3 text-sm font-semibold transition-colors"
            [class]="
              activeCategoryIndex() === i
                ? 'bg-emerald-600 text-white'
                : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
            "
          >
            {{ cat }}
          </button>
        }
      </nav>

      <!-- Promotions banner -->
      @if (promotions().length > 0) {
        <div
          class="mb-8 rounded-2xl border border-emerald-500/30 bg-gradient-to-r from-emerald-600/20 to-purple-600/20 p-6"
          aria-label="Daily specials"
        >
          <h2 class="mb-2 text-xl font-bold text-emerald-400">Daily Specials</h2>
          <ul class="flex flex-wrap gap-4">
            @for (promo of promotions(); track promo.promoId) {
              <li class="rounded-xl bg-gray-900/50 px-5 py-3">
                <p class="font-semibold text-white">{{ promo.name }}</p>
                @if (discountLabel(promo); as label) {
                  <p class="text-sm font-bold text-emerald-400">{{ label }}</p>
                }
                @if (promo.description) {
                  <p class="mt-1 text-sm text-gray-400">{{ promo.description }}</p>
                }
              </li>
            }
          </ul>
        </div>
      }

      <!-- Product grid -->
      @if (products().length === 0) {
        <p class="py-20 text-center text-xl text-gray-600">No products to display.</p>
      } @else {
        <ul class="grid grid-cols-2 gap-5 lg:grid-cols-3 xl:grid-cols-4">
          @for (p of products(); track p.id) {
            <li class="rounded-2xl border border-gray-800 bg-gray-900 p-6">
              <h3 class="mb-2 text-xl font-bold leading-tight text-white">{{ p.name }}</h3>
              <div class="mb-3 flex items-center gap-2">
                @if (p.strainType) {
                  <span
                    class="rounded-full border px-3 py-1 text-xs font-semibold uppercase"
                    [class]="strainBadgeClass(p.strainType)"
                  >
                    {{ p.strainType }}
                  </span>
                }
                @if (p.thcPercent != null) {
                  <span
                    class="rounded-full bg-gray-800 px-3 py-1 text-xs font-medium text-gray-400"
                  >
                    THC {{ p.thcPercent }}%
                  </span>
                }
              </div>
              <p class="text-3xl font-bold text-emerald-400">
                {{ priceLabel(p) }}
              </p>
            </li>
          }
        </ul>
      }
    </div>
  `,
})
export class MenuBoardPage {
  private readonly svc = inject(MenuBoardService);
  private readonly document = inject(DOCUMENT);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly categories = CATEGORIES;
  protected readonly products = this.svc.products;
  protected readonly promotions = this.svc.promotions;

  protected readonly activeCategoryIndex = signal<number>(0);
  protected readonly clock = signal<Date>(new Date());
  protected readonly isFullscreen = signal<boolean>(false);

  protected readonly timeLabel = computed(() =>
    this.clock().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
  );

  constructor() {
    const clockId = setInterval(() => this.clock.set(new Date()), CLOCK_INTERVAL_MS);
    const rotateId = setInterval(
      () => this.activeCategoryIndex.update((i) => (i + 1) % CATEGORIES.length),
      CATEGORY_ROTATE_MS,
    );
    const handler = () => this.isFullscreen.set(!!this.document.fullscreenElement);
    this.document.addEventListener('fullscreenchange', handler);

    this.destroyRef.onDestroy(() => {
      clearInterval(clockId);
      clearInterval(rotateId);
      this.document.removeEventListener('fullscreenchange', handler);
    });

    // Track effect so manual clock-set in tests triggers CD.
    effect(() => {
      void this.clock();
    });
  }

  protected setActiveCategory(index: number): void {
    this.activeCategoryIndex.set(index);
  }

  protected onToggleFullscreen(): void {
    if (!this.document.fullscreenElement) {
      const el = this.document.documentElement;
      if (el.requestFullscreen) void el.requestFullscreen();
      this.isFullscreen.set(true);
    } else if (this.document.exitFullscreen) {
      void this.document.exitFullscreen();
      this.isFullscreen.set(false);
    }
  }

  protected priceLabel(p: MenuBoardProduct): string {
    const price = p.variants[0]?.retailPrice ?? 0;
    return '$' + price.toFixed(2);
  }

  protected discountLabel(promo: ActivePromotion): string | null {
    if (!promo.discountValue) return null;
    if (promo.type === 'percent' || promo.type === 'percentage') {
      return promo.discountValue + '% OFF';
    }
    return '$' + promo.discountValue.toFixed(2) + ' OFF';
  }

  protected strainBadgeClass(strain: string | null | undefined): string {
    switch (strain) {
      case 'sativa':
        return 'bg-amber-500/20 text-amber-300 border-amber-500/30';
      case 'indica':
        return 'bg-purple-500/20 text-purple-300 border-purple-500/30';
      case 'hybrid':
      default:
        return 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30';
    }
  }
}
