// apps/admin/src/pages/SchedulingPage.tsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { gqlRequest } from '../lib/graphql-client';
import { useAuthStore } from '../stores/auth.store';
import { CalendarDays, Truck, Clock, ChevronLeft, ChevronRight, Send } from 'lucide-react';

const WEEK_SCHEDULE = `query($id: ID!, $week: String!) { weekSchedule(dispensaryId: $id, weekStart: $week) {
  shiftId shiftDate startTime endTime status published
}}`;

const DRIVERS_QUERY = `query($id: ID!) { drivers(dispensaryId: $id) {
  driverId vehicleMake vehicleModel vehicleColor licensePlate status
}}`;

const DRIVER_STATS = `query($id: ID!) { driverStats(dispensaryId: $id) {
  totalTrips completed avgDeliveryMinutes avgRating totalMiles
}}`;

const TIME_OFF = `query($id: ID!) { timeOffRequests(dispensaryId: $id) {
  requestId startDate endDate requestType reason status
}}`;

const PUBLISH_WEEK = `mutation($id: ID!, $week: String!) { publishWeekSchedule(dispensaryId: $id, weekStart: $week) }`;

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function getWeekStart(offset = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - (d.getDay() || 7) + 1 + offset * 7);
  return d.toISOString().split('T')[0];
}

export function SchedulingPage() {
  const dispensaryId = useAuthStore((s) => s.user?.dispensaryId);
  const queryClient = useQueryClient();
  const [weekOffset, setWeekOffset] = useState(0);
  const weekStart = getWeekStart(weekOffset);

  const { data: shifts } = useQuery({
    queryKey: ['weekSchedule', dispensaryId, weekStart],
    queryFn: () => gqlRequest<any>(WEEK_SCHEDULE, { id: dispensaryId, week: weekStart }),
    select: (d) => d.weekSchedule,
    enabled: !!dispensaryId,
  });

  const { data: drivers } = useQuery({
    queryKey: ['drivers', dispensaryId],
    queryFn: () => gqlRequest<any>(DRIVERS_QUERY, { id: dispensaryId }),
    select: (d) => d.drivers,
    enabled: !!dispensaryId,
  });

  const { data: driverStats } = useQuery({
    queryKey: ['driverStats', dispensaryId],
    queryFn: () => gqlRequest<any>(DRIVER_STATS, { id: dispensaryId }),
    select: (d) => d.driverStats,
    enabled: !!dispensaryId,
  });

  const { data: timeOff } = useQuery({
    queryKey: ['timeOff', dispensaryId],
    queryFn: () => gqlRequest<any>(TIME_OFF, { id: dispensaryId }),
    select: (d) => d.timeOffRequests,
    enabled: !!dispensaryId,
  });

  const publishMutation = useMutation({
    mutationFn: () => gqlRequest(PUBLISH_WEEK, { id: dispensaryId, week: weekStart }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['weekSchedule'] }),
  });

  // Group shifts by day
  const shiftsByDay: Record<string, any[]> = {};
  (shifts ?? []).forEach((s: any) => {
    const day = s.shiftDate?.split('T')?.[0] ?? s.shiftDate;
    if (!shiftsByDay[day]) shiftsByDay[day] = [];
    shiftsByDay[day].push(s);
  });

  const weekDates = DAYS.map((_, i) => {
    const d = new Date(weekStart);
    d.setDate(d.getDate() + i);
    return d.toISOString().split('T')[0];
  });

  const unpublishedCount = (shifts ?? []).filter((s: any) => !s.published).length;
  const ds = driverStats ?? {};
  const pendingTimeOff = (timeOff ?? []).filter((t: any) => t.status === 'pending');

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-txt">Scheduling</h1>

      {/* Week Navigation */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <button onClick={() => setWeekOffset(weekOffset - 1)} className="p-2 rounded-lg border border-border hover:bg-bg-alt"><ChevronLeft size={16} /></button>
          <h2 className="text-lg font-semibold">
            <CalendarDays size={18} className="inline mr-2 text-brand-600" />
            Week of {weekStart}
          </h2>
          <button onClick={() => setWeekOffset(weekOffset + 1)} className="p-2 rounded-lg border border-border hover:bg-bg-alt"><ChevronRight size={16} /></button>
          <button onClick={() => setWeekOffset(0)} className="text-xs text-brand-600 hover:text-brand-700">Today</button>
        </div>
        {unpublishedCount > 0 && (
          <button onClick={() => publishMutation.mutate()}
            className="flex items-center gap-1.5 bg-brand-600 text-txt-inverse text-sm font-medium px-4 py-2 rounded-lg hover:bg-brand-700">
            <Send size={14} /> Publish {unpublishedCount} shifts
          </button>
        )}
      </div>

      {/* Week Grid */}
      <div className="grid grid-cols-7 gap-2">
        {weekDates.map((date, i) => {
          const dayShifts = shiftsByDay[date] ?? [];
          const isToday = date === new Date().toISOString().split('T')[0];
          return (
            <div key={date} className={`bg-surface rounded-xl border p-3 min-h-[120px] ${isToday ? 'border-brand-300 bg-brand-50/30' : 'border-border'}`}>
              <p className={`text-xs font-semibold mb-2 ${isToday ? 'text-brand-700' : 'text-txt-secondary'}`}>
                {DAYS[i]} {date.slice(5)}
              </p>
              {dayShifts.length > 0 ? (
                <div className="space-y-1">
                  {dayShifts.map((s: any) => (
                    <div key={s.shiftId} className={`text-[10px] px-2 py-1 rounded ${s.published ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700'}`}>
                      {s.startTime?.slice(0, 5)}-{s.endTime?.slice(0, 5)}
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-[10px] text-txt-muted">No shifts</p>
              )}
            </div>
          );
        })}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Delivery Drivers */}
        <div className="bg-surface rounded-xl border border-border p-6">
          <h2 className="text-lg font-semibold text-txt mb-3 flex items-center gap-2">
            <Truck size={18} className="text-indigo-600" /> Delivery Drivers
          </h2>
          {drivers && drivers.length > 0 ? (
            <div className="space-y-2">
              {drivers.map((d: any) => (
                <div key={d.driverId} className="flex items-center justify-between p-3 bg-bg-alt rounded-lg">
                  <div>
                    <p className="text-sm font-medium">{d.vehicleYear ?? ''} {d.vehicleMake} {d.vehicleModel}</p>
                    <p className="text-xs text-txt-muted">{d.vehicleColor} · {d.licensePlate}</p>
                  </div>
                  <span className={`text-xs px-2 py-0.5 rounded-full ${
                    d.status === 'available' ? 'bg-green-50 text-green-700' :
                    d.status === 'on_delivery' ? 'bg-blue-50 text-blue-700' : 'bg-gray-200 text-gray-600'
                  }`}>{d.status}</span>
                </div>
              ))}
            </div>
          ) : <p className="text-sm text-txt-muted">No drivers configured</p>}

          {ds.totalTrips > 0 && (
            <div className="mt-4 pt-3 border-t border-border grid grid-cols-3 gap-2 text-center text-xs">
              <div><p className="font-bold text-lg">{ds.completed}</p><p className="text-txt-muted">Trips (30d)</p></div>
              <div><p className="font-bold text-lg">{ds.avgRating}</p><p className="text-txt-muted">Avg Rating</p></div>
              <div><p className="font-bold text-lg">{ds.totalMiles}</p><p className="text-txt-muted">Total Miles</p></div>
            </div>
          )}
        </div>

        {/* Time-Off Requests */}
        <div className="bg-surface rounded-xl border border-border p-6">
          <h2 className="text-lg font-semibold text-txt mb-3 flex items-center gap-2">
            <Clock size={18} className="text-amber-500" /> Time-Off Requests
            {pendingTimeOff.length > 0 && (
              <span className="bg-amber-100 text-amber-700 text-xs font-bold px-2 py-0.5 rounded-full">{pendingTimeOff.length} pending</span>
            )}
          </h2>
          {timeOff && timeOff.length > 0 ? (
            <div className="space-y-2">
              {timeOff.map((t: any) => (
                <div key={t.requestId} className="flex items-center justify-between p-3 bg-bg-alt rounded-lg">
                  <div>
                    <p className="text-sm font-medium">{t.startDate} to {t.endDate}</p>
                    <p className="text-xs text-txt-muted">{t.requestType.toUpperCase()} {t.reason ? `— ${t.reason}` : ''}</p>
                  </div>
                  <span className={`text-xs px-2 py-0.5 rounded-full ${
                    t.status === 'approved' ? 'bg-green-50 text-green-700' :
                    t.status === 'pending' ? 'bg-amber-50 text-amber-700' : 'bg-danger-bg text-danger'
                  }`}>{t.status}</span>
                </div>
              ))}
            </div>
          ) : <p className="text-sm text-txt-muted">No time-off requests</p>}
        </div>
      </div>
    </div>
  );
}

// packages/angular/projects/admin/src/app/pages/scheduling/scheduling-page.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';

import {
  SchedulingService,
  type Driver,
  type ScheduledShift,
  type TimeOff,
} from './scheduling.service';

const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const;

interface DayCell {
  readonly label: string;
  readonly date: string; // YYYY-MM-DD
  readonly isToday: boolean;
  readonly shifts: readonly ScheduledShift[];
}

function todayIso(): string {
  return new Date().toISOString().split('T')[0];
}

/**
 * Weekly scheduling overview. Mirrors React parity: read-only
 * week-grid, drivers panel + 30-day stats, time-off requests panel,
 * Publish-week button (disabled when zero unpublished shifts).
 *
 * Filed scope mentioned a CDK drag-drop assignment editor + create-
 * shift modal + conflict detection. None exist in React — that's a
 * larger feature that should land in a dedicated follow-up story.
 * For now this matches React behavior.
 */
@Component({
  selector: 'cs-scheduling-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="space-y-6">
      <h1 class="text-2xl font-bold text-(--color-text)">Scheduling</h1>

      <!-- Week nav -->
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <button
            type="button"
            (click)="prevWeek()"
            aria-label="Previous week"
            class="rounded-lg border border-(--color-border) bg-(--color-surface) p-2 text-(--color-text-secondary) hover:text-(--color-text)"
          >
            ‹
          </button>
          <h2 class="text-lg font-semibold text-(--color-text)">Week of {{ weekStart() }}</h2>
          <button
            type="button"
            (click)="nextWeek()"
            aria-label="Next week"
            class="rounded-lg border border-(--color-border) bg-(--color-surface) p-2 text-(--color-text-secondary) hover:text-(--color-text)"
          >
            ›
          </button>
          @if (weekOffset() !== 0) {
            <button
              type="button"
              (click)="resetWeek()"
              class="text-xs text-(--color-primary) hover:text-(--color-primary-hover)"
            >
              Today
            </button>
          }
        </div>

        @if (unpublishedCount() > 0) {
          <button
            type="button"
            (click)="onPublish()"
            [disabled]="publishing()"
            class="rounded-lg bg-(--color-primary) px-4 py-2 text-sm font-medium text-white hover:bg-(--color-primary-hover) disabled:opacity-50"
            aria-label="Publish unpublished shifts for this week"
          >
            @if (publishing()) {
              Publishing…
            } @else {
              Publish {{ unpublishedCount() }} shifts
            }
          </button>
        }
      </div>

      @if (loading()) {
        <p
          class="rounded-xl border border-(--color-border) bg-(--color-surface) p-8 text-center text-sm text-(--color-text-muted)"
        >
          Loading schedule…
        </p>
      } @else if (error(); as err) {
        <div
          class="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-rose-300"
          role="alert"
        >
          <h2 class="font-semibold">Failed to load schedule</h2>
          <p class="mt-1 text-sm">{{ errorMessage() }}</p>
        </div>
      } @else {
        <!-- Week grid -->
        <div class="grid grid-cols-7 gap-2">
          @for (cell of cells(); track cell.date) {
            <div
              class="min-h-[120px] rounded-xl border p-3"
              [class]="
                cell.isToday
                  ? 'border-(--color-primary) bg-(--color-primary)/5'
                  : 'border-(--color-border) bg-(--color-surface)'
              "
              [attr.aria-label]="cell.label + ' ' + cell.date"
            >
              <p
                class="mb-2 text-xs font-semibold"
                [class]="cell.isToday ? 'text-(--color-primary)' : 'text-(--color-text-secondary)'"
              >
                {{ cell.label }} {{ cell.date.slice(5) }}
              </p>
              @if (cell.shifts.length === 0) {
                <p class="text-[10px] text-(--color-text-muted)">No shifts</p>
              } @else {
                <ul class="space-y-1">
                  @for (s of cell.shifts; track s.shiftId) {
                    <li
                      class="rounded px-2 py-1 text-[10px]"
                      [class]="
                        s.published
                          ? 'bg-emerald-500/10 text-emerald-500'
                          : 'bg-amber-500/10 text-amber-500'
                      "
                    >
                      {{ shiftRangeLabel(s) }}
                    </li>
                  }
                </ul>
              }
            </div>
          }
        </div>

        <!-- Drivers + Time-off -->
        <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
          <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
            <h2 class="mb-3 flex items-center gap-2 text-lg font-semibold text-(--color-text)">
              <span aria-hidden="true">🚚</span> Delivery drivers
            </h2>
            @if (drivers().length === 0) {
              <p class="text-sm text-(--color-text-muted)">No drivers configured</p>
            } @else {
              <ul class="space-y-2">
                @for (d of drivers(); track d.driverId) {
                  <li class="flex items-center justify-between rounded-lg bg-(--color-bg) p-3">
                    <div>
                      <p class="text-sm font-medium text-(--color-text)">
                        {{ driverNameLabel(d) }}
                      </p>
                      <p class="text-xs text-(--color-text-muted)">
                        {{ driverDetailLabel(d) }}
                      </p>
                    </div>
                    <span
                      class="rounded-full px-2 py-0.5 text-xs"
                      [class]="driverStatusClass(d.status)"
                    >
                      {{ d.status }}
                    </span>
                  </li>
                }
              </ul>
            }

            @if (driverStats(); as ds) {
              @if (ds.totalTrips > 0) {
                <div
                  class="mt-4 grid grid-cols-3 gap-2 border-t border-(--color-border) pt-3 text-center text-xs"
                >
                  <div>
                    <p class="text-lg font-bold text-(--color-text) tabular-nums">
                      {{ ds.completed }}
                    </p>
                    <p class="text-(--color-text-muted)">Trips (30d)</p>
                  </div>
                  <div>
                    <p class="text-lg font-bold text-(--color-text) tabular-nums">
                      {{ ds.avgRating.toFixed(1) }}
                    </p>
                    <p class="text-(--color-text-muted)">Avg rating</p>
                  </div>
                  <div>
                    <p class="text-lg font-bold text-(--color-text) tabular-nums">
                      {{ ds.totalMiles.toFixed(0) }}
                    </p>
                    <p class="text-(--color-text-muted)">Total miles</p>
                  </div>
                </div>
              }
            }
          </div>

          <div class="rounded-xl border border-(--color-border) bg-(--color-surface) p-6">
            <h2 class="mb-3 flex items-center gap-2 text-lg font-semibold text-(--color-text)">
              <span class="text-amber-500" aria-hidden="true">⏱</span>
              Time-off requests
              @if (pendingTimeOff().length > 0) {
                <span
                  class="rounded-full bg-amber-500/15 px-2 py-0.5 text-xs font-bold text-amber-500"
                >
                  {{ pendingTimeOff().length }} pending
                </span>
              }
            </h2>
            @if (timeOff().length === 0) {
              <p class="text-sm text-(--color-text-muted)">No time-off requests</p>
            } @else {
              <ul class="space-y-2">
                @for (t of timeOff(); track t.requestId) {
                  <li class="flex items-center justify-between rounded-lg bg-(--color-bg) p-3">
                    <div>
                      <p class="text-sm font-medium text-(--color-text)">
                        {{ t.startDate }} to {{ t.endDate }}
                      </p>
                      <p class="text-xs text-(--color-text-muted)">
                        {{ requestLabel(t) }}
                      </p>
                    </div>
                    <span
                      class="rounded-full px-2 py-0.5 text-xs"
                      [class]="timeOffStatusClass(t.status)"
                    >
                      {{ t.status }}
                    </span>
                  </li>
                }
              </ul>
            }
          </div>
        </div>
      }
    </section>
  `,
})
export class SchedulingPage {
  private readonly svc = inject(SchedulingService);

  protected readonly shifts = this.svc.shifts;
  protected readonly drivers = this.svc.drivers;
  protected readonly driverStats = this.svc.driverStats;
  protected readonly timeOff = this.svc.timeOff;
  protected readonly loading = this.svc.isLoading;
  protected readonly error = this.svc.error;
  protected readonly publishing = this.svc.publishing;
  protected readonly weekOffset = this.svc.weekOffset;
  protected readonly weekStart = this.svc.weekStart;

  protected readonly errorMessage = computed(() => {
    const err = this.error();
    return err instanceof Error ? err.message : 'Unable to load schedule.';
  });

  protected readonly unpublishedCount = computed(
    () => this.shifts().filter((s) => !s.published).length,
  );

  protected readonly pendingTimeOff = computed(() =>
    this.timeOff().filter((t) => t.status === 'pending'),
  );

  protected readonly cells = computed<readonly DayCell[]>(() => {
    const weekStart = this.weekStart();
    const today = todayIso();
    const shiftsByDate = new Map<string, ScheduledShift[]>();
    for (const s of this.shifts()) {
      const date = (s.shiftDate ?? '').split('T')[0];
      const list = shiftsByDate.get(date) ?? [];
      list.push(s);
      shiftsByDate.set(date, list);
    }
    return DAY_LABELS.map((label, i) => {
      const d = new Date(weekStart);
      d.setDate(d.getDate() + i);
      const date = d.toISOString().split('T')[0];
      return {
        label,
        date,
        isToday: date === today,
        shifts: shiftsByDate.get(date) ?? [],
      };
    });
  });

  protected prevWeek(): void {
    this.svc.shiftWeek(-1);
  }

  protected nextWeek(): void {
    this.svc.shiftWeek(1);
  }

  protected resetWeek(): void {
    this.svc.resetWeek();
  }

  protected onPublish(): void {
    void this.svc.publishWeek();
  }

  protected shiftRangeLabel(s: ScheduledShift): string {
    return (s.startTime ?? '').slice(0, 5) + '–' + (s.endTime ?? '').slice(0, 5);
  }

  protected driverNameLabel(d: Driver): string {
    const parts = [d.vehicleYear, d.vehicleMake, d.vehicleModel].filter(Boolean);
    return parts.join(' ') || 'Driver';
  }

  protected driverDetailLabel(d: Driver): string {
    const parts: string[] = [];
    if (d.vehicleColor) parts.push(d.vehicleColor);
    if (d.licensePlate) parts.push(d.licensePlate);
    return parts.join(' · ');
  }

  protected driverStatusClass(status: string): string {
    switch (status) {
      case 'available':
        return 'bg-emerald-500/10 text-emerald-500';
      case 'on_delivery':
      case 'on_trip':
        return 'bg-sky-500/10 text-sky-500';
      default:
        return 'bg-(--color-surface-hover) text-(--color-text-secondary)';
    }
  }

  protected requestLabel(t: TimeOff): string {
    const base = t.requestType.toUpperCase();
    return t.reason ? base + ' — ' + t.reason : base;
  }

  protected timeOffStatusClass(status: string): string {
    switch (status) {
      case 'approved':
        return 'bg-emerald-500/10 text-emerald-500';
      case 'pending':
        return 'bg-amber-500/10 text-amber-500';
      case 'denied':
      case 'rejected':
        return 'bg-rose-500/10 text-rose-500';
      default:
        return 'bg-(--color-surface-hover) text-(--color-text-secondary)';
    }
  }
}
